# (id, old span, new span, citations, tag)  tag: F fact/norm, X framing, H history
C = [
("c01","### 9.4 Activations: executable sets, laziness, caching","### 9.4 Activations: executable sets, laziness, caching",[],"F"),
("c02","An activation at `T` re-runs the activation step with a different scalar:","An activation at `T` re-runs it with a different scalar",[],"R",[]),
("c03","producer-fed cells are re-typed by walking the producing component's output declaration at `T` (§8.2).","Producer-fed cells are re-typed by walking the producing component's output declaration at `T` (§8.2).",["§8.2"],"F"),
("c04","A continuous producer's declaration follows the scalar at every unpinned leaf,","A continuous producer's declaration follows the scalar at every unpinned leaf.",[],"F"),
("c05","and a discrete producer's declaration pins;","A discrete producer's declaration pins.",[],"F"),
("c06","root-input cells are re-typed by walking the consuming `u_types` entry at `T`,","Root-input cells are re-typed by walking the consuming `u_types` entry at `T`.",[],"F"),
("c07","which §8.2 reads permissively.","§8.2 reads that entry permissively.",["§8.2"],"F"),
("c08","An unpinned entry follows the activation, and a `Pinned` entry stays frozen;","An unpinned entry follows the activation, and a `Pinned` entry stays frozen.",[],"F"),
("c09","the state type is re-derived by the walk over `x_init`'s,","The state type derived from `x_init` is re-derived by the leaf walk.",[],"R",[]),
("c10","with table and state buffers re-laid-out;","The table and state buffers are laid out again.",[],"F"),
("c11","workspace allocators are re-invoked at `T`,","Workspace allocators are invoked again, a continuous component's at `T` and a discrete component's at `Float64` (D-263).",[],"R",['D-263']),
("c12","not introduced.","The activation does not introduce them.",[],"F"),
("c13","The first invocation precedes the nominal evaluation's probes (§9.1/§9.3),","Their first invocation precedes the nominal evaluation's probes (§9.1/§9.3).",["§9.1","§9.3"],"F"),
("c14","and a continuous component's scratch carries the activation's scalar (§7.3);","A continuous component's scratch carries the activation's scalar (§7.3).",["§7.3"],"F"),
("c15","the probe chain is re-run.","The probe chain runs again.",[],"F"),
("c16","`Structure`, the structure step's product, and `Outputs`, the nominal evaluation's, are `T`-independent by construction,","Neither depends on `T`, by construction.",[],"F"),
("c17","so no execution order and no name list changes across activations (D-253).","No execution order and no name list changes across activations (D-253).",["D-253"],"F"),
("c18","Each activation probes exactly the function set it can execute.","Each activation probes exactly the set of functions it can execute (D-052).",[],"R",['D-052']),
("c19","A `Dual` activation (linearization, gradient trim) evaluates the model at a frozen instant.","A `Dual` activation, as linearization and gradient trim use, evaluates the model at a frozen instant.",[],"F"),
("c20","Discrete stages are gated off holding `Float64` values (the §8.2 frozen-constant semantics),","Discrete stages are gated off and hold `Float64` values. This is the frozen-constant semantics of §8.2.",["§8.2"],"F"),
("c21","and guards and handlers never run,","Guards and handlers never run, because event localization",[],"F"),
("c22","because event localization is `Float64` sweeps by design (§10.4).","event localization runs as `Float64` sweeps by design (§10.4).",["§10.4"],"F"),
("c23","Only the continuous output stages (`y_state`/`y_direct`) and `x_deriv` ever see a `Dual`, so only they are probed.","Only the continuous output stages (`y_state`/`y_direct`) and `x_deriv` ever see a `Dual`. So only they are probed at it.",[],"F"),
("c24","Probing the discrete stages, `s_update`, or guards at `Dual` would check code against a number type it cannot receive.","Probing the discrete stages, `s_update` or the guards at `Dual` would check code against a number type it cannot receive.",[],"F"),
("c25","It is one rule with no special cases,","The rule has no special cases.",[],"F"),
("c26","and the §5.6 tracer activation follows it identically.","The §5.6 tracer activation follows it identically.",["§5.6"],"F"),
("c27","\"Tracer activation\" names the global set-tracer (D-012),","\"Tracer activation\" names the global set-tracer (D-012).",["D-012"],"F"),
("c28","a whole-model run at the tracer scalar, an activation like any other.","It is a whole-model run at the tracer scalar, an activation like any other.",[],"F"),
("c29","The cycle classifier (§5.6) is the other variant (D-012).","The cycle classifier (§5.6) is the other tracer variant (D-012).",["§5.6","D-012"],"F"),
("c30","It is the order-free per-member local trace,","It traces each member of a cycle locally and needs no execution order.",[],"F"),
("c31","which runs in the nominal evaluation's failure path and is not an activation at all.","It runs in the nominal evaluation's failure path and is not an activation at all.",[],"F"),
("c32","Lazy, with an opt-in exhaustive mode.","An opt-in exhaustive mode does it:",[],"X"),
("c33","Non-nominal activations run at first request, not at build.","Non-nominal activations run at first request, not at build (D-052).",[],"R",['D-052']),
("c34","The dominant cost is compiling the continuous chain a second time at `Dual`,","Their dominant cost is compiling the continuous chain a second time, at `Dual`,",[],"F"),
("c35","pure waste for interactive fly-around use.","and for interactive fly-around use that cost is pure waste.",[],"F"),
("c36","The price is stated openly.","Laziness has a price, and the spec states it openly.",[],"X"),
("c37","`build` succeeding does not certify the model linearizable.","A successful `build` does not certify that the model is linearizable.",[],"F"),
("c38","A pinned `Float64` (§7.2), whether hidden in a constructor","A pinned `Float64` (§7.2) can appear in two places. It may hide in a constructor.",["§7.2"],"F"),
("c39","or declared `Pinned` at a leaf that really participates (the misplaced pin, §8.2),","Or it may be declared `Pinned` at a leaf that really participates, which is the misplaced pin of §8.2.",["§8.2"],"F"),
("c40","lurks until the first `Dual` activation detonates it at the probe, naming the offending constructor or leaf.","Either one lurks until the first `Dual` activation. The probe then fails and names the offending constructor or leaf.",[],"F"),
("c41","The repository's test suite pins the invariant instead, as policy rather than advice (D-166).","Instead, the repository's test suite makes linearizability an invariant, held by policy rather than advice.",["D-166"],"R",[]),
("c42","Every component gets a `Dual` activation built in CI.","Every component gets a `Dual` activation built in CI (D-280).",[],"R",['D-280']),
("c43","`build(world; activations = (Float64, ProbeDual))` runs the exhaustive set,","This call runs the exhaustive set.",[],"F"),
("c44","catching both genericity violations and misplaced pins at PR time, at the cost of an activation per component.","It catches both genericity violations and misplaced pins at PR time, at the cost of one activation per component.",[],"F"),
("c45","The keyword is the whole entry point, and no separate check function exists (D-275).","The keyword is the whole entry point, and no separate check function exists (D-275).",["D-275"],"F"),
("c46","The same keyword is also recommended for the parallel-sweep idiom (§11.1).","The same keyword is also recommended for the parallel-sweep idiom (§11.1).",["§11.1"],"F"),
("c47","Pre-materialize the activations the sweep will need, and the shared `Build` is a fully immutable artifact, with no synchronization on any path.","Pre-materialize the activations the sweep will need. The shared `Build` is then a fully immutable artifact, with no synchronization on any path.",[],"F"),
("c48","`ProbeDual` is the framework's public canonical probe scalar, `const ProbeDual = ForwardDiff.Dual{ProbeTag, Float64, 1}`.","`ProbeDual` is the framework's public canonical probe scalar (D-099).",[],"R",['D-099']),
("c49","It exists because an activation is keyed by a concrete scalar type,","It exists because an activation is keyed by a concrete scalar type.",[],"F"),
("c50","and the bare `Dual` `UnionAll` cannot key one, be walked to, or answer `zero(T)`.","The bare `Dual` is a `UnionAll`. It cannot key an activation, be walked to, or answer `zero(T)`.",[],"F"),
("c51","Its width is arbitrary.","The width of `ProbeDual` is arbitrary.",[],"F"),
("c52","What CI pins is genericity, not any particular Jacobian, so one canonical width suffices even though §14.10 chunks at whatever widths it needs.","CI pins genericity, not any particular Jacobian. So one canonical width suffices, even though §14.10 chunks at whatever widths it needs.",["§14.10"],"F"),
("c53","Caching is implementation detail, not semantics.","Whether an activation is cached never changes a result (D-052).",[],"R",['D-052']),
("c54","An activation is a pure function of the build and the concrete scalar type, so the activation dictionary is the `Build`'s,","It lives there because an activation is a pure function of the build and the concrete scalar type.",[],"R",[]),
("c55","and the nominal `Float64` entry is one key in it like any other (D-253).","The nominal `Float64` entry is one key in the activation dictionary like any other (D-253).",["D-253"],"R",['D-253']),
("c56","Each entry holds layouts, compiled plans and a validated flag keyed by that type,","The cache is one activation dictionary, keyed by concrete scalar type. Each entry holds layouts, compiled plans and a validated flag.",[],"R",[]),
("c57","immutable once constructed and hence freely shareable.","An entry is immutable once constructed, and so it is freely shareable.",[],"F"),
("c58","Buffers are never cached, because every buffer set has exactly one owner.","Every buffer set has exactly one owner (D-282).",[],"R",['D-282']),
("c59","The `Simulation` owns its nominal activation's buffers, materialized from the cached layouts at construction,","The `Simulation` owns its nominal activation's buffers. They are materialized from the cached layouts at construction.",[],"F"),
("c60","which is what the loop's zero-allocation stepping runs on.","The loop's zero-allocation stepping runs on them.",[],"F"),
("c61","Every service invocation owns the scratch set it instantiates from those same layouts.","Every service invocation owns the scratch set it instantiates from those same layouts.",[],"F"),
("c62","§14.8 states this for `trim!`, and it is the general rule, not a trim-local one.","§14.8 states this for `trim!`. It is the general rule, not one local to trim.",["§14.8"],"F"),
("c63","Compiled code is cached by Julia itself, process-wide.","Julia itself caches compiled code, process-wide.",[],"F"),
("c64","What the framework cache saves is the expensive part, namely probe re-runs, layout construction, and Julia's compilation of the `Dual` chain.","The framework cache saves the expensive part, namely probe re-runs, layout construction, and Julia's compilation of the `Dual` chain.",[],"F"),
("c65","That is what actually amortizes in activation-reusing loops,","These savings amortize in loops that reuse an activation.",[],"F"),
("c66","such as the envelope-grid gain-schedule case, where hundreds of trim-then-linearize points pay those costs once.","In the envelope-grid gain-schedule case, hundreds of trim-then-linearize points pay those costs once.",[],"F"),
("c67","What does not amortize is the per-point allocation of a working store set,","The per-point allocation of a working store set does not amortize.",[],"F"),
("c68","which is O(model size) and trivial against the solve it feeds.","It is O(model size), and trivial against the solve it feeds.",[],"F"),
("c69","The zero-allocation invariant (§7.5) is scoped to the stepping loop,","The zero-allocation invariant (§7.5) covers only the stepping loop,",["§7.5"],"F"),
("c70","and the services were always allocation-tolerant.","and the services were always allocation-tolerant.",[],"F"),
("c71","Nothing numerical is ever cached.","Nothing numerical is ever cached.",[],"F"),
("c72","Note that `Dual{Tag,V,N}` carries the partial count,","`Dual{Tag,V,N}` carries the partial count.",[],"F"),
("c73","so a different seeding width is a different scalar type, hence a separate entry and a separate Julia compile.","A different seeding width is therefore a different scalar type. It gets a separate entry and a separate Julia compile.",[],"F"),
("c74","Lazy materialization is torn-state-free, normatively.","Lazy materialization is torn-state-free (D-281).",[],"R",['D-281']),
("c75","Concurrent first requests for the same activation must never expose partially populated cache state.","Concurrent first requests for the same activation must never expose partially populated cache state.",[],"F"),
("c76","The mechanism is unspecified,","The mechanism is unspecified.",[],"F"),
("c77","and a guard around insertion suffices, paid at service time and never on the hot path.","A guard around insertion suffices, paid at service time and never on the hot path.",[],"F"),
("c78","Since an activation is a pure function of build and scalar, the worst benign race is duplicated work.","An activation is a pure function of build and scalar, so the worst benign race is duplicated work.",[],"F"),
("c79","Torn state is excluded by contract, not by luck.","Torn state is excluded by contract, not by luck.",[],"F"),
]
# New text with no old source: listed for the user, never silent.
ADDED = [
 "By default, the build types the model only at `Float64`.",
 "Linearization and gradient trim need the same model at another scalar type, a `Dual`.",
 "An activation (the build's typed products at a given scalar type) supplies that typing.",
 "and redoes five things:",
 "This section states what an activation re-runs, which functions it probes, when it runs, and what the `Build` caches.",
 "Only the activation step re-runs for a new scalar (D-259).",
 "The activation cache lives on the `Build` and holds only immutable compiled artifacts (D-135).",
 "So buffers are never cached.",
]
