import json, os
H = os.path.dirname(os.path.abspath(__file__))
# (old, new, cites, newcites or None, tag, ruling or None)
R = [
("### 7.4 The fused-evaluation lineage (prior art and how we got here)", "### 7.4 The fused-evaluation lineage (prior art and how we got here)", [], None, "X", None),
("The §5.2 interfaces are the end point of a four-step simplification arc.", "The §5.2 interfaces are the end point of a four-step simplification arc.", ["§5.2"], None, "F", None),
("The arc is recorded here because each step replaced a mechanism with something smaller.", "The arc is recorded here because each step replaced a mechanism with something smaller.", [], None, "F", None),
("1. N output groups → exactly two (D-006), at the price of an occasional component split (§5.4).", "1. N output groups gave way to exactly two (D-006), at the price of an occasional component split (§5.4).", ["D-006", "§5.4"], None, "R", "R3"),
("2. Derivative binding → own-output access (D-015).", "2. Derivative binding gave way to own-output access (D-015).", ["D-015"], None, "R", "R3"),
("Passing the fresh signal table to `x_deriv`/`s_update` subsumes the declaration feature, and the \"binding\" becomes a one-line function body.", "Passing the fresh signal table to `x_deriv`/`s_update` subsumes the declaration feature, and the \"binding\" becomes a one-line function body.", [], None, "F", None),
("3. Separate state arguments → the state decoder (D-016, D-035).", "3. Separate state arguments gave way to the state decoder (D-016, D-035).", ["D-016", "D-035"], None, "R", "R3"),
("Step 4 later reversed the second half of this step.", "Step 4 later reversed the second half of this step.", [], None, "F", None),
("4. Decoder-exclusive state access → stores-and-views arguments.", "4. Decoder-exclusive state access gave way to stores-and-views arguments.", [], None, "R", "R3"),
("Step 3's second half was reversed (D-035).", "Step 3's second half was reversed (D-035).", ["D-035"], None, "F", None),
("Once §8.3 made publication a deliberate interface act, the identity decode stood revealed as transport.", "Once contract visibility (§8.3, D-034) made a port's publicity a declaration, the identity decode stood revealed as transport.", ["§8.3"], ["§8.3", "D-034"], "R", "R8"),
("It copied the buffer into cells so that a buffer view could be replaced by a cell view.", "It copied the buffer into cells so that a buffer view could be replaced by a cell view.", [], None, "F", None),
("The fixed point is the argument rule (§5.2), zero-copy views of the stores a function genuinely reads.", "The fixed point is the argument rule (§5.2). A function receives zero-copy views of the stores it genuinely reads.", ["§5.2"], None, "F", None),
("What survives of step 3 is the uniform shapes, the fused economics, and the stage-1 decoder itself (today's `y_state`).", "What survives of step 3 is the uniform shapes, the fused economics, and the stage-1 decoder itself (now `y_state`).", [], None, "R", "R8"),
("That decoder is no longer the sole state gate.", "That decoder is no longer the sole state gate.", [], None, "F", None),
("It is the no-feedthrough stage.", "It is the no-feedthrough stage.", [], None, "F", None),
("For orientation, here is the prior art.", "The prior art is given here for orientation.", [], None, "X", None),
("Every causal framework meets the shared-computation problem and resolves it per its architecture.", "Every causal framework meets the shared-computation problem and resolves it per its architecture.", [], None, "F", None),
("Simulink diagrams make integrators explicit blocks.", "Simulink diagrams make integrators explicit blocks.", [], None, "F", None),
("Derivatives are ordinary wires into `1/s`, and the computer/integrator split is their native idiom.", "Derivatives are ordinary wires into `1/s`, and the computer/integrator split is their native idiom.", [], None, "F", None),
("S-functions and FMUs use sanctioned mutable caches, DWork vectors and FMI's lazy-evaluation caching, between their `mdlDerivatives`/`mdlOutputs`-style callback pairs.", "S-functions and FMUs use sanctioned mutable caches between their `mdlDerivatives`/`mdlOutputs`-style callback pairs. The caches are DWork vectors and FMI's lazy-evaluation caching.", [], None, "F", None),
("Modelica/MTK write `der(x) = expr` natively with symbolic CSE.", "Modelica/MTK (ModelingToolkit) write `der(x) = expr` natively, with symbolic common-subexpression elimination.", [], None, "R", "R16"),
("The fused sweep plus signal-consuming `x_deriv`/`s_update` is the cache-free formulation that fits this design's purity rules.", "The fused sweep plus signal-consuming `x_deriv`/`s_update` is the cache-free formulation that fits this design's purity rules (D-015).", [], ["D-015"], "C", None),
("It is also what FlightCore's fused `f_ode!` did economically, minus the checked ordering.", "It is also what FlightCore's fused `f_ode!` (its in-place derivative function) did economically, minus the checked ordering.", [], None, "R", "R2"),
("The computer/integrator split remains fully expressible without any framework support.", "The computer/integrator split remains fully expressible without any framework support (D-015).", [], ["D-015"], "C", None),
("A stateless component computes derivatives as outputs, wired into a trivial state-holding component.", "A stateless component computes derivatives as outputs and is wired into a trivial state-holding component.", [], None, "F", None),
("It is the idiom of choice when the factoring earns reuse, for example one Newton–Euler solver shared across vehicle variants, or swappable kinematic descriptors against a common integrator shape.", "It is the idiom of choice when the factoring earns reuse. Two examples are one Newton–Euler solver shared across vehicle variants, and swappable kinematic descriptors against a common integrator shape.", [], None, "F", None),
("Against a split-form spelling of the same model (four components, thirteen connections), the merged form has half the components and wiring.", "Against a split-form spelling of a rigid-body kinematics and dynamics core (four components, thirteen connections), the merged form has half the components and wiring (D-015).", [], ["D-015"], "R", "R8"),
("Everything derivable from pose alone migrates to stage 1, shortening the stage-2 chain.", "Everything derivable from pose alone migrates to stage 1, shortening the stage-2 chain.", [], None, "F", None),
("### 7.5 Allocation policy: a scoped invariant", "### 7.5 Allocation policy: a scoped invariant", [], None, "X", None),
("The allocation policy is not dogma.", "The allocation policy is not dogma (D-014).", [], ["D-014"], "C", None),
("Three reasons support it, and only one is about speed.", "Three reasons support it, and only one is about speed.", [], None, "F", None),
("First, GC-pause jitter control for real-time.", "The first is GC-pause jitter control for real-time.", [], None, "F", None),
("Second, throughput for unattended runs (runs with empty staging and no snapshot readers).", "The second is throughput for unattended runs (runs with empty staging and no snapshot readers).", [], None, "F", None),
("Third, the canary.", "The third is the canary.", [], None, "F", None),
("An unexpected allocation is Julia's most reliable symptom of type instability.", "An unexpected allocation is Julia's most reliable symptom of type instability.", [], None, "F", None),
("A zero baseline therefore makes `@allocated == 0` a CI-testable invariant, one that catches inference regressions at the offending commit.", "A zero baseline therefore makes `@allocated == 0` a CI-testable invariant. That invariant catches inference regressions at the offending commit.", [], None, "F", None),
("Continuous hot path. This is per-stage evaluation, plus everything else that runs unconditionally per frame or boundary.", "The continuous hot path is per-stage evaluation, plus everything else that runs unconditionally per frame or boundary.", [], None, "F", None),
("Those unconditional items are guards, evaluated every boundary whether they fire or not, and `x_projection` at both of its §5.3 positions in the execution order.", "Those unconditional items are guards, evaluated every boundary whether they fire or not, and `x_projection` at both of its §5.3 positions in the execution order.", ["§5.3"], None, "F", None),
("The budget is exactly zero, CI-enforced at the §9.7 phase-body seam (`phase_bodies`).", "The budget is exactly zero, CI-enforced at the phase-body seam that `phase_bodies` exposes (§9.7, D-014, D-116).", ["§9.7"], ["§9.7", "D-014", "D-116"], "C", None),
("Periodic ticks and event handlers. These execute episodically, a tick when due and a handler only on firing.", "Periodic ticks and event handlers execute episodically. A tick runs when due, and a handler only on firing.", [], None, "F", None),
("Allocation here is zero by idiom.", "Their allocation is zero by idiom.", [], None, "F", None),
("The idiom is the workspace (component-declared mutable scratch arriving as the `ws` bundle field) and snapshot pattern, plus immutable-value returns.", "The idiom is the workspace (component-declared mutable scratch arriving as the `ws` bundle field) and snapshot pattern, plus immutable-value returns.", [], None, "F", None),
("The rare exception has a documented tolerance, scoped per body by the seam's granularity so it never loosens the continuous assertions.", "The rare exception has a documented tolerance (D-116). The seam's granularity scopes the tolerance per body, so the tolerance never loosens the continuous assertions.", [], ["D-116"], "C", None),
("Logging is amortized-zero.", "Logging is amortized-zero.", [], None, "F", None),
("The log retains the published snapshot objects themselves, by reference, one slot per retained boundary and no copy (§11.2).", "The log retains the published snapshot objects themselves, by reference (§11.2, D-137). It keeps one slot per retained boundary and makes no copy.", ["§11.2"], ["§11.2", "D-137"], "C", None),
("`sizehint!` to the retention bound makes regrowth a non-event.", "`sizehint!` to the retention bound makes regrowth a non-event.", [], None, "F", None),
("The allocation claim is about the snapshot's fields, not about everything reachable from them.", "The allocation claim is about the snapshot's fields, not about everything reachable from them.", [], None, "F", None),
("A model carrying §4.4 field handles (immutable query objects consumers evaluate at their own arguments, such as heightmap terrain or wind grids) has a snapshot type with reference fields.", "A model carrying §4.4 field handles (immutable query objects consumers evaluate at their own arguments, such as heightmap terrain or wind grids) has a snapshot type with reference fields.", ["§4.4"], None, "F", None),
("Those fields ride as references to build-time-frozen data, with no copy and no per-boundary garbage, which is what the allocation claim asserts.", "Those fields ride as references to build-time-frozen data, with no copy and no per-boundary garbage. That is what the allocation claim asserts.", [], None, "F", None),
("What the claim does not assert is that the snapshot is `isbits`.", "The claim does not assert that the snapshot is `isbits`.", [], None, "F", None),
("The per-boundary allocation cost is zero either way, and the summarize-or-skip rule (§4.4) governs what such a field contributes on export.", "The per-boundary allocation cost is zero either way. The summarize-or-skip rule (§4.4) governs what such a field contributes on export.", ["§4.4"], None, "F", None),
("Event firings are not recorded.", "Event firings are not recorded.", [], None, "R", "R7"),
("The log holds boundary snapshots and the trace holds staged inputs (§11.2, §11.5).", "The log holds boundary snapshots and the trace holds staged inputs (§11.2, §11.5).", ["§11.2", "§11.5"], None, "R", "R7"),
("Neither carries a per-event record.", "Neither carries a per-event record.", [], None, "R", "R7"),
("Which events fired at which boundary is recovered by replay plus the published modes.", "Replay plus the published modes recovers which events fired at which boundary.", [], None, "R", "R7"),
("The honest remedy (§11.2) is to declare the mode field public and return it from `y_state` (D-252); a mode field so exposed is in every snapshot.", "The honest remedy is to declare the mode field public and return it from `y_state` (§11.2, D-252). A mode field so exposed is in every snapshot.", ["§11.2", "D-252"], None, "R", "R7"),
("An event-firing stream is a guarded addition (a capability the design admits but does not build).", "An event-firing stream is a guarded addition (a capability the design admits but does not build).", [], None, "R", "R7"),
("Tools where garbage is unavoidable.", "Two tools serve where garbage is unavoidable.", [], None, "X", None),
("Arena allocation (Bumper.jl-style) serves scoped temporaries.", "Arena allocation (Bumper.jl-style) serves scoped temporaries.", [], None, "F", None),
("A scheduled `GC.gc(false)` at frame boundaries moves collection out of the critical path.", "A scheduled `GC.gc(false)` at frame boundaries moves collection out of the critical path.", [], None, "F", None),
("Julia has no per-object freeing, so these are the honest levers.", "Julia has no per-object freeing, so these are the honest levers.", [], None, "F", None),
("---", "---", [], None, "X", None),
]
claims = []
for i, (o, n, c, nc, t, r) in enumerate(R, 1):
    d = {"id": f"D-{i:03d}", "old": o, "new": n, "where": "new", "cites": c}
    if nc is not None: d["newcites"] = nc
    d["tag"] = t
    if r: d["ruling"] = r
    claims.append(d)
added = [
 "Overlap between derivatives and outputs is the norm in physical and control models (§5.3).",
 "The section gives the four steps, then the prior art, then an idiom the design admits without framework support.",
 "(its in-place derivative function)",
 "The section states the invariant's scope, the policy's three tiers, what the log does not record, and the tools for garbage that cannot be avoided.",
 "The zero-allocation invariant is scoped to the stepping loop, and the stopped-sim services were always allocation-tolerant (D-135, §14.8).",
 "Publication is not a phase body (D-288, §9.7), and its one snapshot allocation per boundary sits with logging on the framework side, outside what the invariant claims is zero (§11.2).",
 "The policy has three tiers.",
]
json.dump({"claims": claims, "added": added}, open(os.path.join(H, "inventory.json"), "w"), indent=1, ensure_ascii=False)
