import json, os
HERE = os.path.dirname(os.path.abspath(__file__))

# (old, new, tag, newcites or None, ruling or None)
C = [
 (r"#### The IMU's leaves: integrate-and-difference", r"#### The leaves: integrate-and-difference", "R", None, "R6"),
 (r"The leaves carry the idiom that answers integrate-and-dump (§3.4).", r"The IMU's leaves carry the idiom that answers integrate-and-dump (§3.4).", "F", None, None),
 (r"Algebra can eliminate the reset, with no approximation.", r"Algebra can eliminate that reset, with no approximation.", "F", None, None),
 (r"Every interval-relative integral becomes a cumulative one.", r"Every interval-relative integral becomes a cumulative one (D-056).", "C", ["D-056"], None),
 (r"The sampler differences against the previous sample, held in its `s`.", r"The sampler differences against the previous sample, held in its `s`.", "F", None, None),
 (r"That is the textbook sampled-data latch, and it is the only new store, the memory the reset used to erase.", r"That is the textbook sampled-data latch. It is the only new store, the memory the reset used to erase.", "F", None, None),
 (r"- Raw increments (linear): $\Theta(t) = \int_{t_0}^{t} \omega^{c}_{ic} \, dt$, $\Upsilon(t) = \int_{t_0}^{t} f^{c} \, dt$, never reset; $\vartheta_c = \Theta(t_k) - \Theta(t_{k-1})$, $\upsilon_c = \Upsilon(t_k) - \Upsilon(t_{k-1})$.",
  r"- Raw increments (linear). The cumulative integrals $\Theta(t) = \int_{t_0}^{t} \omega^{c}_{ic} \, dt$ and $\Upsilon(t) = \int_{t_0}^{t} f^{c} \, dt$ are never reset. The increments are $\vartheta_c = \Theta(t_k) - \Theta(t_{k-1})$ and $\upsilon_c = \Upsilon(t_k) - \Upsilon(t_{k-1})$.", "F", None, None),
 (r"- Coning: cumulative $q(t) = q_{c_0 \to c(t)}$ with $\dot{q} = \tfrac{1}{2} \, q \otimes \omega^{c}_{ic}$ from identity at $t_0$.",
  r"- Coning. The cumulative attitude $q(t) = q_{c_0 \to c(t)}$ follows $\dot{q} = \tfrac{1}{2} \, q \otimes \omega^{c}_{ic}$ from identity at $t_0$.", "F", None, None),
 (r"The interval rotation is $\Delta q = q(t_{k-1})' \circ q(t_k)$, exact by right-invariance ($\Delta q$ satisfies the same ODE with the same body rate).",
  r"The interval rotation is $\Delta q = q(t_{k-1})' \circ q(t_k)$. It is exact by right-invariance, because $\Delta q$ satisfies the same ODE with the same body rate.", "F", None, None),
 (r"- Sculling: $\int_{t_{k-1}}^{t_k} R^{c_{k-1}}_{c} f^{c} \, dt = q(t_{k-1})' \, ( V(t_k) - V(t_{k-1}) )$ with $\dot{V} = q(t)(f^{c})$.",
  r"- Sculling. $\int_{t_{k-1}}^{t_k} R^{c_{k-1}}_{c} f^{c} \, dt = q(t_{k-1})' \, ( V(t_k) - V(t_{k-1}) )$ with $\dot{V} = q(t)(f^{c})$.", "F", None, None),
 (r"The derivation takes two steps.", r"The derivation takes two steps.", "F", None, None),
 (r"First, re-anchor the rotation through the fixed $c_0$ frame, $R^{c_{k-1}}_{c} = (R^{c_0}_{c_{k-1}})^{\mathsf{T}} R^{c_0}_{c}$, so that the $c_{k-1}$-dependent factor, constant over the interval, exits the integral.",
  r"First, re-anchor the rotation through the fixed $c_0$ frame, $R^{c_{k-1}}_{c} = (R^{c_0}_{c_{k-1}})^{\mathsf{T}} R^{c_0}_{c}$. The re-anchoring lets the $c_{k-1}$-dependent factor, constant over the interval, exit the integral.", "F", None, None),
 (r"What remains is the cumulative integrand.", r"What remains is the cumulative integrand.", "F", None, None),
 (r"Second, split its range at $t_{k-1}$, which gives the difference of the running store:", r"Second, split its range at $t_{k-1}$. That gives the difference of the running store:", "F", None, None),
 (r"$$\int_{t_{k-1}}^{t_k} R^{c_{k-1}}_{c} f^{c} \, dt = (R^{c_0}_{c_{k-1}})^{\mathsf{T}} \left( \int_{t_0}^{t_k} R^{c_0}_{c} f^{c} \, dt - \int_{t_0}^{t_{k-1}} R^{c_0}_{c} f^{c} \, dt \right) = q(t_{k-1})' \, \big( V(t_k) - V(t_{k-1}) \big)$$",
  r"$$\int_{t_{k-1}}^{t_k} R^{c_{k-1}}_{c} f^{c} \, dt = (R^{c_0}_{c_{k-1}})^{\mathsf{T}} \left( \int_{t_0}^{t_k} R^{c_0}_{c} f^{c} \, dt - \int_{t_0}^{t_{k-1}} R^{c_0}_{c} f^{c} \, dt \right) = q(t_{k-1})' \, \big( V(t_k) - V(t_{k-1}) \big)$$", "F", None, None),
 (r"In code, this is the sampler line `υ_c_sc = s.q'(u.V - s.V)`.", r"In code, the sculling result is the sampler line `υ_c_sc = s.q'(u.V - s.V)`.", "F", None, None),
 (r"The factor leaving the integral is the anchor change between two inertially-fixed frames.", r"The factor leaving the integral is the anchor change between two inertially-fixed frames.", "F", None, None),
 (r"It is constant because $t_{k-1}$ is in the past and latched.", r"It is constant because $t_{k-1}$ is in the past and latched.", "F", None, None),
 (r"The physical intra-interval rotation, the thing sculling corrections are about, stays inside the integrand via $q(t)$.",
  r"The physical intra-interval rotation stays inside the integrand via $q(t)$. That rotation is what sculling corrections are about.", "F", None, None),
 (r"Every RHS evaluation, RK stages included, applies the current cumulative attitude,",
  r"Every evaluation of the RHS (`x_deriv`, the continuous derivative function) applies the current cumulative attitude, RK stages included.", "F", None, None),
 (r"exactly as the direct formulation applies its current `q_c_cc`.",
  r"The direct formulation applies its current `q_c_cc`, its coning attitude increment, in exactly the same way.", "F", None, None),
 (r"#### Exactness condition, stated once", r"#### The exactness condition", "R", None, "R6"),
 (r"Interval-relative integrals factor into cumulative ones whenever the interval dependence enters through a left action by the interval-start value of a cumulatively-integrable quantity.",
  r"Interval-relative integrals factor into cumulative ones whenever the interval dependence enters through a left action by the interval-start value of a cumulatively-integrable quantity (D-056).", "C", ["D-056"], None),
 (r"That action is the identity for linear integrals, right-invariance for attitude increments, and constancy of the anchor change for sculling.",
  r"That action is the identity for linear integrals, right-invariance for attitude increments, and constancy of the anchor change for sculling.", "F", None, None),
 (r"Two provisos apply.", r"Two provisos apply.", "F", None, None),
 (r"First, the cumulative attitude must be integrated with the inertial rate,", r"First, the cumulative attitude must be integrated with the inertial rate (D-056).", "C", ["D-056"], None),
 (r"so that the anchor frame is inertially fixed and the pulled factor rigorously constant.", r"The anchor frame is then inertially fixed and the pulled factor rigorously constant.", "F", None, None),
 (r"Anchoring to a rotating reference breaks the factorization.", r"Anchoring to a rotating reference breaks the factorization.", "F", None, None),
 (r"Second, the equivalence survives discretization.", r"Second, the equivalence survives discretization (D-056).", "C", ["D-056"], None),
 (r"Quaternion kinematics is linear in `q`, every RK stage composes on the right, and left multiplication by the constant anchor commutes through,",
  r"Quaternion kinematics is linear in `q`, every RK stage composes on the right, and left multiplication by the constant anchor commutes through.", "F", None, None),
 (r"so the formulations agree to machine precision, not merely in the continuous-time limit.", r"So the formulations agree to machine precision, not merely in the continuous-time limit.", "F", None, None),
 (r"Never resetting has numerical consequences.", r"Never resetting has numerical consequences.", "F", None, None),
 (r"`q` stays unit under `x_projection`, which is better conditioned than the direct formulation's `normalization = false` plus reset.",
  r"`q` stays unit under `x_projection`, which is better conditioned than the direct formulation's `normalization = false` plus reset.", "F", None, None),
 (r"`Θ`, `Υ` and `V` grow linearly, so differencing loses relative precision.", r"`Θ`, `Υ` and `V` grow linearly, so differencing loses relative precision.", "F", None, None),
 (r"After an hour of flight that loss is of order $10^{-11}\ \mathrm{m/s}$ per sample against $10^{4}\ \mathrm{m/s}$ totals,",
  r"After an hour of flight that loss is of order $10^{-11}\ \mathrm{m/s}$ per sample against $10^{4}\ \mathrm{m/s}$ totals.", "F", None, None),
 (r"six-plus orders below any error model worth simulating.", r"That is six-plus orders below any error model worth simulating.", "F", None, None),
 (r"`struct IMUIntegrals <: AbstractComponent t_bc::FrameTransform end x_init(::IMUIntegrals) = (Θ = zeros(SVector{3}), q = SVector{4}(1.0, 0, 0, 0), Υ = zeros(SVector{3}), V = zeros(SVector{3})) u_types(::IMUIntegrals) = (q_eb = RQuat{Float64}, r_eb_e = SVector{3,Float64}, ω_eb_b = SVector{3,Float64}, a_ib_b = SVector{3,Float64}, α_ib_b = SVector{3,Float64}) y_types(::IMUIntegrals) = (Θ = SVector{3,Float64}, q = SVector{4,Float64}, # exposed state (§5.3) Υ = SVector{3,Float64}, V = SVector{3,Float64}, ω_ic_c = SVector{3,Float64}, f_c_c = SVector{3,Float64}) # instantaneous truth",
  r"struct IMUIntegrals <: AbstractComponent t_bc::FrameTransform end x_init(::IMUIntegrals) = (Θ = zeros(SVector{3}), q = SVector{4}(1.0, 0, 0, 0), Υ = zeros(SVector{3}), V = zeros(SVector{3})) u_types(::IMUIntegrals) = (q_eb = RQuat{Float64}, r_eb_e = SVector{3,Float64}, ω_eb_b = SVector{3,Float64}, a_ib_b = SVector{3,Float64}, α_ib_b = SVector{3,Float64}) y_types(::IMUIntegrals) = (Θ = SVector{3,Float64}, q = SVector{4,Float64}, # exposed state (§5.3) Υ = SVector{3,Float64}, V = SVector{3,Float64}, ω_ic_c = SVector{3,Float64}, f_c_c = SVector{3,Float64}) # instantaneous truth", "F", None, None),
 (r"# the four integrals are state, so stage 1 returns them (§5.3) y_state(::IMUIntegrals, (; x)) = (; x.Θ, x.q, x.Υ, x.V)",
  r"# the four integrals are state, so stage 1 returns them (§5.3) y_state(::IMUIntegrals, (; x)) = (; x.Θ, x.q, x.Υ, x.V)", "F", None, None),
 (r"# y_direct: strapdown kinematics (lever arm, gravity, Earth rate) → (; ω_ic_c, f_c_c) function x_deriv(imu::IMUIntegrals, (; x, y)) q = RQuat(x.q, normalization = false) # §7.1's explicit cast (Θ = y.ω_ic_c, q = SVector{4}(Attitude.dt(q, y.ω_ic_c)), Υ = y.f_c_c, V = q(y.f_c_c)) end x_projection(imu::IMUIntegrals, x) = (; x..., q = normalize(x.q)) # SVector normalize",
  r"# y_direct: strapdown kinematics (lever arm, gravity, Earth rate) → (; ω_ic_c, f_c_c) function x_deriv(imu::IMUIntegrals, (; x, y)) q = RQuat(x.q, normalization = false) # §7.1's explicit cast (Θ = y.ω_ic_c, q = SVector{4}(Attitude.dt(q, y.ω_ic_c)), Υ = y.f_c_c, V = q(y.f_c_c)) end x_projection(imu::IMUIntegrals, x) = (; x..., q = normalize(x.q)) # SVector normalize", "R", None, "R7"),
 (r"struct IMUSampler <: AbstractComponent end s_init(::IMUSampler) = (Θ = zeros(SVector{3}), q = SVector{4}(1.0, 0, 0, 0), Υ = zeros(SVector{3}), V = zeros(SVector{3})) u_types(::IMUSampler) = (Θ = SVector{3,Float64}, q = SVector{4,Float64}, # discrete class: plain Υ = SVector{3,Float64}, V = SVector{3,Float64}) # form, bound check only y_types(::IMUSampler) = (sample = IMUSample,) # discrete class: cells pin (frozen-exact)",
  r"struct IMUSampler <: AbstractComponent end s_init(::IMUSampler) = (Θ = zeros(SVector{3}), q = SVector{4}(1.0, 0, 0, 0), Υ = zeros(SVector{3}), V = zeros(SVector{3})) u_types(::IMUSampler) = (Θ = SVector{3,Float64}, q = SVector{4,Float64}, # discrete tier: bound check only Υ = SVector{3,Float64}, V = SVector{3,Float64}) y_types(::IMUSampler) = (sample = IMUSample,) # discrete tier: cells pin (frozen-exact)", "R", None, "R7"),
 (r"function y_direct(smp::IMUSampler, (; s, u, Δt)) q_s = RQuat(s.q, normalization = false); q_u = RQuat(u.q, normalization = false) ϑ_c = u.Θ - s.Θ; υ_c = u.Υ - s.Υ Δq = q_s' ∘ q_u # interval rotation, exact υ_c_sc = q_s'(u.V - s.V) # constant anchor change pulled out (; sample = IMUSample(; ω̄_ic_c = ϑ_c / Δt, f̄_c_c = υ_c / Δt, ϑ_c, ϑ_c_cc = RVec(Δq)[:], υ_c, υ_c_sc)) end s_update(smp::IMUSampler, (; u)) = (Θ = u.Θ, q = u.q, Υ = u.Υ, V = u.V) # the latch",
  r"function y_direct(smp::IMUSampler, (; s, u, Δt)) q_s = RQuat(s.q, normalization = false); q_u = RQuat(u.q, normalization = false) ϑ_c = u.Θ - s.Θ; υ_c = u.Υ - s.Υ Δq = q_s' ∘ q_u # interval rotation, exact υ_c_sc = q_s'(u.V - s.V) # constant anchor change pulled out (; sample = IMUSample(; ω̄_ic_c = ϑ_c / Δt, f̄_c_c = υ_c / Δt, ϑ_c, ϑ_c_cc = RVec(Δq)[:], υ_c, υ_c_sc)) end s_update(smp::IMUSampler, (; u)) = (Θ = u.Θ, q = u.q, Υ = u.Υ, V = u.V) # the latch", "F", None, None),
 (r"The `IMU` assembly wires the four integral ports across,", r"The `IMU` assembly wires the four integral ports across.", "F", None, None),
 (r"holds the error model as a discrete sibling consuming `sample`,", r"It holds the error model as a discrete sibling consuming `sample`,", "F", None, None),
 (r"and leaves the sampler at `K = 1` in its own scope.", r"and it leaves the sampler at `K = 1` (its `sample_times` entry is `Relative(1)`) in its own scope.", "F", None, None),
 (r"The parent sets the IMU's rate (§8.7).", r"The parent sets the IMU's rate (§8.7).", "F", None, None),
 (r"`Δt` in the stage bundle (the NamedTuple of zero-copy views a component function receives) is the §10.5 single source of truth,",
  r"`Δt` in the stage bundle (the NamedTuple of zero-copy views a component function receives) is the single source of truth (§10.5).", "F", None, None),
 (r"put there for exactly this kind of discretized law.", r"It is there for exactly this kind of discretized law.", "F", None, None),
 (r"Initialization consistency also holds.", r"Initialization is consistent too.", "F", None, None),
 (r"The sampler's `s` must equal the initial integrals, or the `t₀` sample is wrong.", r"The sampler's `s` must equal the initial integrals, or the `t₀` sample is wrong.", "F", None, None),
 (r"That holds by default at zeros/identity, and boundary zero discharges the rest.", r"That holds by default at zeros/identity, and boundary zero discharges the rest.", "F", None, None),
 (r"Its due `s_update` latches `s ← integrals(t₀)` for every subsequent sample,", r"There the sampler's due `s_update` (one scheduled to run at this boundary) latches `s ← integrals(t₀)` for every subsequent sample (D-067).", "C", ["D-067"], None),
 (r"so only the `t₀` sample itself depends on the authored `s`.", r"So only the `t₀` sample itself depends on the authored `s`.", "F", None, None),
 (r"That dependence is a condition-authoring obligation under trim (§14.5).", r"That dependence is an obligation on the author of the condition (the datum that sets a build to a state) under trim (§14.5).", "F", None, None),
 (r"#### Why `u.V` is fresh: the line that would silently zero", r"#### Freshness at the sample", "R", None, "R6"),
 (r"The sculling line is correct only because a due tick samples the completed boundary.", r"The sculling line is correct only because a due tick samples the completed boundary.", "F", None, None),
 (r"If `u.V` still held the previous boundary's decode, it would equal `s.V` exactly, since that is the value `s_update` latched,",
  r"If `u.V` still held the previous boundary's decode, it would equal `s.V` exactly, since that is the value `s_update` latched.", "F", None, None),
 (r"and sculling would vanish without an error anywhere.", r"Sculling would then vanish without an error anywhere.", "F", None, None),
 (r"The guarantee is the §10.6 macro-sequence, not a scheduling accident.", r"The guarantee is the boundary macro-sequence of §10.6, not a scheduling accident.", "F", None, None),
 (r"The sequence is integrate, project, sweep,", r"The sequence is integrate, project, sweep (one pass through the execution order).", "F", None, None),
 (r"with the due sampler's stages gated into that sweep (§10.5)", r"The due sampler's stages are gated into that sweep (§10.5).", "F", None, None),
 (r"and the integrals arriving at stage-1 position, returned by `y_state` (§5.3).", r"The integrals arrive at stage-1 position, returned by `y_state` (§5.3).", "F", None, None),
 (r"They arrive before any stage-2 function runs, regardless of topological placement.", r"They arrive before any stage-2 function runs, regardless of topological placement.", "F", None, None),
 (r"The rest of the timeline closes consistently.", r"The rest of the timeline closes consistently.", "F", None, None),
 (r"The sampler's `y_direct` decodes `s`, the `t_{k-1}` latch, before `s_update` runs,", r"The sampler's `y_direct` decodes `s`, the `t_{k-1}` latch, before `s_update` runs.", "F", None, None),
 (r"which is the `z⁻¹` semantics.", r"That is the `z⁻¹` semantics, the one-sample delay of sampled-data control.", "F", None, None),
 (r"After event quiescence, `s_update` latches the `t_k` values for the next tick.", r"After event quiescence (the point where a round of handlers fires nothing), `s_update` latches the `t_k` values for the next tick.", "F", None, None),
 (r"Same-boundary events re-run the gated stages in their re-sweeps,", r"Same-boundary events re-run the gated stages in their re-sweeps.", "F", None, None),
 (r"so `s_update` and external readers see the settled boundary.", r"So `s_update` and external readers see the settled boundary.", "F", None, None),
 (r"#### Sampling at `t_k` is a taught contract", r"#### The boundary-sampling contract", "R", None, "R6"),
 (r'The clean implementation leans on the author knowing that "sampling at `t_k`" means post-integration, post-projection, stage-1-fresh state.',
  r'The clean implementation leans on the author knowing that "sampling at `t_k`" means post-integration, post-projection, stage-1-fresh state.', "F", None, None),
 (r"That knowledge must be part of the framework's taught contract, not internal lore,", r"That knowledge must be part of the framework's taught contract, not internal lore (D-056).", "C", ["D-056"], None),
 (r"with the §10.5 and §10.6 semantics stated in component-author documentation (Appendix A) and this IMU as the worked example.",
  r"The semantics of §10.5 and §10.6 must be stated in component-author documentation (Appendix A), with this IMU as the worked example.", "F", None, None),
 (r"The failure mode of not knowing it is instructive.", r"The failure mode of not knowing it is instructive.", "F", None, None),
 (r"An author who distrusts the sweep order adds a defensive one-tick delay or re-derives the integrals in the sampler,", r"An author who distrusts the sweep order adds a defensive one-tick delay or re-derives the integrals in the sampler.", "F", None, None),
 (r"silently degrading the model.", r"Either one silently degrades the model.", "F", None, None),
 (r"When the coupling is genuinely two-way, the latch becomes a wire back.", r"When the coupling is genuinely two-way, the latch becomes a wire back (D-056).", "C", ["D-056"], None),
 (r"The IMU's coupling is one-directional, from integrals to sampler.", r"The IMU's coupling is one-directional, from integrals to sampler.", "F", None, None),
 (r"Suppose the flow itself needed the interval-relative value, say for integrator saturation within the sampling interval.", r"Suppose the flow itself needed the interval-relative value, say for integrator saturation within the sampling interval.", "F", None, None),
 (r"Then the sampler publishes the sample-instant values from its feedthrough stage,", r"Then the sampler publishes the sample-instant values from its feedthrough stage (the stage with an instantaneous input-to-output dependence).", "F", None, None),
 (r"and the continuous `x_deriv` computes `x − u.latch`.", r"The continuous `x_deriv` computes `x − u.latch`.", "F", None, None),
 (r"The feedthrough stage is the right one because `y_direct` reads `u`,", r"The feedthrough stage is the right one because `y_direct` reads `u`.", "F", None, None),
 (r"so the latch port carries the current tick's values, ZOH until the next.", r"The latch port therefore carries the current tick's values, held by zero-order hold (ZOH) until the next.", "F", None, None),
 (r"An `y_state`-published latch would be one period stale.", r"A `y_state`-published latch would be one period stale.", "F", None, None),
 (r"Both cross-wires consume the other side's ports, and the feedthrough graph stays acyclic.", r"Both cross-wires consume the other side's ports, and the feedthrough graph stays acyclic.", "F", None, None),
 (r"The integrals' stage 1 feeds the sampler's `y_direct`, and the sampler's `y_direct` feeds the integrals' `x_deriv` edge (§5.4).",
  r"The integrals' stage 1 feeds the sampler's `y_direct`, and the sampler's `y_direct` feeds the integrals' `x_deriv` edge (§5.4).", "F", None, None),
 (r'The "reset" becomes a visible tier-crossing feedback loop, which is what it always was, physically.', r'The "reset" becomes a visible tier-crossing feedback loop. That is what it always was, physically.', "F", None, None),
]

ADDED = [
 r"#### The leaves in code",
 r"In integrate-and-dump, the IMU's direct formulation integrates over each sample interval and zeroes its integrals at every sample.",
 r"(`x_deriv`, the continuous derivative function)",
 r"its coning attitude increment,",
 r"A few names in the code below need an introduction. `RQuat` is the domain wrapper an attitude `SVector{4}` is cast to where rotation semantics are wanted (§7.1). `Attitude.dt` gives the coning bullet's quaternion derivative, and `RVec` turns the interval rotation `Δq` into the vector the sample carries. `IMUSample` is the sampler's output struct. `FrameTransform` is one of the payload types §7.2 lists as walked.",
 r"(its `sample_times` entry is `Relative(1)`)",
 r"Boundary zero is the initialization boundary (a published consistency point), run at `t₀`.",
 r"(one scheduled to run at this boundary)",
 r"(the datum that sets a build to a state)",
 r"A tick is an instant at which a discrete component's stages and update run.",
 r"(one pass through the execution order)",
 r"the one-sample delay of sampled-data control",
 r"(the point where a round of handlers fires nothing)",
 r"Projection is the `x_projection` hook, run after integration.",
 r"(the stage with an instantaneous input-to-output dependence)",
 r"held by zero-order hold (ZOH)",
]

import re
CITE = re.compile(r'§\d+(?:\.\d+)?|D-\d{3}|Appendix [A-D]')
claims = []
for i, (o, n, tag, nc, rl) in enumerate(C, 1):
    oc = list(dict.fromkeys(CITE.findall(o)))
    d = {"id": f"E2-{i:03d}", "old": o, "new": n, "where": "new", "cites": oc}
    if nc is not None:
        d["newcites"] = sorted(set(oc) | set(nc))
    d["tag"] = tag
    if rl: d["ruling"] = rl
    claims.append(d)
json.dump({"claims": claims, "added": ADDED}, open(os.path.join(HERE, "inventory.json"), "w"), ensure_ascii=False, indent=1)
