# The suite's `import Redstone:` list — the one place a framework name the tests
# call or extend is admitted (implementation.md's authoring caveat). Shared with
# `repl.jl`: `include` evaluates in the including module, so the same file
# imports into `RedstoneTests` and into `Main`.
import Redstone: ASSEMBLY, Absolute, AbstractBinding, AbstractComponent,
    AbstractDevice, AlgebraicCycle, AlreadyAttached, Anchor, ArgumentInvalid,
    AbstractAtRoot, AttachUnknownFace, Authored, BUILD_WARNINGS, BindingContractMismatch,
    Build, BundleFieldError,
    CONTINUOUS, ChatteringBudget, Checkpoint, CheckpointMidFrame,
    CheckpointMismatch, ChildNameCollision,
    ClaimConflict, ClaimedFaceEntry, Class, ClassMixed, ClassUnreadable,
    Combined, ComponentEntry, ComponentEvents, ComponentOutputs, ConditionNodeMisuse,
    ConditionPlan, ConditionResolution,
    ConditionShapeDrift, ConformanceFailure, ContainerMixed, ContainerNested,
    Control, ControlRequestedStop, CursorFrame, DIAG_RING, DISCRETE, DeadStage,
    DeclarationOnWrongTier, DeclarationShadowed, DeclaredNotProduced,
    Deployment, DeploymentInvalid, DeviceContractMismatch, DeviceCrash, DeviceHandle,
    DebtReanchor, DeviceJoinTimeout, DiagCell, Diagnostic, DiagnosticError,
    DuplicateConditionLeaf, EMPTY_DIAG, EmptyFaceSelection, EmptyGreedyClaim,
    EndTimeReached, EntryTypeMismatch, EventHalfMissing, Events,
    Executor, FaceDirectionConflict, FaceNameCollision, FaceNameIllegal,
    FiringBudget, Fragment, FrameworkStatus, Gated, GetDeriv, GridEntry, GridReport, GridUtilization,
    GuardForm,
    HandlerReturnKey, Heun, Hz, IllegalPortType, IllegalStateLeaf, IllegalStoreField, InternalInvariant,
    KINDS, KindCounts, LEGAL_BUNDLE, LINEARIZE_WIDTH, Linearization, LinearizeDual,
    LinearizeTag, LoopError, MalformedDatum, Marker, MissingInit,
    MissingProbeValue, ModelRequestedStop,
    NonfiniteState, NotAttached, OutOfClaimEntry, Outputs, PRIMITIVE, Pacer, PacerStatus,
    PathResolution,
    Period, Pinned, ProbeDual, ProbeTag, ProducedByTwoStages, RK4,
    RatesViolation, ReadBindingUnresolved,
    ReadSetMisuse, Reader, Reads, Relative, ReplayDiscardedStaging, ReplayFeed,
    ReplaySchemaMismatch, ReplayUnknownFace,
    RootInputTypeConflict, Run, STATUS_MAXLOG, Schedule, ScheduleEntry, ScopeEntry, Scoped, ServiceLifecycle,
    Simulation, Snapshot,
    SpecializedPlan, StageEntry, StateEvent, StatelessWithoutOutputs, StepError, StopFaceInvalid,
    StopPolicy, StoreBundle,
    StoreNotNamedTuple, StoreWithoutUpdate, Structure, StructureDraft, TableBinding, TapResolution,
    Taps, TerminationRecord, Tier,
    ThreadBudget, TierUnreadable, Trace, TraceBatch, Tracer,
    TransparentContainerUnknown,
    TrimCommitChecks, TrimCommitEvents, TrimCommitResiduals, TrimProblem, TrimProblemInvalid,
    TrimTag, TwoProducers, UnboundedRun, UnconnectedInput, UndeclaredReturnField, Undecidable,
    UninitializedInputs, UnknownFaceSelection, UnknownPort, UserCodeFraming,
    WALK_FACES, WalkingFaceAtFrozenEntry, WireTypeMismatch, WriterStatus,
    _accepts, _accepts_wire, _bump, _check_handler, _check_root_faces, _check_transparent,
    _children, _container_fields, _contract, _element_keys, _elements, _is_container,
    _declares, _declares_workspace, _holds_marker, _kind, _leaf_values, _cell_key, _compile_feed, _compile_reads, _gates, _heartbeat,
    _fire!, _frame_at, _frames_to, _guards!, _mflatten_expr, _mreconstruct_expr, _ports, _projects!,
    report_cell!, report_thread_budget!, _saturated, _take!, _total, _typename, _walk!, _walk_at,
    _walked_children, _warn!, _workspace, activation, anchor!, apply!, at, at_component, attach!,
    binding, boundary!,
    build, bundle_names, capture_stores, check_state_leaves, check_store_form, check_stores,
    checkpoint, inner_wires, children, claims,
    classify, classify_bundle_field, classify_tier, closed, combine, compile, compile_plan,
    condition, declarations, declarations_found, declared_at,
    detach!, diagnostic, diagnostics, drain!, evaluate!, event_bundle_names, flatten!, flatten_tree!,
    foreign_declarations, fragment, frame!, gather, gather_cell, gather_reads, gather_snapshot, get_deriv, get_face,
    get_input, get_output, get_state, has_stage, incumbent_status, index_of, init!, integrate!,
    invoke_declaration, invoke_probed,
    input_wires, input_faces, input_passthrough, linearize,
    is_greedy, is_input, is_output, kinds,
    latest, leaf_declarations, leaf_eltypes, leaf_names, leaf_types, lifecycle, live!, logged,
    logline, loop, m_init, map_input, map_output, margin, margin!, message, mode, modes,
    mutable_position, nleaves, offtick_boundary!, orphaned,
    output_wires, output_faces, output_passthrough,
    override, pace, pace!, path, pause!, paused, peek, pending, period, phase_bodies, port,
    port_views, probe_value, publish!, reads,
    reconstruct, replay!, report!, resolve, resolve_condition, resolve_dest, restore!,
    resolve_source, resolve_terminal, resume!, retype, retype_entry, retype_value, run!, running,
    s_init, s_update, sample_times,
    scatter_cell!, severity, shutdown!, solve, stage!, stale, state,
    state_events, step!, taps,
    stop!, termination, trace, transparent_container, trim!, u_types, unblock!,
    wait_deadline!, wait_next_snapshot, warnings, ws_init,
    x_deriv, x_init, x_projection, y_direct, y_state, y_types
import Redstone.Blocks: Group, Junction, SumJunction, Or, And,
    Constant, Freeze, UnitDelay
