# The suite's `import Cadence:` list — the one place a framework name the tests
# call or extend is admitted (implementation.md's authoring caveat). Shared with
# `repl.jl`: `include` evaluates in the including module, so the same file
# imports into `CadenceTests` and into `Main`.
import Cadence: ASSEMBLY, Absolute, AbstractBinding, AbstractComponent,
    AbstractDevice, AlgebraicCycle, AlreadyAttached, ArgumentInvalid,
    AttachUnknownFace, Authored, BindingContractMismatch, Build,
    CONTINUOUS, CallerTaskConflict, ChatteringBudget, ChildNameCollision,
    ClaimConflict, ClaimedFaceEntry, Class, ClassMixed, ClassUnreadable,
    Combined, ConditionNode, ConditionNodeMisuse, ConditionResolution,
    ConditionShapeDrift, ConformanceFailure, ContainerMixed,
    ControlRequestedStop, CursorFrame, DIAG_RING, DISCRETE,
    DeclarationOnWrongTier, DeclaredNotProduced, DeploymentInvalid,
    DeviceContractMismatch, DeviceCrash, DeviceHandle, DeviceJoinTimeout,
    DiagCell, Diagnostic, DiagnosticError, DuplicateConditionLeaf, EMPTY_DIAG,
    EmptyGreedyClaim, EndTimeReached, EntryTypeMismatch, EventHalfMissing,
    Executor, FaceDirectionConflict, FaceNameCollision, FaceNameIllegal,
    FiringBudget, Fragment, Gated, GetDeriv, Group, GuardForm,
    HandlerReturnKey, Heun, Hz, IllegalPortType, InternalInvariant,
    KindCounts, LoopError, MalformedDatum, MissingInit, ModelRequestedStop,
    NonfiniteState, NotAttached, OutOfClaimEntry, PRIMITIVE, PathResolution,
    Period, ProducedByTwoStages, RK4, RatesViolation, ReadBindingUnresolved,
    ReadSetMisuse, Relative, ReplayDiscardedStaging, ReplayFeed,
    ReplayHeaderMismatch, ReplaySchemaMismatch, ReplayUnknownFace,
    RootInputTypeConflict, Scoped, ServiceLifecycle, Simulation, Snapshot,
    SpecializedPlan, StateEvent, StepError, StopFaceInvalid, StoreBundle,
    StoreWithoutUpdate, TableBinding, TapResolution, TerminationRecord, Tier,
    TierUnreadable, Trace, TraceBatch, TransparentContainerUnknown,
    TrimCommitEvents, TrimCommitResiduals, TrimProblem, TrimProblemInvalid,
    TrimTag, TwoProducers, UnconnectedInput, UndeclaredReturnField,
    UninitializedInputs, UnknownFaceSelection, UnknownPort, WireTypeMismatch,
    _bump, _cell_key, _compile_feed, _compile_reads, _heartbeat,
    _mflatten_expr, _mreconstruct_expr, _report!, _reschema, _saturated,
    _take!, _total, activation, apply!, at, attach!, binding, boundary!,
    build, bundle_names, capture, child_connections, children, claims,
    classify, classify_tier, combine, compile, compile_plan, declarations,
    detach!, diagnostic, diagnostics, drain!, evaluate!, flatten!, fragment,
    frame!, gather, get_deriv, get_face, get_input, get_output, get_state,
    index_of, init!, init_m, init_s, init_workspace, init_x,
    input_connections, input_faces, input_passthrough, input_types,
    is_greedy, is_input, is_output, kinds,
    latest, leaf_eltypes, leaf_names, leaf_types, lifecycle, live!, logged,
    logline, loop, map_input, map_output, message, mode, modes,
    needs_calling_task, nleaves, offtick_boundary!, output_connections,
    output_direct, output_faces, output_passthrough, output_state,
    output_types, override, path, period, phase_bodies, port, publish!, reads,
    reconstruct, replay!, report!, resolve, resolve_condition,
    resolve_terminal, retype, retype_value, run!, running, sample_times,
    scatter!, severity, shutdown!, solve, stage!, stale, state,
    state_derivative, state_events, state_projection, state_update, step!,
    stop!, termination, trace, transparent_container, trim!, unblock!,
    wait_next_snapshot
