# The suite's `import Cadence:` list — the one place a framework name the tests
# call or extend is admitted (implementation.md's authoring caveat). Shared with
# `repl.jl`: `include` evaluates in the including module, so the same file
# imports into `CadenceTests` and into `Main`.
import Cadence: ASSEMBLY, Absolute, AbstractBinding, AbstractComponent,
    AbstractDevice, AlgebraicCycle, AlreadyAttached, Anchor, ArgumentInvalid,
    AbstractAtRoot, AttachUnknownFace, Authored, BUILD_WARNINGS, BindingContractMismatch,
    Build, BundleFieldError,
    CONTINUOUS, CallerTaskConflict, ChatteringBudget, ChildNameCollision,
    ClaimConflict, ClaimedFaceEntry, Class, ClassMixed, ClassUnreadable,
    Combined, ComponentEntry, ComponentEvents, ComponentOutputs, ConditionNode, ConditionNodeMisuse,
    ConditionPlan, ConditionResolution,
    ConditionShapeDrift, ConformanceFailure, ContainerMixed, ContainerNested,
    ControlRequestedStop, CursorFrame, DIAG_RING, DISCRETE, DeadStage,
    DeclarationOnWrongTier, DeclarationShadowed, DeclaredNotProduced,
    Deployment, DeploymentInvalid, DeviceContractMismatch, DeviceCrash, DeviceHandle,
    DeviceJoinTimeout, DiagCell, Diagnostic, DiagnosticError,
    DuplicateConditionLeaf, EMPTY_DIAG, EmptyFaceSelection, EmptyGreedyClaim,
    EndTimeReached, EntryTypeMismatch, EventHalfMissing, Events,
    Executor, FaceDirectionConflict, FaceNameCollision, FaceNameIllegal,
    FiringBudget, Fragment, Gated, GetDeriv, GridEntry, GridReport, GridUtilization,
    Group, GuardForm,
    HandlerReturnKey, Heun, Hz, IllegalPortType, IllegalStateLeaf, IllegalStoreField, InternalInvariant,
    KindCounts, LEGAL_BUNDLE, LoopError, MalformedDatum, Marker, MissingInit,
    MissingProbeValue, ModelRequestedStop,
    NonfiniteState, NotAttached, OutOfClaimEntry, Outputs, PRIMITIVE, PathResolution,
    Period, ProbeDual, ProbeTag, ProducedByTwoStages, RK4,
    RatesViolation, ReadBindingUnresolved,
    ReadSetMisuse, Reader, Relative, ReplayDiscardedStaging, ReplayFeed,
    ReplayHeaderMismatch, ReplaySchemaMismatch, ReplayUnknownFace,
    RootInputTypeConflict, Run, Schedule, ScheduleEntry, ScopeEntry, Scoped, ServiceLifecycle,
    Simulation, Snapshot,
    SpecializedPlan, StageEntry, StateEvent, StepError, StopFaceInvalid, StopPolicy, StoreBundle,
    StoreNotNamedTuple, StoreWithoutUpdate, Structure, TableBinding, TapResolution,
    TerminationRecord, Tier,
    TierSignatureMismatch, TierUnreadable, Trace, TraceBatch, TraceHeader, Tracer,
    TransparentContainerUnknown,
    TrimCommitChecks, TrimCommitEvents, TrimCommitResiduals, TrimProblem, TrimProblemInvalid,
    TrimTag, TwoProducers, UnboundedRun, UnconnectedInput, UndeclaredReturnField, Undecidable,
    UninitializedInputs, UnknownFaceSelection, UnknownPort, UserCodeFraming,
    WALK_FACES, WalkingFaceAtFrozenEntry, WireTypeMismatch,
    _accepts, _accepts_wire, _bump, _leaf_values, _cell_key, _compile_feed, _compile_reads, _gates, _heartbeat,
    _mflatten_expr, _mreconstruct_expr, _ports, report_cell!, _saturated,
    _take!, _total, _typename, _warn!, activation, apply!, at, attach!, binding, boundary!,
    build, bundle_names, capture, capture_stores, child_connections, children, claims,
    classify, classify_bundle_field, classify_tier, closed, combine, compile, compile_plan,
    condition, declarations,
    detach!, diagnostic, diagnostics, drain!, evaluate!, flatten!,
    foreign_declarations, fragment, frame!, gather, gather_cell, gather_reads, get_deriv, get_face,
    get_input, get_output, get_state, index_of, init!, init_m, init_s,
    init_workspace, init_x,
    input_connections, input_faces, input_passthrough, input_types,
    is_greedy, is_input, is_output, kinds,
    latest, leaf_eltypes, leaf_names, leaf_types, lifecycle, live!, logged,
    logline, loop, map_input, map_output, message, mode, modes,
    mutable_position, needs_calling_task, nleaves, offtick_boundary!, output_connections,
    output_direct, output_faces, output_passthrough, output_state,
    output_types, override, path, period, phase_bodies, port, probe_value, publish!, reads,
    reconstruct, replay!, report!, resolve, resolve_condition,
    resolve_terminal, retype, retype_value, run!, running, sample_times,
    scatter_cell!, severity, shutdown!, solve, stage!, stale, state,
    state_derivative, state_events, state_projection, state_update, step!,
    stop!, termination, trace, transparent_container, trim!, unblock!,
    wait_next_snapshot, warnings
