"""Scratch: builds inventory.json for unit C2. Each row: (old, new, tag, extra)."""
import json, re, os
H = os.path.dirname(os.path.abspath(__file__))
CITE = re.compile(r'§\d+(?:\.\d+)?|D-\d{3}|Appendix [A-D]')
S = "(the per-component `(D, Φ, Δt)` table the `Deployment` carries)"
rows = [
 ("Coincidence and stagger are modeling choices with observable consequences", "Coincidence and stagger are modeling choices with observable consequences.", "M"),
 ("Coincident ticks give a consumer fresh same-instant reads via topological order. That is the idealized synchronous-sampling picture.", None, "M"),
 ("A phase stagger makes the same reads pipelined and deterministically aged instead. That is the structural expression of an acquisition pipeline's latency, obtained with no delay blocks.", None, "M"),
 ("A stagger is also a load-shaping tool under real-time pacing (waits inserted between completed frames, never altering the boundary sequence).", None, "M"),
 ("Staggered stacks never share a frame, so worst-case frame cost is a `max` rather than a sum (§10.7).", None, "M"),
 ("Both patterns are worked in `sample_time_proposal.md`, together with how silently an offset edit rewires a coincidence structure.", None, "M"),
 ("The schedule " + S, "The deployment's `Schedule` " + S, "M"),
 ("and its hyperperiod chart (§9.2) are how a user audits which pattern a model actually has.", "The `Schedule` and its hyperperiod chart (§9.2) are how a user audits which pattern a model actually has.", "M"),
 ("Declaring a sample time: two forms, one concept", "The two forms thus declare one concept, a sample time, in different units.", "X"),
 ("Rule. A discrete component or sub-assembly is scheduled by a `sample_times` entry in its enclosing assembly (§8.7).", "A discrete component or sub-assembly is scheduled by a `sample_times` entry in its enclosing assembly (§8.7).", "F"),
 ("The entry declares one (period, phase) pair in one of two unit systems, and the wrapper type names the unit system.", "The entry declares one (period, phase) pair in one of two unit systems, and the wrapper type names the unit system (D-185).", "C"),
 ("| entry | unit system | tick instants | constraints | |---|---|---|---| | `Relative(K, Φ = 0)` | scope ticks | every `K`-th tick of the enclosing scope, starting from its `Φ`-th | `K ≥ 1`, `0 ≤ Φ < K` | | `Absolute(q, τ = 0)` | seconds | `t = τ + k·T`, with `T = period(q)` | `T > 0`, `0 ≤ τ < T` |", None, "F"),
 ("`K = 1` therefore admits no stagger.", "`K = 1` therefore admits no stagger (D-185).", "C"),
 ("Two same-rate siblings are staggered one level down instead. Declare the scope at twice their rate, then give them `Relative(2, 0)` and `Relative(2, 1)`.", None, "F"),
 ("`q` is a quantity value, `Period(1//50)` or `Hz(50)`. The two are a spelling choice, normalized to the rational period at construction.", None, "F"),
 ("Every period and offset is an exact `Rational{Int}`, because grid derivation is GCD arithmetic and ill-defined over floats.", None, "F"),
 ("A float argument throws the teaching error naming the exact spelling (`Period(1//50)`, or `Hz(1//2)` for 0.5 Hz).", None, "F"),
 ("The wrappers are the whole vocabulary.", "The wrappers are the whole vocabulary (D-185).", "C"),
 ("A bare integer or bare quantity is a declaration error.", None, "F"),
 ("An unlisted discrete child defaults to `Relative(1)`, so the common case costs nothing and a multiplied or anchored child always appears explicitly.", "An unlisted discrete child defaults to `Relative(1)`. The common case therefore costs nothing, and a multiplied or anchored child (one declared `Absolute`, below) always appears explicitly.", "F"),
 ("Validation belongs to the structure step, the build's declaration-reading step, and is collected with path attribution (§9.1, §13.1).", "Validation belongs to the structure step (the build's declaration-reading step), which collects it with path attribution (§9.1, §13.1, D-185).", "C"),
 ("It covers `K ≥ 1`, `0 ≤ Φ < K`, `T > 0`, `0 ≤ τ < T`, and keys naming discrete or scope children.", None, "F"),
 ("The constructors themselves are plain data carriers, with no checks of their own (D-185).", "The constructors themselves are plain data carriers, with no checks of their own.", "C"),
 ("The relative form composes affinely and stays on the scope grid", "keep a relative entry on the scope grid", "X"),
 ("Rule. Multipliers compose multiplicatively and phases affinely down the tree.", "Multipliers compose multiplicatively and phases affinely down the tree (D-019, D-185).", "C"),
 ("Under a scope compiled to divisor and phase `(D_s, Φ_s)` in base ticks, a child declared `Relative(K, φ)` compiles to `D = K·D_s` and `Φ = Φ_s + φ·D_s`.", None, "F"),
 ("Composition preserves the canonical residue `0 ≤ Φ < D`.", None, "F"),
 ("`sample_time_proposal.md` carries the one-line induction.", "`sample_time_proposal.md` (the declaration design's worked companion) carries the one-line induction.", "F"),
 ("All scoping therefore compiles away at build to one `(D, Φ)` pair per discrete component,", "All scoping therefore compiles away at build to one `(D, Φ)` pair per discrete component.", "F"),
 ("and the boundary sweep gates on that pair with the `(tick − Φ) % D == 0` test above.", "The boundary sweep gates on that pair with the `(tick − Φ) % D == 0` test above.", "F"),
 ("The lattice stays static, and the interior sweep still holds no discrete entries to gate.", None, "F"),
 ("Why relative is the default form. In a layered control architecture the ratios are intrinsic to the design and travel with the assembly type.", "Relative is the default form because, in a layered control architecture, the ratios are intrinsic to the design and travel with the assembly type.", "F"),
 ("The inner loop runs at `Relative(1)` and the outer loops at `Relative(5)`, whatever the deployment.", None, "F"),
 ("The convention that keeps `K ≥ 1` livable is this: a scope's base rate is its fastest relative member, and that member gets `K = 1`.", "One convention keeps `K ≥ 1` livable. A scope's base rate is its fastest relative member, and that member gets `K = 1`.", "F"),
 ("Two structural properties confine grid cost to the other form.", "Two structural properties keep a relative entry on the scope grid and confine grid cost to the other form.", "F"),
 ("A relative phase selects among scope ticks that already exist, so it never refines the base grid.", "A relative phase never refines the base grid, because it selects among scope ticks that already exist (D-185).", "C"),
 ("And it cannot place a tick between scope ticks.", "It also cannot place a tick between scope ticks.", "F"),
 ("Staggering off-grid means declaring the offset in seconds, or declaring the scope base finer than its fastest member so that unused slots exist.", None, "F"),
 ("An `Absolute` entry detaches its child from the scope's grid", "The child is severed from the enclosing scope's grid", "X"),
 ("Rule. An `Absolute` entry may appear in any scope's `sample_times`, not only the root's.", "An `Absolute` entry may appear in any scope's `sample_times`, not only the root's (D-186).", "C"),
 ("The `(T, τ)` pair it establishes is an anchor, and the child hangs from that anchor.", None, "F"),
 ("The child is severed from the enclosing scope's grid, and no relation to the scope's ticks remains.", None, "F"),
 ("Three corollaries follow:", "Three corollaries follow (D-186):", "C"),
 ("`K ≥ 1` reads \"a child cannot tick faster than the scope it is relative to\". An anchored child may therefore tick faster than its scope.", None, "F"),
 ("The fastest-member convention counts relative members only.", None, "F"),
 ("Phase relationships between an anchored child and its relative siblings are deployment-emergent. Whether their ticks ever coincide depends on how the grid derivation works out.", None, "F"),
 ("That is the question the deployment's `Schedule` (§9.2) exists to answer.", "The deployment's `Schedule` " + S + " exists to answer that question (§9.2).", "F"),
 ("Relative children of an anchored subtree compose against the anchor exactly as against the root grid.", "Relative children of an anchored subtree compose against the anchor exactly as against the root grid (D-186, D-283).", "C"),
 ("A nested anchor simply severs again (the fold, §9.1).", None, "F"),
 ("Absolute periods and nonzero offsets jointly constrain the base grid.", "Absolute periods and nonzero offsets jointly constrain the base grid (D-186, D-283).", "C"),
 ("They join the deployment-time constraint pool (§9.2).", None, "F"),
 ("This is the subtlety with teeth.", "This is the subtle part, and it has a real cost.", "X"),
 ("An offset of `T/2` can cost a 2× finer grid, and `T/1000` a 1000× one.", None, "F"),
 ("The cost is relational, incurred against everything else declared.", None, "F"),
 ("That is why attribution is the engine's job (§9.2).", None, "F"),
 ("A declaration, its compiled pairs, and one hyperperiod", "This example follows one declaration to its compiled pairs and one hyperperiod.", "X"),
 ("Three discrete components sit under two scopes, at a deployment that binds `Δt_base = 2 ms` (§9.2)", None, "F"),
 ("# Root scope: (D_s, Φ_s) = (1, 0). sample_times(::Vehicle) = (fcs = Relative(1), # → (D, Φ) = (1, 0) gnss = Absolute(Hz(50))) # → (10, 0), anchored at T = 20 ms", None, "F"),
 ("# fcs is the enclosing scope of its own children, at (D_s, Φ_s) = (1, 0). sample_times(::FCS) = (inner = Relative(1), # → (1, 0) outer = Relative(5, 2)) # → (5, 2), D = 5·1, Φ = 0 + 2·1", None, "F"),
 ("Those pairs are what the boundary gate reads at run time. One hyperperiod is `lcm(Dᵢ) = 10` base ticks.", None, "F"),
 ("Because the gate is pure modulo arithmetic, that one hyperperiod is the complete truth rather than a sample (§9.2):", None, "F"),
 ("``` base tick k: 0 1 2 3 4 5 6 7 8 9 | 0 1 … inner • • • • • • • • • • | • • (D, Φ) = (1, 0) outer • • | (5, 2) gnss • | • (10, 0) ```", None, "F"),
 ("`outer` is due where `(k − 2) % 5 == 0`, `gnss` where `k % 10 == 0`.", None, "F"),
 ("Should `outer` read a `gnss` cell, the ZOH makes that read two base ticks old at `k = 2` and seven at `k = 7`.", None, "F"),
 ("That is the deterministic aging of a stagger, in this model's numbers.", "The two-tick and seven-tick reads in the example above are the deterministic aging of a stagger, in that model's numbers.", "M"),
 ("Where the doctrinal line falls on mid-tree anchors", "and the doctrinal line falls here.", "M"),
 ("Absolute-first declaration as the default form is rejected (D-019, D-186).", None, "M"),
 ("What mid-tree anchors legitimize is narrower.", "What mid-tree anchors legitimize is narrower,", "M"),
 ("Rule. An absolute declaration inside a library type is legitimate when the rate is a fact about the modeled system, not a preference about the simulation.", "An absolute declaration inside a library type is legitimate when the rate is a fact about the modeled system, not a preference about the simulation (D-186).", "C"),
 ("A GPS receiver emitting at 1 Hz, a bus schedule and an ADC pipeline's fixed conversion offset are as intrinsic to the assembly as its wiring.", "A GPS receiver emitting at 1 Hz, a data bus's transmission schedule and an ADC (analog-to-digital converter) pipeline's fixed conversion offset are as intrinsic to the assembly as its wiring.", "M"),
 ("Forcing them to the root breaks encapsulation, since the root would have to know instrument internals to re-declare them.", None, "M"),
 ("\"Run the controller at 400 Hz in this study\" remains a deployment choice, and the existing idiom remains its answer. The assembly exposes its multiplier as a constructor parameter.", None, "M"),
 ("Absolute pinning from outside a subtree's contract stays rejected as action at a distance.", "Absolute pinning from outside a subtree's contract (its declared interface) stays rejected as action at a distance.", "M"),
 ("The framework cannot police the distinction. It is authoring doctrine, recorded here.", None, "M"),
 ("Anchoring leaves the never-cache-`Δt` argument below fully intact.", "Anchoring leaves the never-cache-`Δt` argument below fully intact (D-186).", "C"),
 ("The pinning happens in the enclosing assembly's `sample_times`, the same site where the multiplier lives.", None, "M"),
 ("The component type itself therefore stays rate-agnostic, and still consumes the `Δt` of its bundle (the NamedTuple of zero-copy views a component function receives).", "The component type itself therefore stays rate-agnostic. It still consumes the `Δt` of its bundle (the NamedTuple of zero-copy views a component function receives).", "M"),
 ("`Δt` has a single source of truth: the deployment's `Schedule`", "`Δt` has a single source of truth, the deployment's `Schedule` (D-187, D-254).", "C"),
 ("Rule. Each discrete component's effective period arrives read-only as the `Δt` field of every discrete-tier bundle (§5.2), in `y_state`, `y_direct` and `s_update` alike.", "Each discrete component's effective period arrives read-only as the `Δt` field of every discrete-tier bundle (§5.2, D-019). The field arrives in `y_state`, `y_direct` and `s_update` alike.", "C"),
 ("The field is absent from continuous bundles, so touching it on the wrong tier is a missing-field error rather than a rule.", "It is absent from continuous bundles, so touching it on the wrong tier is a missing-field error rather than a rule.", "F"),
 ("It must be readable in the stages, not just in `s_update`.", "The field must be readable in the stages, not just in `s_update`.", "F"),
 ("The discretized laws that actually consume `Δt` run in `y_direct`, which computes each law once and publishes it (§5.3, D-015).", None, "F"),
 ("A PID's backward-difference coefficients and a LeadLag's Tustin transform are the examples. `s_update` is a copy.", "A PID controller's backward-difference coefficients and a lead-lag compensator's Tustin transform are the examples. `s_update` is a copy.", "F"),
 ("The value must arrive through the call, and the bundle field is where it arrives.", None, "F"),
 ("A `comp.Δt` virtual property is impossible here, not merely inconvenient (D-019).", None, "F"),
 ("Author rule: never store `Δt`, or any `Δt`-derived coefficient, as a component parameter.", "An author must never store `Δt`, or any `Δt`-derived coefficient, as a component parameter (D-019).", "C"),
 ("Recomputing derived coefficients per tick is a few arithmetic ops. A cached copy is a second thing for gain-scheduling machinery to chase.", None, "F"),
 ("Relative declaration structurally enforces that rule for the period itself.", "Relative declaration structurally enforces that author rule for the period itself.", "F"),
 ("Under scoped multipliers a component author cannot know their absolute rate. It does not exist until composition.", None, "F"),
 ("Phases change none of this. The bundle's `Δt` is still `D·Δt_base`.", "Phases change none of this. The bundle's `Δt` is still `D·Δt_base` (D-185).", "C"),
 ("An offset shifts firing instants and never the period, so the discretized laws are unaffected by staggering.", None, "F"),
]
# Citations that sit elsewhere in the claim's paragraph, by claim text prefix.
EXTRA = {"The constructors themselves": ["D-185"]}
claims = []
for i, (old, new, tag) in enumerate(rows, 1):
    new = new or old
    c = {"id": f"C2-{i:03d}", "old": old, "new": new, "where": "new",
         "cites": sorted(set(CITE.findall(old)))}
    nc = sorted(set(CITE.findall(new)))
    for k, v in EXTRA.items():
        if old.startswith(k): nc = sorted(set(nc) | set(v))
    if nc != c["cites"]: c["newcites"] = nc
    c["tag"] = tag
    claims.append(c)
added = ["#### The two declaration forms", "#### Relative composition", "#### Anchors",
         "#### When an anchor belongs in a library type", "#### A worked example",
         "#### Coincidence and stagger", "#### `Δt` in the bundle",
         "(one declared `Absolute`, below)", "(the declaration design's worked companion)",
         "(analog-to-digital converter)", "data bus's transmission", "PID controller's", "lead-lag compensator's", "(its declared interface)",
         "The root scope holds `fcs`, a flight control system (FCS) scope, and `gnss`, a satellite-navigation (GNSS) component."]
json.dump({"claims": claims, "added": added}, open(os.path.join(H, "inventory.json"), "w"),
          ensure_ascii=False, indent=1)
