"""Builds inventory.json for unit A. Rows: (old, new, where, cites, newcites, tag, ruling)."""
import json, re

CITE = re.compile(r'§\d+(?:\.\d+)?|D-\d{3}|Appendix [A-D]')
N, DEC = "new", "docs/design/decisions.md"

IMPORT = ("`import Cadence: x_init, s_init, m_init, ws_init, u_types, y_types, state_events, "
          "y_state, y_direct, x_deriv, s_update, x_projection, inner_connections, u_connections, "
          "y_connections, sample_times, transparent_container`")
TESTSET = ('`@testset "mycomp" begin y_state(::MyComp, (; x)) = … #a NEW local one, not a method of '
           '… #Cadence.y_state; calls here end #resolve to it, and look correct #outside: '
           'Cadence.y_state still has no MyComp method`')
MSG = ('"`MyEngine`\'s module defines its own `x_deriv`, distinct from `Cadence.x_deriv`; '
       'add `import Cadence: x_deriv`".')

rows = [
 ("## 8. The declaration layer: components and assemblies", None, N, None, "X", None),
 ("This chapter says how an author spells a component.", None, N, None, "X", None),
 ("It covers where the structural facts live, what the build takes as authoritative, and what is checked against what.", None, N, None, "X", None),
 ("§8.1–§8.4 cover the component side, and §8.5–§8.8 the assembly side.", "The first four sections cover the component side.", N, None, "X", None),
 ("The build pipeline is §9, and the stopped-sim service spellings are §14.", None, N, None, "X", None),
 ("The concrete syntax below is near-final in shape but still illustrative in spelling.", None, N, None, "F", None),
 ("### 8.1 Position: a declarative trait layer in plain Julia, no macros", None, N, None, "X", None),
 ("A component is authored in ordinary Julia.", None, N, None, "F", None),
 ("Its stage functions (`y_state` and `y_direct`, the two output stages every component provides on either tier)",
  "Its stage functions are ordinary multiple-dispatch methods. They are `y_state` and `y_direct`, the two output stages every component provides on either tier", N, None, "F", None),
 ("are ordinary multiple-dispatch methods, on the `GUI.draw!` precedent.",
  "The methods follow the `GUI.draw!` precedent, the per-component panel extensions in FlightCore's style (§11.7).", N, ["§11.7"], "C", None),
 ("Its structural facts are declared through a small set of well-known functions returning plain values, defined alongside those methods.",
  "A component's structural facts are declared through a small set of well-known functions returning plain values, defined alongside those methods.", N, None, "F", None),
 ("Four questions about that layer are settled here.", "Five questions about that layer are settled here, one per subsection.", N, None, "R", "R7 (F17)"),
 ("What does it rule out, and what does it still admit (macros)?", None, N, None, "X", None),
 ("How do an author's methods reach the framework's generic functions, and how can they silently fail to (the namespace)?", None, N, None, "X", None),
 ("Which of declaration and evaluation is authoritative (the schema)?", None, N, None, "X", None),
 ("And what may a component's contract depend on (the type)?",
  "What may a component's contract (its declared interface) depend on (the type)?", N, None, "X", None),
 ("#### Plain Julia, not a macro DSL", None, N, None, "X", None),
 ("Rule. There is no macro DSL.", "There is no macro DSL (D-032).", N, ["D-032"], "F", None),
 ("Why. The debugging, tooling and comprehension criterion (§1) decides it (D-032).",
  "The debugging, tooling and comprehension criterion (§1) decides it.", N, ["§1", "D-032"], "F", None),
 ("Redundancy between declarations and function bodies is accepted deliberately, under one non-negotiable condition.", None, N, None, "F", None),
 ("Every inconsistency fails loudly, at build time where possible and at first execution otherwise.",
  "Every inconsistency fails loudly, at build time where possible and at first execution otherwise (D-032).", N, ["D-032"], "C", None),
 ("A macro can only ever lower to a layer like this one.",
  "The reason is that a macro can only ever lower to a layer like this one.", N, None, "F", None),
 ("A convenience macro therefore remains addable a posteriori as pure sugar, on the `@kwdef` precedent, and never becomes essential.",
  "A convenience macro remains addable a posteriori as pure sugar, on the `@kwdef` precedent, and never becomes essential (D-032).", N, ["D-032"], "C", None),
 ("The door stays open for the declaration layer specifically.", None, N, None, "F", None),
 ("A macro generating the well-known declarations is admissible sugar on top of the plain-Julia forms.", None, N, None, "F", None),
 ("It is never a replacement for them and never required to author a component (D-166).",
  "It is never a replacement for them and never required to author a component (D-032).", N, ["D-032"], "R", "R7 (F2)"),
 ("The obvious candidate is the `where {T <: Real}` ceremony of a continuous `y_types` (§8.2).",
  "Every contract declaration takes the component alone on both tiers, is written at nominal `Float64`, and is retyped by the framework.",
  DEC, [], "R", "R7 (F2), deleted; the span is D-263's Position, which retired the ceremony"),
 ("Every rule in this part is stated over the generated methods, so a macro that lowers to them adds convenience and no semantics.", None, N, None, "F", None),
 ("#### The namespace: declarations are extended, not called", "#### The namespace", N, None, "R", "R6"),
 ("Rule. The framework's extensible functions are extended, not called.",
  "The framework's extensible functions are extended, not called (D-117).", N, ["D-117"], "C", None),
 ("Authoring a component means adding methods to framework-owned generic functions.", None, N, None, "F", None),
 ("Julia admits that only through an explicit per-name `import`, or through a qualified `Cadence.x_deriv(…) = …` definition.", None, N, None, "F", None),
 ("The latter is the `Base.show` idiom that the exported-name audit in `pending.md` records for the extension-only periphery surface.", None, N, None, "F", None),
 ("A component module therefore opens with", None, N, None, "F", None),
 (IMPORT, None, N, None, "F", None),
 ("The explicit list is needed because `using Cadence` alone is a silent trap.", None, N, None, "F", None),
 ("After a bare `using`, `x_deriv(eng::Engine, …) = …` defines a new, unrelated `MyModule.x_deriv`, with no error and no warning.", None, N, None, "F", None),
 ("The declarations are deliberately unexported (D-117).", None, N, None, "F", None),
 ("A bare `using` therefore brings no name into scope for the definition to clash with, so there is nothing for the language to detect.", None, N, None, "F", None),
 ("Left alone, the build would see a component with no `x_deriv` method and report a modeling diagnostic, `StoreWithoutUpdate`,",
  "Left alone, the build would see a component with no `x_deriv` method. It would report a modeling diagnostic, `StoreWithoutUpdate` (a non-empty store without its update law, §8.2).", N, ["§8.2"], "F", None),
 ("or `ClassUnreadable` when the whole inventory was shadowed.",
  "When the whole inventory was shadowed, it would report `ClassUnreadable` (no declaration to read a class from, §8.5).", N, ["§8.5"], "F", None),
 ("A one-line namespace mistake would be reported far from the line that caused it.", None, N, None, "F", None),
 ("That is the §8.4 inversion of error locality (the property that a mistake fails at the site of the mistake), arriving through the namespace.",
  "That is the inversion of error locality (the property that a mistake fails at the site of the mistake) that §8.4 traces, arriving through the namespace.", N, None, "F", None),
 ("Two mitigations, both normative.", "Two mitigations apply, both normative.", N, None, "F", None),
 ("The first is that the import list above is authoring surface, stated wherever a component file is first shown.",
  "The first is that the import list above is authoring surface, stated wherever a component file is first shown (D-117).", N, ["D-117"], "C", None),
 ("The second is a shadowing check in the structural walk (§9.1), run on every component before its class is read (D-246).",
  "The second is a shadowing check. The structural walk runs the shadowing check on every component before its class is read (§9.1, D-246).", N, None, "F", None),
 ("If the component's parent module holds a binding of a family name distinct from the framework's function, the build throws `DeclarationShadowed`, alone,",
  "The check looks for a binding of a declaration name (a name in the import list above) in the component's parent module. If the module holds one distinct from the framework's function, the build throws `DeclarationShadowed` alone (D-246).", N, ["D-246"], "F", None),
 ("naming the module, the foreign names and the missing import:",
  "The diagnostic names the module, the foreign names and the missing import.", N, None, "F", None),
 (MSG, "Its message reads " + MSG, N, None, "F", None),
 ("The check is a two-line `isdefined`/`!==` test on the family's names.", "The check is a two-line `isdefined`/`!==` test on those names.", N, None, "F", None),
 ("Those names are distinctive by design (D-220), so a foreign binding of one of them in a component's module is evidence of the missing import, not a coincidence.", None, N, None, "F", None),
 ("The check throws alone because nothing the module declares can be trusted.", None, N, None, "F", None),
 ("Every declaration it holds may have gone to a foreign function, and a walk past it would only report cascades of the one cause.", None, N, None, "F", None),
 ("It runs on every component rather than only where an absence is noticed, because an optional declaration such as `state_events` or `sample_times` has no absence to notice.", None, N, None, "F", None),
 ("Shadowed, it would drop its feature silently.", None, N, None, "F", None),
 ("A convenience macro expanding to the import list remains addable a posteriori as sugar, per this section's macro doctrine.", None, N, None, "F", None),
 ("A re-export submodule is not an alternative,", "A re-export submodule is not an alternative (D-117).", N, ["D-117"], "R", "R4"),
 ("because per-name `import` is the only unqualified extension mechanism the language provides (D-117).",
  "`using Cadence.Declarations` carries identical silent-shadowing semantics — per-name `import` is the only extension idiom the language provides.",
  DEC, ["D-117"], "R", "R4; 'unqualified' is also carried in the new text by \"Julia admits that only through an explicit per-name `import`, or through a qualified ... definition\""),
 ("The same trap has a local-scope sibling (D-164).", None, N, None, "F", None),
 ("Written inside a `let`, a function body or a `@testset`, `y_state(::MyComp, (; x)) = …` does not add a method to the global `y_state`.", None, N, None, "F", None),
 ("It binds a new local function of that name.", None, N, None, "F", None),
 ("Calls within the block resolve to it and look correct.", None, N, None, "F", None),
 ("The generic function the build dispatches on never learns of the component, which therefore reads as one declaring nothing at all.", None, N, None, "F", None),
 (TESTSET, None, N, None, "F", None),
 ("The shadowing check above cannot reach this case.", None, N, None, "F", None),
 ("There is no parent-module binding to compare, because the shadow is a local binding that disappears with its block.", None, N, None, "F", None),
 ("So the mitigation sits at the other end.", "The mitigation therefore sits at the other end.", N, None, "F", None),
 ("A component that declares nothing and defines no stage is rejected at build time, because an inert component is unwritable on purpose.",
  "A component that declares nothing and defines no stage is rejected at build time (D-164), because an inert component is unwritable on purpose.", N, ["D-164"], "C", None),
 ("That check costs a line, and it catches the misspelled-declaration family with it.", None, N, None, "F", None),
 ("Test code is the realistic victim, with a fixture component defined inside its own `@testset`.", None, N, None, "F", None),
 ("The authoring rule is one line.", None, N, None, "F", None),
 ("Declarations live at module top level.", "Declarations live at module top level (D-164).", N, ["D-164"], "C", None),
 ("The net holds under a partially shadowed component too, because `y_types` is still a declaration.",
  "The net also holds when only a stage is shadowed, because `y_types` is still a declaration.", N, None, "R", "R7 (F24)"),
 ("A component whose ports are declared but whose stage went to a local binding reads as \"declared but not produced\" (§8.3) rather than as a component with nothing to say.",
  "A component whose ports (its declared, addressable names) are declared but whose stage went to a local binding reads as \"declared but not produced\" (§8.3). It does not read as a component with nothing to say.", N, None, "F", None),
 ("#### Names: four classes by role", "#### Names", N, None, "R", "R6"),
 ("Rule. Every name on the framework's surface belongs to one of four classes, and its class fixes its grammatical shape (D-144).",
  "Every name on the framework's surface belongs to one of four classes, and its class fixes its grammatical shape (D-144).", N, None, "F", None),
 ("1. Declarations are noun phrases naming what they return, prefixed by the bundle field they define where one exists (D-267).", None, N, None, "F", None),
 ("An assembly's boundary declarations take `u` and `y` too.", None, N, None, "F", None),
 ("There the letter names a side of the contract, which on a leaf is also a bundle field (D-279).", None, N, None, "F", None),
 ("The author defines them and the framework calls them:", "The author defines them and the framework calls them.", N, None, "F", None),
 ("`inner_connections`, `u_connections`/`y_connections`, `state_events`, `u_types`, `ws_init`, the stage and update-law names (D-220), and `claims(b)` from the binding interface (§11.6).",
  "They include `inner_connections`, `u_connections`/`y_connections`, `state_events`, `u_types`, `ws_init`, the stage and update-law names (D-220), and `claims(b)` from the binding interface (§11.6).", N, None, "F", None),
 ("2. Value selectors carry `get_`.", None, N, None, "F", None),
 ("They are called against `reads` and against snapshots (§14.4).",
  "They are called against `reads` and against snapshots, the immutable per-boundary publications (§14.4).", N, None, "F", None),
 ("3. Lifecycle and mutating actions are verbs, with `!` when they mutate.", None, N, None, "F", None),
 ("4. Build primitives are plain verbs (§13.3).", None, N, None, "F", None),
 ("A name in the wrong class is a rename candidate on that ground alone.", None, N, None, "F", None),
 ("The convention also has a semantic axis.", None, N, None, "F", None),
 ("A name can sit in the right class and still pick the wrong noun.", None, N, None, "F", None),
 ("A declaration names its content, never the consequence the declaration has.", None, N, None, "F", None),
 ("`input_passthrough` (§8.8, D-171) and the binding methods `claims`/`reads` (§11.6, D-146) apply that axis, and `exports` is its retired exemplar (D-170).", None, N, None, "F", None),
 ("The `_connections` family names content deliberately, for authoring transparency.", None, N, None, "F", None),
 ("That is a recorded choice, not class drift.", None, N, None, "F", None),
 ("Which names the module exports is a separate question.", None, N, None, "F", None),
 ("It stays open until the exported-name audit in `pending.md` runs (D-226).", None, N, None, "F", None),
 ("#### Declarations are the schema authority", None, N, None, "R", "R6 (moved up within §8.1)"),
 ("Rule. Declarations define the model's structure.", "Declarations define the model's structure (D-032).", N, ["D-032"], "C", None),
 ("Evaluation checks conformance against them, never the reverse.", None, N, None, "F", None),
 ("The build probes user functions with real values, with no reliance on compiler inference, and compares observed against declared.", "The build probes user functions with real values (a single evaluation of each, its result discarded), with no reliance on compiler inference, and compares observed against declared.", N, None, "F", None),
 ("The same comparison then runs on every subsequent evaluation for free, as a `NamedTuple`-type check that constant-folds away when conformant.", None, N, None, "F", None),
 ("Inference-by-evaluation as schema authority is rejected on three counts, established by walkthrough (§8.4) and litigated in D-032.", "Inference-by-evaluation as schema authority (the source that defines structure) is rejected on three counts, established by walkthrough (§8.4) and litigated in D-032.", N, None, "F", None),
 ("Types come by declaration, values by execution, and conformance by comparison.", None, N, None, "F", None),
 ("#### Contracts are functions of the type, not of the instance", "#### Contracts are functions of the type", N, None, "R", "R6 (moved up within §8.1)"),
 ("Rule. A leaf's contract declarations (`u_types`, `y_types`, `state_events`, and the shapes of `x_init`/`s_init`/`m_init`)",
  "Those declarations are `u_types`, `y_types` and `state_events`, and the shapes of `x_init`/`s_init`/`m_init`.", N, None, "F", None),
 ("must be determined by the component's type, its type parameters included, and never by its field values.",
  "A leaf's contract declarations must be determined by the component's type, its type parameters included, and never by its field values (D-033).", N, ["D-033"], "C", None),
 ("The value-discarding signature `u_types(::Engine)` is the visible form of the rule.",
  "The value-discarding signature `u_types(::Engine)` is the visible form of the rule (`Engine` is the example component of §8.2).", N, None, "F", None),
 ("The idiom for a contract that genuinely varies is the type parameter, not the field, as in `SumJunction{Wrench, 3}` (§6.2) and `Or{N}` (§13.7).", None, N, None, "F", None),
 ("Arity is spelled in the type, at the price §6.2 states openly.", None, N, None, "F", None),
 ("Why. The entry typing decides it (§9.7).", "The reason is how entries of the executor (the compiled form of the stage execution order) are typed (§9.7).", N, None, "R", "K3"),
 ("A component's bundle is the `NamedTuple` of zero-copy views a component function receives, and its key set is its contract's.", None, N, None, "F", None),
 ("An entry of the executor, the compiled form of the stage execution order, carries what selects code in type parameters and what is plain data in fields.", "An executor entry carries what selects code in type parameters and what is plain data in fields.", N, None, "R", "K3"),
 ("A key set derivable only from field values would therefore have to go one of two ways.", None, N, None, "F", None),
 ("It could climb into the type parameters anyway, multiplying specialization and changing the cost model (§9.7) of chunking, the splitting of a large phase body into statically typed chunks.", None, N, None, "F", None),
 ("Or it could sit in fields, dissolving the static typing that the zero runtime graph logic (§5.1), the allocation invariant (§7.5) and the fold-away conformance test (§9.5) all rest on.", None, N, None, "F", None),
 ("The build reads each declaration once, against the concrete instance, so a value-dependent contract does not announce itself.", None, N, None, "F", None),
 ("This is a rule authors keep, not a check the build can run.", None, N, None, "F", None),
 ("`ws_init` is the one exception, and explicitly so.", "`ws_init` is the one exception, and explicitly so (D-033).", N, ["D-033"], "C", None),
 ("It is the by-allocation convention (D-077), an allocator the framework calls rather than a schema it walks.", None, N, None, "F", None),
 ("It legitimately takes sizes from the instance (`ws_init(c::KF, ::Type{T})` reads `c.n`, §7.3), because no entry type is derived from it.", None, N, None, "F", None),
]

added = [
 "§8.1 lays the foundations of the declaration layer, §8.2 lists the declaration inventory, §8.3 says what a contract makes visible, and §8.4 gives the five failure walkthroughs that ground error locality.",
 "The last four cover the assembly side.",
 "§8.5 covers assembly declaration, how a type's class is read, container children and `Group`.",
 "§8.6 covers paths, wiring and faces, works them through the strapdown IMU, and ends with the boundary-sampling contract.",
 "§8.7 covers rate scopes, and §8.8 covers computed connections and generic holding.",
 "(`Engine` is the example component of §8.2)",
 "(a single evaluation of each, its result discarded)",
 "(the source that defines structure)",
 "(the continuous or discrete side of the hybrid formalism)",
 "the per-component panel extensions in FlightCore's style (§11.7)",
 "one per subsection",
 "And what grammatical shape does each name on the framework's surface take (names)?",
 "(its declared interface)",
 "(a non-empty store without its update law, §8.2)",
 "(no declaration to read a class from, §8.5)",
 "(a name in the import list above)",
 "The refusal is `ClassUnreadable` (§8.5).",
 "(its declared, addressable names)",
 "An optional declaration shadowed in a local scope, such as `state_events` or `ws_init`, drops its feature silently (D-178).",
 "A binding is the value passed at `attach!` that makes a device framework-legible.",
 ", the immutable per-boundary publications",
]

claims = []
for i, (old, new, where, newcites, tag, ruling) in enumerate(rows, 1):
    c = {"id": f"A-{i:03d}", "old": old, "new": new if new is not None else old,
         "where": where, "cites": sorted(set(CITE.findall(old)))}
    if newcites is not None:
        c["newcites"] = newcites
    c["tag"] = tag
    if ruling:
        c["ruling"] = ruling
    claims.append(c)

json.dump({"claims": claims, "added": added}, open(__file__.replace("build_inventory.py", "inventory.json"), "w"),
          ensure_ascii=False, indent=1)
