import csv
PRE = "pre-existing: "
V = {}
def s(rows, v, n):
    for r in (rows if isinstance(rows, (list, range)) else [rows]):
        V[r] = (v, n)
R5 = "fixed by R5/R15: §7.5 now states it; the old chapter did not"
CARVE = "holds in substance since R5/R15 (§7.5: publication not a phase body, its per-boundary snapshot allocation sits with logging on the framework side, outside what the invariant claims is zero); the word carve-out is not §7.5's"
# spec.md
s(1,"OK","opening keeps the sentence word for word (R1)")
s(2,"OK","§7.5 hot-path budget exactly zero, CI-enforced; scope sentence names the stepping loop")
s(3,"VAGUE",PRE+"§7.1 declares a flat NamedTuple of real scalars and SArrays of a common eltype T, not an isbits struct of real scalars; old text the same; chapter 3's rewrite or track 2")
s(4,"VAGUE",PRE+"§7.3: every field isbits or a Symbol (D-231), not any isbits value; old text the same; chapter 3's rewrite or track 2")
s(5,"OK","§7.1: the framework-owned buffer holds continuous state; §7.3 keeps 'the buffer that holds x'. M2 cut §7.1's 'The buffer holds x, the stores hold s and m' (now §5.2 only)")
s(6,"OK","§7.3: the s and m stores, framework-owned homes of those letters")
s(7,"OK","'interned, immutable and never freed' word for word in §7.3")
s(8,"OK","")
s(9,"OK","§7.1 immutable state values; §7.3 immutable-value discipline")
s(10,"OK","§7.4 split paragraph: 'idiom of choice when the factoring earns reuse'")
s(11,"OK","opening keeps the sentence word for word (R1)")
s(12,"OK","")
s(13,"OK","KF allocator block verbatim; 'Sizes come from the instance'")
s(14,"VAGUE",PRE+"§7.1 fixes leaves 'of a common eltype T'; the rule that a state leaf follows the activation scalar is §7.2's ('in the x_init-derived state type alike'); old text the same. Track 2: cite §7.2 beside §7.1")
s(15,"VAGUE",PRE+"'not memory' is D-077 Rejected's phrase; §7.3 says 'mutable scratch, deliberately not state at all' and 'Scratch is allocated, not retyped'")
s(16,"OK","§7.1: 'Domain wrapper types are not state leaves either. Two such types are RQuat ...'")
s(17,"OK","§7.2: the discrete side's exemption, the Exempt tier; 'the discrete exemption' was never word for word, old or new")
s(18,"OK","")
s(19,"OK","Walked tier: constructors infer T")
s(20,"OK","consumer 4, 'CI invariant'")
s(21,"VAGUE",PRE+"§7.1 implies it ('of a common eltype T', kept word for word) and never states it; D-295 points back, so §7.1 must not cite D-295 for it")
s(22,"OK","")
s(23,"OK","")
s(24,"OK","")
s(25,"OK","")
s(26,"OK","§7.3: bulk data and labels have their home on the component instance")
s(27,"OK","")
s(28,"OK","")
s(29,"OK","§7.2 keeps FrameTransform as the Walked tier's one example (R2, R12); the full list moved to the companion")
s(30,"OK","§7.1 'explicit, invariant-free cast at the point of use'; the code comment's label was never word for word")
s(31,"OK","")
s(32,"OK","")
s(33,"OK","ws_init takes the activation scalar; a continuous workspace joins the T-generic surface")
s(34,"OK","Pinned tier stays Float64; Pinned{P} marker")
s(35,"OK",R5)
s(36,"OK","")
s(37,"OK","")
s(38,"OK","§7.1 last bullet: the mapping layer is deleted (D-072); now called Flight.jl's (R17)")
s(39,"OK","")
s(40,"OK","§7.1 flat layout over one contiguous Vector{T}")
s(41,"OK","'buffer-unchanged-within-a-sweep' word for word; §7.1 states the rule in its own words and points to §9.7 without pointing back circularly")
s(42,"MISSING",PRE+"'per-call by topological necessity' was never in §7.1; old §7.1 said only that the executor is spelled rebuild-per-call (M1 trimmed it to 'views rebuilt per call', §9.7). Not a loss. Track 2: drop '(§7.1)'; §9.7's own 'Views are spelled rebuild-per-call' carries it")
s(43,"OK","")
s(44,"OK","§7.5: CI-enforced at the phase-body seam that phase_bodies exposes (§9.7, D-116)")
s(45,"OK","'a documented tolerance' word for word; the seam scopes it per body")
s(46,"VAGUE",PRE+"was MISSING; "+CARVE)
s(47,"OK","'CI-testable invariant'")
s(48,"OK","")
s(49,"OK","")
s(50,"OK",R5+" ('on the framework side', 'with logging')")
s(51,"OK","")
s(52,"OK",R5)
s(53,"VAGUE",PRE+"§7.5 says sizehint! 'to the retention bound', the reconciled form this sentence describes; old text the same")
s(54,"VAGUE",PRE+"was MISSING; "+CARVE)
s(55,"VAGUE",PRE+"§7.5 scopes the invariant to 'the stepping loop', not 'the model sweep'; the framework side with publication and logging now holds (R5/R15). Track 2: one term")
s(56,"OK","")
s(57,"OK","§7.1: 'Constructors run on the write paths, never on views'")
s(58,"OK",R5)
s(59,"OK","")
s(60,"OK","step 2 keeps its number and 'one-line function body' (R3)")
s(61,"OK",R5)
s(62,"OK","")
s(63,"VAGUE",PRE+"'layout image' is Appendix B's phrase; §7.1 says an Ẋ-typed value scatter-stored into the flat ẋ buffer")
s(64,"OK","")
s(65,"OK","§7.1 now names IllegalStateLeaf (R8 F17)")
s(66,"MISSING",PRE+"§7.1 states no port-type condition, old or new; §4.3 547-549 does. Track 2: cite §4.3 in place of §7.1")
s(67,"OK","§7.3 names IllegalStoreField")
s(68,"OK","")
s(69,"OK","")
s(70,"OK","holds jointly: §5.2 (spec 820-822) carries 'no store mirrors another'; §7.1 keeps 'no state cells ... interface, not transport' (M2)")
s(71,"OK","")
s(72,"MISSING",PRE+"§7.5 mentions neither the integrator's buffers nor the mid-step table, old or new. Track 2: drop §7.5, §10.3 and §10.4 carry it")
s(73,"OK","§7.3 holds the store rules; the root-input clause is §4.1's and §11.2's, also cited")
s(74,"OK","")
s(75,"OK","")
s(76,"OK","")
s(77,"OK","§7.3 Idioms: 'The blessed (explicitly sanctioned) idiom for zero-allocation ticks'")
# decisions.md
for r in [78,79,80,81,82,85,87,88,89,92,95,97,99,100,103,104,106,108,109,110,117,119,124,126,127,129,131,132,138,139,140,142,143,145,147,148,149,150,151,159,164,165,168,169,170,171,172,173,174,177,178,181]:
    s(r,"OK","Spec field; the section still holds the entry's content")
s(83,"OK","Spec field; D-035 is now also cited at §7.1 (Spec field gains §7.1 at landing)")
s(84,"OK",R5+" (stopped-sim allocation)")
s(86,"OK","§7.1 last bullet, D-072 cited")
s(90,"OK","§7.1's closed vocabulary; old log vocabulary (init_x, Stratum A)")
s(91,"OK",""); s(93,"OK","")
s(94,"OK","")
s(96,"VAGUE",PRE+"was MISSING; "+CARVE)
s(98,"OK","§7.1 write-back bullet: the two positions of §5.3 (D-111)")
s(101,"VAGUE",PRE+"tiers hold; was MISSING; "+CARVE)
s(102,"VAGUE",PRE+"tiers hold; was MISSING; "+CARVE)
s(105,"OK","history: poison retired by D-183; true as history")
s(107,"OK","step 2 keeps its number")
s(111,"OK","history: §7.5 still cites §5.3 for x_projection's positions")
s(112,"OK","history: §7.1's write-back bullet keeps the back-reference to §5.3")
s(113,"OK","about the companion's own §7"); s(114,"OK","about the companion's own §7")
s(115,"OK","D-135 now cited at §7.5")
s(116,"OK",R5)
s(118,"VAGUE",PRE+"'scoped model-sweep' invariant: §7.5 says the stepping loop (same term mismatch as spec 7819)")
s(120,"OK","")
s(121,"OK",R5+" ('framework side')")
s(122,"VAGUE",PRE+"§7.5 says sizehint! 'to the retention bound'; old text the same")
s(123,"OK","the canary")
s(125,"VAGUE",PRE+"§7.1 says flat layout; the leaf walk's glossary home is §8.2")
s(128,"OK","")
s(130,"OK","the canary")
s(133,"VAGUE",PRE+"same as spec 2195: the follow-the-scalar rule is §7.2's")
s(134,"OK","")
s(135,"VAGUE",PRE+"'§7.1's walk being total': §7.1 closes the vocabulary; the walk is §7.2's and §8.2's")
s(136,"VAGUE",PRE+"same as spec 2599: §7.1 implies, never states, no pinned state leaf")
s(137,"OK","step 4 keeps its number and the identity-transport finding")
s(141,"VAGUE",PRE+"was MISSING; "+CARVE)
s(144,"OK","")
s(146,"MISSING",PRE+"§7.2 says nothing about the clock, old or new. Track 2: drop '(§7.2)' or cite where the run's time scalar is stated")
s(152,"OK","history: the prior §7.3 text"); s(153,"OK","'governed by contract rather than by checks' word for word in §7.3's opening"); s(154,"OK","history: the prior §7.3 text")
s(155,"OK","§7.1 write-back bullet; new text cites D-235 at §7.2 (Spec field gains §7.2 at landing)")
s(156,"OK","§7.2's author rules")
s(157,"OK",R5+": §7.5 now gives the scope"); s(158,"OK",R5+": §7.5 now gives the scope")
s(160,"OK","'interned, immutable and never freed' word for word"); s(161,"OK","§7.5 event-firing paragraph keeps 'the honest remedy'"); s(162,"OK",""); s(163,"OK","§7.5 remedy kept (M9)")
s(166,"OK","")
s(167,"OK","")
s(175,"OK",""); s(176,"OK","")
s(179,"VAGUE",PRE+"was MISSING; §7.5 now cites D-288 and states publication is not a phase body; "+CARVE)
s(180,"VAGUE",PRE+"same as spec 2599")
s(182,"OK","history: store as §4.1 and §7.3 used it"); s(183,"OK","history")
# others
s(184,"OK",""); s(185,"OK",""); s(186,"OK","")
s(187,"OK","'stay `Float64`' and 'promotion handles mixing' word for word in §7.2's Pinned tier")
s(188,"OK","'promotion handles mixing' word for word")
s(189,"VAGUE",PRE+"the quoted 'no `::SomeType{Float64}` annotations' was never word for word; §7.2 rule 3 reads 'No `::SomeType{Float64}` return-type annotations'. Track 2: fix the quote")
s(190,"OK","§7.2: one walk retypes it per activation")
s(191,"OK","§7.2 Walked tier keeps the @kwdef pattern sentence (R2)")
s(192,"COMPANION","the walked payload list moved to migration_outline.md, 'The parametrization pass'; §7.2 keeps the Walked tier, 'mechanical' and one example")
s(193,"OK",""); s(194,"OK",""); s(195,"OK",""); s(196,"OK","")
s(197,"OK","§7.5 logging tier: the log retains the published snapshot objects by reference")
s(198,"OK",""); s(199,"OK","")
s(200,"OK","§7.5 now names publication's per-boundary snapshot allocation (R5/R15)")
s(201,"OK","§7.5 keeps GC.gc(false) at frame boundaries")
s(202,"OK",""); s(203,"OK","")
s(204,"OK","§7.1 keeps RQuat and Ranged"); s(205,"OK","")

rows = list(csv.reader(open('inbound.tsv'), delimiter='\t', quoting=csv.QUOTE_NONE))
hdr, data = rows[0], rows[1:]
fh = open('inbound_check.tsv','w')
class W:
    def writerow(self, r): fh.write('\t'.join(r)+'\n')
out = W()
out.writerow(hdr+['verdict','note'])
from collections import Counter
c = Counter(); missing=[]
for i,r in enumerate(data,1):
    if r[0].startswith('briefs/') or r[0].startswith('tools/'):
        v,n = "HISTORY","frozen record or older numbering"
    elif i in V: v,n = V[i]
    else: missing.append(i); v,n="?",""
    c[v]+=1
    out.writerow(r+[v,n])
print(c, 'unassigned', missing)
pre = sum(1 for i,(v,n) in V.items() if n.startswith(PRE))
print('pre-existing', pre)
