import json, os
H = os.path.dirname(os.path.abspath(__file__))
DEC = "docs/design/decisions.md"
# (old, new, tag, extra) ; new=None means same as old; extra: dict
C = [
("`u_types(::C)`", "#### Input contracts: `u_types`", "R", {"ruling": "R6"}),
("An `u_types` declaration is a bare `NamedTuple` of types, written at nominal `Float64` and taking the component alone on both tiers.",
 "An `u_types` declaration is a bare `NamedTuple` of types, written at nominal `Float64` and taking the component alone on both tiers (D-263).", "C", {"newcites": ["D-263"]}),
("The one piece of framework vocabulary it admits is the `Pinned{P}` marker, which wraps a leaf type to say that the leaf never follows the activation scalar.",
 "The one piece of framework vocabulary it admits is the `Pinned{P}` marker. The marker wraps a leaf type to say that the leaf never follows the activation scalar.", "F", {}),
("It wraps the whole entry, and a marker below the top of an entry is `IllegalPortType` (D-265).", None, "F", {}),
("On a continuous consumer the declaration is walked: every `Float64` position follows the scalar, and a `Pinned` leaf stays `Float64`.",
 "On a continuous consumer the declaration is walked, which means that every `Float64` position follows the scalar and a `Pinned` leaf stays `Float64`.", "F", {}),
("On a discrete consumer it pins wholesale, and a `Pinned` entry there says nothing and is `DeclarationOnWrongTier` (§8.5).",
 "On a discrete consumer it pins wholesale. A `Pinned` entry there says nothing and is `DeclarationOnWrongTier` (§8.5, D-263).", "C", {"newcites": ["§8.5", "D-263"]}),
("Entries are face bounds, not cell types, and the reading is permissive (D-167).",
 "Entries are face bounds, not cell types, and the reading is permissive (D-263, D-078).", "R", {"ruling": "R9", "newcites": ["D-263", "D-078"]}),
("An entry states, per leaf, what the consumer allows to arrive there.", None, "F", {}),
("Entries come in three forms:", "Entries come in three forms.", "F", {}),
("| entry | the leaf is | what may lawfully arrive | |---|---|---| | `Float64`, alone or as a type parameter (`SVector{3, Float64}`, `RQuat{Float64}`) | tolerant | the activation scalar or a frozen `Float64` | | `Pinned{Float64}`, or `Pinned{P}` around any leaf type | demanding frozen | never partials | | `Int`/`Bool`/enum leaves, abstract reference-typed entries | as it always was | what the declared bound admits |", None, "F", {}),
("An unpinned entry is what a promoting consumer writes, and it is the overwhelmingly common case.", None, "F", {}),
("A walking producer, a frozen discrete producer and a root input are all admissible behind it, so substitution stays intact.",
 "A walking producer, a frozen discrete producer and a root input (the root component's own input face, produced by no component) are all admissible behind it. Substitution therefore stays intact.", "F", {}),
("A `Pinned` entry is the FFI door.", None, "F", {}),
("This input must never carry partials.", None, "F", {}),
("A component whose internals cannot propagate `Dual`s (an opaque wrapper, a C table, a hand-rolled solver) declares it, and its AD-incompatibility becomes schema-visible instead of folklore.",
 "A component whose internals cannot propagate `Dual`s (an opaque wrapper, a C table, a hand-rolled solver) declares it. Its AD-incompatibility then becomes schema-visible instead of folklore.", "F", {}),
("The failure then moves from a `MethodError` inside user math at the first `Dual` probe to a named wiring error at build (§6.1).",
 "The failure moves from a `MethodError` inside user math at the first `Dual` probe (the build's checking evaluation of a user function) to a named wiring error at build (§6.1).", "F", {}),
("`Int`/`Bool`/enum leaves and abstract reference-typed entries stand as they always were.",
 "`Int`/`Bool`/enum leaves and abstract reference-typed entries stand as they always were, admitting what their declared bound admits.", "F", {}),
("Abstract entries state structural substitutability, several concrete producer types admissible behind one stable face.",
 "Abstract entries state structural substitutability (D-078). Several concrete producer types are admissible behind one stable face.", "C", {"newcites": ["D-078"]}),
("The field handles (§4.4) are the demonstrated client, as in `terrain = AbstractTerrainField`.", None, "F", {}),
("They carry no scalar position, because they are references rather than numbers.", None, "F", {}),
("They are still never the tool for eltype genericity.", None, "F", {}),
("That is exactly what an unpinned entry is, a promoting consumer writing `SVector{3, Float64}` rather than an abstract bound.",
 "That tool is exactly an unpinned entry, a promoting consumer writing `SVector{3, Float64}` rather than an abstract bound.", "F", {}),
("Names-only contracts were rejected (D-033).",
 "- Names-only input contracts: lose wiring-time type errors and standalone checkability.", "R", {"ruling": "R4", "where": DEC}),
("Inputs are the component's requirements.", None, "F", {}),
("Only against them are the unconnected-input error (§6.1), over-wiring detection and did-you-mean typo messages definable at all.", None, "F", {}),
("A did-you-mean message is the offending name plus the list-in-hand it should have matched.", None, "F", {}),
("Two clauses check a wire (§6.1).", "Two clauses check a wire (§6.1, D-263, D-236).", "R", {"ruling": "R2", "newcites": ["§6.1", "D-263", "D-236"]}),
("The nominal bound check is stated at nominal.", "The first is the nominal bound check, stated at nominal.", "F", {}),
("The producer's declaration at `Float64`, markers stripped, must be `<:` the entry at `Float64`.",
 "The producer's declaration at `Float64`, markers stripped, must be `<:` the entry at `Float64` (D-078).", "C", {"newcites": ["D-078"]}),
("It is one uniform rule, and it degenerates to exact equality for a concrete entry, because concrete types are final.",
 "It is one uniform rule. It degenerates to exact equality for a concrete entry, because concrete types are final.", "F", {}),
("Beside it sits the tier-scoped walk-compatibility clause.", None, "F", {}),
("For a continuous consumer, a walking producer leaf (one the producer left unpinned) requires an unpinned entry, while a pinned producer leaf satisfies either, because frozen values embed upward.",
 "For a continuous consumer, a walking producer leaf (one the producer left unpinned) requires an unpinned entry. A pinned producer leaf satisfies either, because frozen values embed upward.", "F", {}),
("An opaque leaf embeds nothing and is admitted at an unpinned entry as the producer's cell (D-264).", None, "F", {}),
("Both sides are plain declarations the walk retypes, so the clause is decidable in the structure step (the build's first step, declaration reading only) by retyping them at a marker scalar.",
 "Both sides are plain declarations the walk retypes. The clause is therefore decidable in the structure step (the build's first step, declaration reading only) by retyping them at a marker scalar.", "F", {}),
("No user stage code runs (§9.1), and a violation is `WalkingFaceAtFrozenEntry`.",
 "No user stage code runs (§9.1). A violation is `WalkingFaceAtFrozenEntry`.", "F", {}),
("Discrete consumers take the bound check only, and that scope is a correctness rule rather than tidiness.",
 "Discrete consumers take the bound check only (D-263). That scope is a correctness rule rather than tidiness.", "R", {"ruling": "R9", "newcites": ["D-263"]}),
("Why. A discrete stage reads exclusively at real ticks in the nominal world, and a `Dual`-carrying cell exists only inside activations discrete stages never run in (§9.4).",
 "A discrete stage reads exclusively at real ticks (the instants a discrete component runs) in the nominal world. A `Dual`-carrying cell exists only inside activations discrete stages never run in (§9.4).", "F", {}),
("Wires from a continuous producer to a discrete consumer are therefore unconditionally legal.", None, "F", {}),
("The unscoped variant is rejected in D-167.", "The unscoped variant is rejected.", "R", {"ruling": "R9", "newcites": []}),
('Because entries are bounds, nothing is ever "overwritten".', None, "F", {}),
("Cell types are single-sourced from the producer side per activation (§9.4), and a `Dual`-carrying cell behind an unpinned entry is the design working, not a promise broken.",
 "Cell types are single-sourced from the producer side per activation (§9.4, D-054). A `Dual`-carrying cell behind an unpinned entry is the design working, not a promise broken.", "C", {"newcites": ["§9.4", "D-054"]}),
("The code-level complement is the genericity obligation, which says that whatever scalars the wiring delivers, the consumer's math promotes.",
 "The code-level complement is the genericity obligation. It says that whatever scalars the wiring delivers, the consumer's math promotes.", "F", {}),
("The obligation is still checked by the `Dual` probe, never declared, and it is scoped to the unpinned entries.",
 "It is still checked by the `Dual` probe, never declared (D-054). The obligation is scoped to the unpinned entries (D-263).", "R", {"ruling": "R9", "newcites": ["D-054", "D-263"]}),
("A `Pinned` input imposes no such obligation, which is its point.", None, "F", {}),
("So declarations record choices, and obligations are checked.",
 "Declarations record choices, and obligations are checked (D-078).", "C", {"newcites": ["D-078"]}),
("The marker's absence records the tolerance choice, and the probe checks the promotion.", None, "F", {}),
("The permissive reading is the operative one,", "The permissive reading is the operative one (D-263).", "C", {"newcites": ["D-263"]}),
("and the two readings it escapes are rejected (D-033, D-054, D-167, D-263).",
 "- Symmetric `T` as genericity envelope: a per-leaf marking that is a constant function across components — zero information, wrong granularity, false-affordance pins; the predictive reading remains impossible per D-054.",
 "R", {"ruling": "R4", "where": DEC}),
("The predictive reading has the entry saying what will arrive.", None, "F", {}),
("The envelope reading has it as a promise to promote.", None, "F", {}),
("The permissive reading predicts nothing, and it is not constant, because pinned entries are rare but real.", None, "F", {}),
("That is what makes the marker carry information here.", None, "F", {}),
("Root inputs are the one place an entry types a cell.", None, "F", {}),
("A root input is produced by no component, so it has only the consumer declaration to take a type from.", None, "F", {}),
("The root-input type is the entry at `Float64`, markers stripped, and only a tight bound determines one.",
 "The root-input type is the entry at `Float64`, markers stripped, and only a tight bound determines one (D-078).", "C", {"newcites": ["D-078"]}),
("A face surfacing as a root input must therefore resolve to a concrete declaration, which staging cells, the trace header and `probe_value` all need.", None, "F", {}),
("Abstract-at-root is a build error,", "Abstract-at-root is a build error (D-236).", "C", {"newcites": ["D-236"]}),
("and `AbstractAtRoot` names the face and the remedy, which is to wire a concrete producer, or a stub child in a test rig (§13.7).",
 "`AbstractAtRoot` names the face and the remedy, which is to wire a concrete producer, or a stub child in a test rig.", "C", {"newcites": ["§13.7", "D-120"]}),
("Under fan-out the root-input type is the unique concrete declaration among its consumers, and abstract co-consumers are checked against it.",
 "Under fan-out the root-input type is the unique concrete declaration among its consumers, and abstract co-consumers are checked against it (D-236).", "C", {"newcites": ["D-236"]}),
("Two different concrete declarations remain an error.", "Two different concrete declarations remain an error, `RootInputTypeConflict` (D-236).", "R", {"ruling": "R14", "newcites": ["D-236"]}),
("The root-input cells at an activation follow the root-input type by retyping that same entry at the activation's `T`.", None, "F", {}),
("This makes seedability schema-visible.", "That retyping makes seedability schema-visible (D-263).", "R", {"ruling": "R9", "newcites": ["D-263"]}),
("An unpinned root input is a lawful linearization `B`-matrix tap, and a `Pinned` root input is declaredly unseedable (§14.10).", None, "F", {}),
("Fan-out combines tolerance by a meet, not by agreement (D-168).", None, "F", {}),
("The root input pins at every activation if any consumer's entry pins, and follows the scalar only when every consumer tolerates.",
 "The root input pins at every activation if any consumer's entry pins. It follows the scalar only when every consumer tolerates.", "F", {}),
("Concretely, the root-input cells at an activation are the root-input type with every leaf following the scalar when every consumer's entry admits that type, and the root-input type itself otherwise.", None, "F", {}),
("A mixture of pins across leaves therefore pins the whole root input (D-236).", None, "F", {}),
("Two consumers of one root input may agree at nominal and still differ in tolerance.", None, "F", {}),
("`SVector{3, Float64}` and `Pinned{SVector{3, Float64}}` are one type at nominal, so the root input type is unambiguous while the entries disagree about partials.",
 "`SVector{3, Float64}` and `Pinned{SVector{3, Float64}}` are one type at nominal. The root input type is therefore unambiguous while the entries disagree about partials.", "F", {}),
("That mixture is a legitimate model rather than a mistake.", None, "F", {}),
("A command consumed by a promoting aerodynamics leaf and by an AD-opaque table is the FFI door in use.", None, "F", {}),
("Why. The direction of the meet is forced by embedding.", "The direction of the meet is forced by embedding.", "F", {}),
("A pinned root-input cell feeds an unpinned entry lawfully, because frozen values embed upward as zero-partial constants (§9.5).", None, "F", {}),
("A `Dual`-carrying cell arriving at a `Pinned` entry is precisely what that entry forbids.", None, "F", {}),
("The meet is therefore the only assignment satisfying every consumer at once.", None, "F", {}),
("It mirrors the walk-compatibility clause (§6.1) on the producer side.", None, "F", {}),
("What the mixture costs is stated where it is paid.", None, "F", {}),
("Such a root input is unseedable, and a tap selecting it is rejected naming the pinning consumer rather than the face alone (§14.10).",
 "Such a root input is unseedable. A tap selecting it is rejected naming the pinning consumer rather than the face alone (§14.10, D-168).", "C", {"newcites": ["§14.10", "D-168"]}),
("Any component may be the root of a build, and the model's root inputs are the root's own input faces (D-208).", None, "M", {}),
("For an assembly those are the faces declared through `u_connections`, each traced through the face chain (§6.1, §11.3) to the leaf entries consuming it.",
 "For an assembly (a component of pure composition) those are the faces declared through `u_connections`, each traced through the face chain (§6.1, §11.3) to the leaf entries consuming it.", "M", {}),
("For a primitive they are its `u_types` keys directly, because a leaf's faces are its own port names (§8.6).", None, "M", {}),
("Each is then its own consuming entry.", None, "M", {}),
("The type derivation is one rule across both cases, the tight bound at the ultimate consuming entry, above.", None, "M", {}),
("At the root the two contract declarations share one face namespace, so a key declared in both is a build error (§8.6).",
 "At the root the two contract declarations share one face namespace, so a key declared in both is a build error (§8.6, D-210).", "M", {"newcites": ["§8.6", "D-210"]}),
("Abstract-at-root is what the uniform doctrine does not relax.", "The uniform root doctrine below does not relax it (D-208).", "M", {"newcites": ["D-208"]}),
("A leaf declaring an abstract entry (`terrain = AbstractTerrainField`) still cannot be built bare, because a root input must resolve to a concrete declaration.", None, "M", {}),
("The component test rig (§13.7) is the idiom for that case.",
 "The component test rig (a one-child wrapper exporting its child's whole input face set, §13.7) is the idiom for that case.", "M", {}),
("It satisfies the entry with a stub child inside the rig.", "It satisfies the entry with a stub child inside the rig (D-120).", "M", {"newcites": ["D-120"]}),
]
ADDED = [
 "A face is the name a port (one declared input or output) wears on its component's boundary.",
 "the root component's own input face, produced by no component",
 "the build's checking evaluation of a user function",
 "`Pinned` records that a leaf carries no partials, not that an implementation cannot take them (D-266).",
 "An AD-opaque implementation that must participate keeps its entry tolerant and supplies a local derivative rule (§14.10).",
 "A walking producer feeds a pinned entry through the `Freeze` block (§13.7).",
 "D-033 records the rejected names-only contracts.",
 "§6.1 names the bound check's kind too, and gives the remedies this violation's message carries.",
 "the instants a discrete component runs",
 "It escapes two other readings.",
 "The log rejects both (D-054, D-078).",
 "#### Root inputs",
 "Staging cells hold each device's pending writes, and the trace header is the trace's fixed preamble.",
 "a component of pure composition",
 "a one-child wrapper exporting its child's whole input face set",
]
import re
CITE = re.compile(r'§\d+(?:\.\d+)?|D-\d{3}|Appendix [A-D]')
out = []
for i, (o, n, tag, ex) in enumerate(C, 1):
    d = {"id": f"B2-{i:03d}", "old": o, "new": n if n is not None else o,
         "where": ex.get("where", "new"), "cites": sorted(set(CITE.findall(o)))}
    if "newcites" in ex: d["newcites"] = ex["newcites"]
    d["tag"] = tag
    if "ruling" in ex: d["ruling"] = ex["ruling"]
    out.append(d)
json.dump({"claims": out, "added": ADDED}, open(os.path.join(H, "inventory.json"), "w"), indent=1, ensure_ascii=False)
