"""Builds inventory.json for unit D. Run from docs/spec_rewrite/ch10/units/D."""
import json, re

CITE = re.compile(r'§\d+(?:\.\d+)?|D-\d{3}|Appendix [A-D]')
A = "units/A/old.md"
LOG = "docs/design/decisions.md"

# (old, new, tag, extra) ; extra may hold where, ruling, newcites
C = [
 # M4 paragraph, moved from §10.4 to the end of "The firing budget"
 ("The same doctrine governs §10.6.", "The doctrine of §10.4 governs both budgets.", "M", {"newcites": ["§10.4"]}),
 ("Neither the boundary iteration nor cross-frame re-localization has a structural bound, so each takes a budget.",
  "Neither the boundary iteration nor re-localization within the frame has a structural bound, so each takes a budget.", "R", {"ruling": "R8 (F5)"}),
 ("The boundary iteration takes `firing_budget`, and re-localization takes `localization_budget`.",
  "The boundary iteration takes `firing_budget`, per event per boundary, and re-localization takes `localization_budget`, per frame.", "F", {}),
 ("Both degrade loudly rather than erroring, under a warning that names the offending event.",
  "Both degrade loudly rather than erroring, under a warning that names the offending event.", "F", {}),
 ("They differ only in what exhaustion sheds.", "They differ only in what exhaustion sheds.", "F", {}),
 ("Localization sheds root-finding precision and preserves every firing at boundary granularity.",
  "Localization sheds root-finding precision and preserves every firing at boundary granularity.", "F", {}),
 ("The firing budget sheds firings, which is exactly what bounds the iteration.",
  "The firing budget sheds firings, which is exactly what bounds the iteration.", "F", {}),
 # heading and context
 ("### 10.6 Event iteration at boundaries: to quiescence, budgeted", "### 10.6 Event iteration at boundaries: to quiescence, budgeted", "X", {}),
 ("§5.3 leaves two questions open.", "§5.3 leaves two questions open.", "X", {}),
 ("How far does the event phase run at a boundary,", "How far does the event phase run at a boundary", "X", {}),
 ("and how often may each event fire while it does?", "and how often may each event fire while it does?", "X", {}),
 ("This section answers both.", "This section answers both.", "X", {}),
 ("The phase iterates.", "The phase iterates (D-020).", "C", {"newcites": ["D-020"]}),
 ("One round re-runs the boundary sweep, evaluates all guards against it, and fires the eligible events,",
  "One round re-runs the boundary sweep", "F", {}),
 ("at most one per component.", "A component fires at most one event per round (D-154).", "C", {"newcites": ["D-154"]}),
 ("Each firing is `handler → x_projection`.", "Each firing is `handler → x_projection`.", "F", {}),
 ("Rounds continue to quiescence, the fixed point where a round of handlers fires nothing.",
  "Rounds continue to quiescence, the fixed point where a round of handlers fires nothing.", "F", {}),
 # the rule
 ("Rule. An event fires in an iteration round if and only if three conditions hold.",
  "An event fires in an iteration round if and only if three conditions hold (D-181):", "C", {"newcites": ["D-181"]}),
 ("Its predicate is observed holding in that round.", "- Its predicate is observed holding in that round.", "F", {}),
 ("The sample observed before it was not-holding.", "- The sample observed before it was not-holding.", "F", {}),
 ("And the event's firing count for this boundary is below `firing_budget`.",
  "- The event's firing count for this boundary is below `firing_budget`.", "F", {}),
 ("That is the whole definition of \"newly fired\".", "That is the whole definition of \"newly fired\".", "F", {}),
 ("The predicate is the one §2.1 defines, either the `Bool` form true or `σ ≥ 0`.",
  "The predicate is the one §2.1 defines, either the `Bool` form true or `σ ≥ 0`.", "F", {}),
 ("`firing_budget` is a deployment keyword, an integer ≥ 1 defaulting to 4.",
  "`firing_budget` is a deployment keyword, an integer ≥ 1 defaulting to 4.", "F", {}),
 ("It caps how many times each declared event may fire at one boundary.",
  "It caps how many times each declared event may fire at one boundary.", "F", {}),
 # registers
 ("Three registers per event decide the rule, all named normatively.",
  "Three registers per event decide the rule, all named normatively.", "F", {}),
 ("- The prior is the previous boundary's quiescent sample.", "- The prior is the previous boundary's quiescent sample.", "F", {}),
 ("The boundary's first round tests against it.", "The boundary's first round tests against it.", "F", {}),
 ("- The last-observed sample is initialized from the prior when the boundary opens and overwritten by every round's evaluation.",
  "- The last-observed sample is initialized from the prior when the boundary opens and overwritten by every round's evaluation.", "F", {}),
 ("Every later round tests against it.", "Every later round tests against it.", "F", {}),
 ("There is one exception.", "There is one exception.", "F", {}),
 ("An event that was eligible but blocked (below) keeps its sample, because blocking defers its edge rather than consuming it.",
  "An event that was eligible but blocked (below) keeps its sample, because blocking defers its edge rather than consuming it.", "F", {}),
 ("- The firing count for the boundary is incremented at each firing and reset when the boundary ends.",
  "- The firing count for the boundary is incremented at each firing and reset when the boundary ends.", "F", {}),
 ("Eligibility inside a boundary is therefore an edge like any other.",
  "Eligibility inside a boundary is therefore an edge like any other.", "F", {}),
 ("It is a not-holding → holding transition, never a bare sign change.",
  "It is a not-holding → holding transition, never a bare sign change.", "F", {}),
 ("What differs is the reference sample.", "What differs is the reference sample.", "F", {}),
 ("The edge is read against the last-observed sample, not against the prior the boundary entered with.",
  "The edge is read against the last-observed sample, not against the prior the boundary entered with (D-181).", "C", {"newcites": ["D-181"]}),
 ("Two consequences follow.", "Two consequences follow.", "X", {}),
 ("Sticky predicates need no special case.", "Sticky predicates need no special case.", "F", {}),
 ("An event that fires and keeps holding presents no further not-holding → holding edge, so it fires once, at the boundary where it first held.",
  "An event that fires and keeps holding presents no further not-holding → holding edge, so it fires once, at the boundary where it first held.", "F", {}),
 ("And a predicate that is genuinely falsified and re-enabled inside the boundary, because another handler's cascade reverted its effect, fires again at this boundary against a fresh sweep (D-181).",
  "And a predicate that is genuinely falsified and re-enabled inside the boundary, because another handler's cascade reverted its effect, fires again at this boundary against a fresh sweep (D-181).", "F", {}),
 ("One boundary's iteration, sketched:", "The sketch below shows one boundary's iteration.", "X", {}),
 ("`# entering the boundary, per event: last ← prior, count ← 0 while the previous round fired something # the first round always runs boundary sweep # the whole boundary sweep, due set fixed for the boundary per event: eligible ← last not-holding && now holding && count < firing_budget per component: firing ← its first eligible event, in declaration order per event: last ← now, unless eligible and not firing # a blocked edge stays unconsumed fire the firing events # handler → x_projection, count += 1 end # the exit condition is quiescence per event: prior ← last # the settled boundary's honest sample`",
  "`# entering the boundary, per event: last ← prior, count ← 0 while the previous round fired something # the first round always runs boundary sweep # the whole boundary sweep, due set fixed for the boundary per event: eligible ← last not-holding && now holding && count < firing_budget per component: firing ← its first eligible event, in declaration order per event: last ← now, unless eligible and not firing # a blocked edge stays unconsumed fire the firing events # handler → x_projection, count += 1 end # the exit condition is quiescence per event: prior ← last # the settled boundary's honest sample`", "F", {}),
 ("The prior is updated at each boundary's quiescence, from the final post-iteration samples.",
  "The prior is updated at each boundary's quiescence, from the final post-iteration samples (D-082).", "C", {"newcites": ["D-082"]}),
 ("The update is unconditional.", "The update is unconditional.", "F", {}),
 ("Every prior is therefore an honest observation of a settled boundary.", "Every prior is therefore an honest observation of a settled boundary.", "F", {}),
 ("That is what makes the θ = 0 discriminator (§10.4) conclusive.", "That is what makes the θ = 0 discriminator (§10.4) conclusive.", "F", {}),
 ("The frame-top drain is the only possible source of disagreement between the prior and the left-end trial evaluation.",
  "is the only possible source of disagreement between the prior and the left-end trial evaluation.", "F", {}),
 ("All three registers are detection bookkeeping, not model memory.", "All three registers are detection bookkeeping, not model memory.", "F", {}),
 ("They are correctly absent from every state store.", "They are correctly absent from every state store (D-082).", "C", {"newcites": ["D-082"]}),
 ("They are not traced, and they are reconstructed deterministically.",
  "The trace header is such a checkpoint. `restore!` copies a checkpoint's prior back (D-274). The other two registers are reset on entering each boundary, as the sketch shows.",
  "R", {"ruling": "R8 (F8)", "newcites": ["D-274"]}),
 ("A checkpoint (the executor's state at a frame top, as one value) carries the prior, the one register that crosses a boundary (§12.6, D-274).",
  "A checkpoint (the executor's state at a frame top, as one value) carries the prior, the one register that crosses a boundary (§12.6, D-274).", "F", {}),
 ("Beyond the prior, the cost is one `Bool` and one small counter per event.",
  "Beyond the prior, the cost is one `Bool` and one small counter per event.", "F", {}),
 ("Boundary zero sets every prior to not-holding.", "Boundary zero sets every prior to not-holding (D-082).", "C", {"newcites": ["D-082"]}),
 ("A predicate already holding in the authored state therefore fires at `t₀`.",
  "A predicate already holding in the authored state therefore fires at `t₀`.", "F", {}),
 ("That behavior (§14.5) is derived rather than asserted.", "That behavior (§14.5) is derived rather than asserted.", "F", {}),
 ("A re-run from a condition resets all three registers from scratch, because `init!` re-runs boundary zero (§14.5).",
  "A re-run from a condition resets all three registers from scratch, because `init!` re-runs boundary zero (§14.5).", "F", {}),
 ("Predicates holding in the newly applied state fire again at the new `t₀`.",
  "Predicates holding in the newly applied state fire again at the new `t₀`.", "F", {}),
 ("A `restore!` keeps the checkpoint's priors and runs no boundary zero, so nothing holding re-fires (§12.6).",
  "A `restore!` keeps the checkpoint's priors and runs no boundary zero, so nothing holding re-fires (§12.6, D-274).", "C", {"newcites": ["§12.6", "D-274"]}),
 # why iterate (M9)
 ("Why iterate.", "#### Why the phase iterates", "X", {}),
 ("Under a single pass, a cascade of N logically simultaneous transitions (supervisor FSM → subordinate FSM → …) takes N steps to complete, at latency N·h.",
  "Under a single pass, a cascade of N logically simultaneous transitions (supervisor FSM → subordinate FSM → …) takes N steps to complete, at latency N·h.", "F", {}),
 ("Model semantics would then depend on the integrator's step size, and `h` is an execution parameter.",
  "Model semantics would then depend on the integrator's step size, and `h` is an execution parameter.", "F", {}),
 ("This is the same class of footgun §2.2 cited when killing `f_step!`.",
  "This is the same class of footgun §2.2 cited when killing `f_step!`, an unconditional per-step hook (D-020).", "R",
  {"ruling": "R8 (F9)", "newcites": ["§2.2", "D-020"]}),
 ("Cascades are not a corner case either.", "Cascades are not a corner case either.", "F", {}),
 ("Externalized FSM components are blessed (§3.1), which makes cross-component cascades the expected idiom.",
  "Externalized FSM components are blessed (§3.1), which makes cross-component cascades the expected idiom.", "F", {}),
 ("Established practice agrees.", "Established practice agrees.", "F", {}),
 ("Hybrid automata take sequences of instantaneous transitions at one time point,",
  "Hybrid automata take sequences of instantaneous transitions at one time point.", "F", {}),
 ("Modelica iterates events to quiescence,", "Modelica iterates events to quiescence.", "F", {}),
 ("and Stateflow runs charts to completion within a tick.", "Stateflow runs charts to completion within a tick", "F", {}),
 ("Boundary-detection timing remains h-dependent, but that is a different quantity.",
  "Boundary-detection timing remains h-dependent, but that is a different quantity.", "F", {}),
 ("It is the resolution at which a physical crossing is noticed.", "It is the resolution at which a physical crossing is noticed.", "F", {}),
 ("The cascade delay would have been structure the framework inserts between transitions the model declares simultaneous.",
  "The cascade delay would have been structure the framework inserts between transitions the model declares simultaneous.", "F", {}),
 # within a round
 ("Why a full re-sweep per round.", "The reason is that", "X", {}),
 ("A transition reaches the signal table only through a sweep.", "a transition reaches the signal table", "F", {}),
 ("A handler writes its component's state stores and nothing else.", "A handler writes its component's state stores and nothing else.", "F", {}),
 ("So neither the transitioning component's own ports nor the downstream stage-2 chains that read them have moved.",
  "nor the downstream stage-2 chains that read them have moved.", "F", {}),
 ("A round therefore re-runs the whole boundary sweep, gated entries included.",
  "Each round re-runs the whole boundary sweep, gated entries included (D-020).", "C", {"newcites": ["D-020"]}),
 ("The cost is noise.", "The cost is negligible.", "F", {}),
 ("Sweeps take microseconds, and rounds beyond the first require an actual cascade.",
  "Sweeps take microseconds, and rounds beyond the first require an actual cascade.", "F", {}),
 ("Within a round, the signal table has a single writer, and it is the sweep.",
  "Within a round, the signal table has a single writer, and it is the sweep (D-154).", "C", {"newcites": ["D-154"]}),
 ("A handler writes nothing to the table.", "A handler writes nothing to the table.", "F", {}),
 ("It returns transitions, the framework latches them into the component's state stores, and `x_projection` normalizes them.",
  "It returns transitions, the framework latches them into the component's state stores, and `x_projection` normalizes them.", "F", {}),
 ("Nothing moves the table mid-round.", "Nothing moves the table mid-round.", "F", {}),
 ("This gives the epoch rule, which is the core of this section.", "This gives the epoch rule, which is the core of this section.", "R", {"ruling": "R4"}),
 ("A handler executes against exactly the world its guard fired on.",
  "A handler executes against exactly the world its guard fired on (D-154).", "C", {"newcites": ["D-154"]}),
 ("Its own `y`, foreign `u` and its own `x`/`m` all come from the firing round's sweep, so `y = h(x)` holds at every handler entry.",
  "Its own `y`, foreign `u` and its own `x`/`m` all come from the firing round's sweep, so `y = h(x)` holds at every handler entry.", "F", {}),
 ("No bundle (the NamedTuple of zero-copy views a component function receives) ever straddles two epochs.",
  "No bundle (the NamedTuple of zero-copy views a component function receives) ever straddles two epochs.", "F", {}),
 ("Serialization is what delivers this.", "Serialization is what delivers this.", "F", {}),
 ("A component's state stores are written only by its own handlers, and it fires at most one event per round, so no same-round writer precedes any handler's entry.",
  "A component's state stores are written only by its own handlers, and it fires at most one event per round, so no same-round writer precedes any handler's entry.", "F", {}),
 ("A component's other eligible events are blocked, not lost.",
  "A component's other eligible events are blocked, not lost (D-191).", "C", {"newcites": ["D-191"]}),
 ("Each is re-decided in the next round, against the post-transition sweep.",
  "Each is re-decided in the next round, against the post-transition sweep (D-154).", "C", {"newcites": ["D-154"]}),
 ("Declaration order is therefore a priority with re-decision, not a simultaneity.",
  "Declaration order is therefore a priority with re-decision, not a simultaneity.", "F", {}),
 ("An event whose premise the earlier transition falsified simply does not fire.",
  "An event whose premise the earlier transition falsified simply does not fire.", "F", {}),
 ("Under a within-round sequence it would have fired on the stale premise.",
  "Under a within-round sequence it would have fired on the stale premise.", "F", {}),
 ("Blocking is visible in the registers (D-191).", "Blocking is visible in the registers (D-191).", "F", {}),
 ("An eligible-but-blocked event is the one case whose last-observed sample is not overwritten, so the edge it presented stands unconsumed.",
  "An eligible-but-blocked event is the one case whose last-observed sample is not overwritten, so the edge it presented stands unconsumed.", "F", {}),
 ("A guard that keeps holding therefore fires in the next round on that same edge.",
  "A guard that keeps holding therefore fires in the next round on that same edge.", "F", {}),
 ("One that the transition falsified records not-holding as usual, and any later re-rise is a fresh edge.",
  "One that the transition falsified records not-holding as usual, and any later re-rise is a fresh edge.", "F", {}),
 ("The prior stays honest at no cost.", "The prior stays honest at no cost.", "F", {}),
 ("The quiescent round fires nothing, hence blocks nothing, so every sample takes its final update before the prior is written.",
  "The quiescent round fires nothing, hence blocks nothing, so every sample takes its final update before the prior is written.", "F", {}),
 ("Across components, handler order within a round is semantically unobservable.",
  "Across components, handler order within a round is semantically unobservable (D-154).", "C", {"newcites": ["D-154"]}),
 ("The reason is stronger than serialization.", "The reason is stronger than serialization.", "F", {}),
 ("There is no delivering mechanism at all.", "There is no delivering mechanism at all.", "F", {}),
 ("Nothing writes the table mid-round, so there is nothing for order to observe.",
  "Nothing writes the table mid-round, so there is nothing for order to observe.", "F", {}),
 ("Execution order is fixed all the same, as executor component order and then declaration order within a component.",
  "Execution order is fixed all the same. It follows the component order of the executor (the compiled form of the stage execution order), then declaration order within a component.", "F", {}),
 ("That keeps the §13.4 cursor and the diagnostics stream deterministic.",
  "That keeps the execution cursor (the loop-state field recording where execution stands, §13.4) and the diagnostics stream deterministic.", "F", {}),
 ("No trajectory depends on it.", "No trajectory depends on it.", "F", {}),
 ("The natural single-pass executor is therefore exactly correct.", "The natural single-pass executor is therefore exactly correct.", "F", {}),
 ("It builds each handler's bundle at dispatch, from the live table.", "It builds each handler's bundle at dispatch, from the live table.", "F", {}),
 ("It needs no pre-materialization, no staging pass, no carrier and no shadow table, and it allocates nothing.",
  "It needs no pre-materialization, no staging pass, no carrier and no shadow table, and it allocates nothing.", "F", {}),
 ("The trade, stated openly, is that a handler cannot opt into seeing a same-round foreign transition.",
  "The trade, stated openly, is that a handler cannot opt into seeing a same-round foreign transition (D-100).", "C", {"newcites": ["D-100"]}),
 ("Same-instant sequential coupling across components is a cascade, one round per link, deterministic.",
  "Same-instant sequential coupling across components is a cascade, one round per link, deterministic.", "F", {}),
 ("Coupling tighter than that belongs inside one component, where declaration order gives exact sequencing across rounds.",
  "Coupling tighter than that belongs inside one component, where declaration order gives exact sequencing across rounds.", "F", {}),
 ("This is the position of the synchronous languages.", "This is the position of the synchronous languages.", "F", {}),
 ("A micro-step sees the pre-state, and effects appear at the next micro-step.",
  "A micro-step sees the pre-state, and effects appear at the next micro-step.", "F", {}),
 ("Serializing same-component firings costs one extra intra-boundary sweep per event so serialized, which is microseconds on the rare boundary that fires at all.",
  "Serializing same-component firings costs one extra intra-boundary sweep per event so serialized, which is microseconds on the rare boundary that fires at all.", "F", {}),
 ("D-154 records the rejected shapes.", "D-154 records the rejected shapes.", "R", {"ruling": "R3"}),
 ("They are the per-event re-decode with a frozen round-start `u` (D-016, D-100, D-152),",
  "Per-event re-decode + frozen `u`: D-016/D-100/D-152 as landed", "R", {"ruling": "R3", "where": LOG}),
 ("live-table reads under the canonical execution order,", "Live-table reads under canonical order: §10.6's standing rejection — executor order becomes semantics.", "R", {"ruling": "R3", "where": LOG}),
 ("a table copy per firing round (D-100),", "A table copy per firing round: identical semantics, pays an allocation pre-materialization avoids.", "R", {"ruling": "R3", "where": LOG}),
 ("and handlers stripped of their own `y`.", "Handlers stripped of own `y`: the `h_x`-no-`u` move", "R", {"ruling": "R3", "where": LOG}),
 # the firing budget
 ("Why a per-event budget.", "A per-event firing budget", "X", {}),
 ("A re-enabled event fires at its true boundary, against a fresh sweep.", "lets a re-enabled event fire at its true boundary, against a fresh sweep.", "F", {}),
 ("The deferral design and the per-round cap are both rejected (D-020, D-181).",
  "The deferral design and the per-round cap are both rejected (D-020, D-181).", "F", {}),
 ("Priors stay honest as a consequence.", "Priors stay honest as a consequence.", "F", {}),
 ("Every prior is a sample actually taken, never a value recorded to make a rule work out.",
  "Every prior is a sample actually taken, never a value recorded to make a rule work out.", "F", {}),
 ("Termination is then budget-bounded rather than structural.", "Termination is then budget-bounded rather than structural.", "F", {}),
 ("For `E` declared events, a boundary admits at most `firing_budget · E` firings, hence a bounded number of rounds, deterministically and independently of pace.",
  "For `E` declared events, a boundary admits at most `firing_budget · E` firings, hence a bounded number of rounds, deterministically and independently of pace.", "F", {}),
 ("A livelock, such as two FSMs toggling each other, does not resolve silently.",
  "A livelock, such as two FSMs toggling each other, does not resolve silently.", "F", {}),
 ("Each toggler spends its budget and warns (below), and the run proceeds and replays identically.",
  "Each toggler spends its budget and warns (below), and the run proceeds and replays identically.", "F", {}),
 ("This is degradation, not an error, per the doctrine of §10.4.", "This is degradation, not an error, per the doctrine of §10.4.", "F", {}),
 ("The warning names the actual chatterer, while every other event's iteration continues untouched.",
  "The warning names the actual chatterer, while every other event's iteration continues untouched.", "F", {}),
 ("This trade is also stated openly.", "This trade is also stated openly.", "R", {"ruling": "R3"}),
 ("Because termination is budget-bounded rather than structural, the arbitrary-K objection lives on in `firing_budget`.",
  "Because termination is budget-bounded rather than structural, the arbitrary-K objection (D-020) lives on in `firing_budget`.", "R", {"ruling": "R3", "newcites": ["D-020"]}),
 ("What that buys is the absence of deferral machinery.", "D-181 records what that buys.", "R", {"ruling": "R3", "newcites": ["D-181"]}),
 ("There is no manufactured prior, no re-arm flag, no `EventDeferred` warning,",
  "manufactured-prior exception, re-arm flag and `EventDeferred` retired", "R", {"ruling": "R3", "where": LOG}),
 ("no one-step artifact,", "(no one-step h-artifact)", "R", {"ruling": "R3", "where": LOG}),
 ("and no collapse of several intra-boundary re-arms into a single later firing.",
  "collapses multiple re-arms into one firing.", "R", {"ruling": "R3", "where": LOG}),
 ("Budget exhaustion degrades; it does not throw.", "Budget exhaustion degrades; it does not throw (D-181).", "C", {"newcites": ["D-181"]}),
 ("When an event has fired `firing_budget` times at a boundary, its further edges there are lost for the rest of that boundary.",
  "When an event has fired `firing_budget` times at a boundary, its further edges there are lost for the rest of that boundary.", "F", {}),
 ("The eligibility test skips it while every other event iterates normally.",
  "The eligibility test skips it while every other event iterates normally.", "F", {}),
 ("A lost edge emits a `FiringBudget` warning (§13.2, Appendix C), at most once per event per boundary.",
  "A lost edge emits a `FiringBudget` warning (§13.2, Appendix C), at most once per event per boundary.", "F", {}),
 ("An event that fires its budget out and then quiesces lost nothing and warns nothing.",
  "An event that fires its budget out and then quiesces lost nothing and warns nothing.", "F", {}),
 ("The warning carries the component path, the event name, the boundary time and the exhausted budget beside the boundary's firing count.",
  "The warning carries the component path, the event name, the boundary time and the exhausted budget beside the boundary's firing count.", "F", {}),
 ("The default of 4 is chosen the way §10.4 chooses 8.", "The default of 4 is chosen the way §10.4 chooses the per-frame localization budget's 8.", "F", {}),
 ("A legitimate re-enable is one or two firings deep.", "A legitimate re-enable is one or two firings deep.", "F", {}),
 ("A toggling FSM pair chatters without bound.", "A toggling FSM pair chatters without bound.", "F", {}),
 ("A budget of 4 separates the two without ever binding on a healthy model.",
  "A budget of 4 separates the two without ever binding on a healthy model.", "F", {}),
 ("Like every other degradation here, it depends on the trajectory alone, so the run replays identically.",
  "Like every other degradation here, it depends on the trajectory alone, so the run replays identically.", "F", {}),
 # ticks after quiescence
 ("Ticks stay outside the iteration, after quiescence.", "Ticks stay outside the iteration, after quiescence (D-020).", "C", {"newcites": ["D-020"]}),
 ("The two possible couplings resolve asymmetrically.", "The two possible couplings resolve asymmetrically.", "F", {}),
 ("- Events → ticks: machinery already in place handles this.", "- From events to ticks, machinery already in place handles the coupling.", "F", {}),
 ("Due discrete components' output stages (`y_state`/`y_direct`) are gated into the boundary sweep against a due set fixed for the whole iteration (§10.5).",
  "Due discrete components' output stages (`y_state`/`y_direct`) are gated into the boundary sweep against a due set fixed for the whole iteration (§10.5).", "F", {}),
 ("Every iteration round therefore refreshes them for free, against the same `s` and post-transition inputs.",
  "Every iteration round therefore refreshes them for free, against the same `s` and post-transition inputs.", "F", {}),
 ("Their `s_update` has not run yet.", "Their `s_update` has not run yet.", "F", {}),
 ("At quiescence, their published outputs reflect the settled boundary instant, which is exactly what \"sampling at t\" should mean for a logically instantaneous cascade.",
  "At quiescence, their published outputs reflect the settled boundary instant, which is exactly what \"sampling at t\" should mean for a logically instantaneous cascade.", "F", {}),
 ("Earlier rounds' tentative values are internal scratch, like RK stage evaluations.",
  "Earlier rounds' tentative values are internal scratch, like RK stage evaluations.", "F", {}),
 ("§10.3 extends naturally.", "§10.3 extends naturally.", "M", {"where": A}),
 ("External readers observe the table only after the boundary sequence completes.",
  "External readers observe the table only after the boundary sequence completes.", "M", {"where": A}),
 ("- Ticks → events: structurally impossible.", "- From ticks to events, a coupling is structurally impossible.", "F", {}),
 ("A tick's output stages contribute nothing guards have not already seen, since they run inside the sweep, from current `s`.",
  "A tick's output stages contribute nothing guards have not already seen, since they run inside the sweep, from current `s`.", "F", {}),
 ("Its `s_update` writes `s⁺` after the sweep, and `s⁺` is first decoded at the owner's next tick.",
  "Its `s_update` writes `s⁺` after the sweep, and `s⁺` is first decoded at the owner's next tick.", "F", {}),
 ("So `s⁺` is invisible to every reader within the boundary.", "So `s⁺` is invisible to every reader within the boundary.", "F", {}),
 ("This is the standard one-sample `z⁻¹` delay of sampled-data control, enforced here by construction.",
  "This is the standard one-sample `z⁻¹` delay of sampled-data control, enforced here by construction.", "F", {}),
 ("Nothing that happens after quiescence can flip a guard, so there is no combined event/tick fixed point to iterate.",
  "Nothing that happens after quiescence can flip a guard, so there is no combined event/tick fixed point to iterate.", "F", {}),
 ("The boundary macro-sequence, in its final form.", "The boundary macro-sequence, in its final form, is the following.", "X", {}),
 ("Boundary zero, the initialization boundary,", "Boundary zero is the initialization boundary.", "F", {}),
 ("is the same sequence with an empty integrate (§14.5).", "Boundary zero is the same sequence with an empty integrate (§14.5, D-067).", "C",
  {"newcites": ["§14.5", "D-067"]}),
 ("> integrate → project → [sweep → guards → handlers] iterated to quiescence > (under the firing budget) → all due `s_update` calls → logging / I/O staging.",
  "> integrate → project → [sweep → guards → handlers] iterated to quiescence > (under the firing budget) → all due `s_update` calls → logging / I/O staging.", "F", {}),
 ("The sequence decides the mixed case, where a continuous component's handler and its discrete observers' ticks land on one boundary.",
  "and its discrete observers' ticks land on one boundary.", "F", {}),
 ("Take an engine's `starting → running` transition under a 50 Hz FCS.", "Take an engine's `starting → running` transition under a 50 Hz FCS.", "F", {}),
 ("The transition fires in the iteration segment.", "The transition fires in the iteration segment.", "F", {}),
 ("The re-sweep re-runs the FCS's stages against `running`-mode ports, and its `s_update` then runs from post-transition values.",
  "The re-sweep re-runs the FCS's stages against `running`-mode ports, and its `s_update` then runs from post-transition values.", "F", {}),
]

ADDED = [
 "(a published consistency point, where the macro-sequence completes)",
 "(the pass over the full execution order, with due discrete entries gated in), evaluates all guards (the declared functions defining each event's predicate) against it, and fires the eligible events.",
 "(an instant at which a discrete component's stages and update run).",
 "#### The three registers",
 "The frame-top drain (the swap that publishes staged device writes into the root inputs)",
 "#### What a handler sees within a round",
 "(the framework-owned cells holding every produced signal) only through a sweep.",
 "So neither the transitioning component's own ports (each one declared name with its cell)",
 "An epoch here is the world one round's sweep produces, so no bundle mixes values from two rounds' sweeps. It is not the input epoch of §10.4.",
 "#### The firing budget",
 "(the rule bounding how often each event fires at one boundary)",
 "#### Ticks after quiescence",
 "§10.3 states when external readers may observe the table.",
 "The sequence decides the mixed case, where the handler of a continuous component (the hybrid primitive, with continuous state, modes and events)",
 "The engine is a continuous component, and the FCS (the flight control system) is a discrete component that observes it.",
]

claims = []
for i, (old, new, tag, ex) in enumerate(C, 1):
    c = {"id": f"D-{i:03d}", "old": old, "new": new, "where": ex.get("where", "new"),
         "cites": sorted(set(CITE.findall(old)))}
    if "newcites" in ex:
        c["newcites"] = ex["newcites"]
    c["tag"] = tag
    if "ruling" in ex:
        c["ruling"] = ex["ruling"]
    claims.append(c)
json.dump({"claims": claims, "added": ADDED}, open("inventory.json", "w"), ensure_ascii=False, indent=1)
print(len(claims), "claims")
