"""Builds units/A/inventory.json. Run from docs/spec_rewrite."""
import json
C = "units/A/companion_addition.md"
LOG = "docs/design/decisions.md"
# (old, new, where, cites, newcites or None, tag, ruling or None)
rows = [
("## 10. Time and execution", "## 10. Time and execution", "new", [], None, "X", None),
("### 10.1 Loop ownership: the framework owns the simulation loop", "### 10.1 Loop ownership: the framework owns the simulation loop", "new", [], None, "X", None),
("The simulation loop consists of six activities: the §5.3 boundary sequence, tick dispatch, event handling, logging, input staging, and pacing",
 "The loop consists of six activities. They are the boundary sequence (§5.3), tick dispatch, event handling, logging, input staging, and pacing", "new", ["§5.3"], None, "F", None),
("(waits inserted between completed frames, never altering the boundary sequence).", "(waits inserted between completed frames, never altering the boundary sequence).", "new", [], None, "F", None),
("Rule. All six are framework code, unconditionally.", "All six are framework code, unconditionally (D-017).", "new", [], ["D-017"], "C", None),
("The framework writes the loop itself.", "The framework writes the loop itself.", "new", [], None, "F", None),
("It does not assemble the loop out of callbacks registered with a third-party solver.", "It does not assemble the loop out of callbacks registered with a third-party solver.", "new", [], None, "F", None),
("Why. The step-boundary contract is the central invariant of this design.", "The reason is the step-boundary contract (§10.6), the central invariant of this design.", "new", [], ["§10.6"], "F", None),
("Only a loop the framework owns can enforce that contract by construction rather than by convention.", "Only a loop the framework owns can enforce that contract by construction rather than by convention.", "new", [], None, "F", None),
("Choreographing the same sequence as an ordered `CallbackSet` inside a foreign event loop is rejected on exactly that ground (D-017).",
 "`OrdinaryDiffEq` as substrate with `CallbackSet` choreography: semantics by convention in a foreign event loop", LOG, ["D-017"], None, "R", "R3"),
("`OrdinaryDiffEq` is therefore dropped as a dependency of the new core (D-017).", "`OrdinaryDiffEq` is dropped as a dependency of the new core (D-017).", "new", ["D-017"], None, "F", None),
("### 10.2 The stepper seam", "### 10.2 The stepper seam", "new", [], None, "X", None),
("Loop ownership stops at one operation: advance the continuous state from `t` by `h`.", "Loop ownership stops at one operation. That operation advances the continuous state from `t` by `h`.", "new", [], None, "F", None),
("The framework delegates that operation across a narrow internal interface, the stepper seam.", "The framework delegates that operation across a narrow internal interface, the stepper seam (D-017).", "new", [], ["D-017"], "C", None),
("The seam exists so that the integration method can be replaced without the loop changing.", "The seam exists so that the integration method can be replaced without the loop changing.", "new", [], None, "F", None),
("#### What the seam requires of a backend", "#### What the seam requires of a backend", "new", [], None, "X", None),
("The seam contract has three clauses.", "The seam contract has four clauses.", "new", [], None, "R", "R6"),
("- Advance by arbitrary `h`.", "- The backend advances by arbitrary `h`.", "new", [], None, "F", None),
("The loop needs this anyway.", "The loop needs this anyway.", "new", [], None, "F", None),
("It lands on tick boundaries, and it resumes from a localized event time (the crossing instant bracketed by root-finding over trial sweeps).", "It lands on tick boundaries, and it resumes from a localized event time (the crossing instant bracketed by root-finding over trial sweeps).", "new", [], None, "F", None),
("- Dense output on demand over the last completed step.", "- The backend provides dense output on demand over the last completed step.", "new", [], None, "F", None),
("Only event localization needs it (§10.4), so the backend constructs it lazily.", "Only event localization needs it (§10.4), so the backend constructs it lazily.", "new", ["§10.4"], None, "F", None),
("- One-step methods only.", "- The backend uses one-step methods only.", "new", [], None, "F", None),
("Event handlers reset state discontinuously, and a one-step method restarts from a new state for free.", "Event handlers reset state discontinuously, and a one-step method restarts from a new state for free.", "new", [], None, "F", None),
("Multistep methods are excluded (D-017).", "Multistep methods are excluded (D-017).", "new", ["D-017"], None, "F", None),
("#### Models with no continuous state", "#### Models with no continuous state", "new", [], None, "X", None),
("A model with no continuous state at all is legal.", "A model with no continuous state at all is legal (D-156).", "new", [], ["D-156"], "C", None),
("Nothing in §8.2 requires an `x` block of any component.", "Nothing in §8.2 requires an `x` block of any component.", "new", ["§8.2"], None, "F", None),
("Such a model still has to be run.", "Such a model still has to be run.", "new", [], None, "F", None),
("The seam is never entered empty.", "The seam is never entered empty (D-156).", "new", [], ["D-156"], "C", None),
("The framework short-circuits this case rather than pushing it down the seam.", "The framework short-circuits this case rather than pushing it down the seam.", "new", [], None, "F", None),
("With an empty `x`, the integrate step degenerates to advancing `t` to the next boundary, and the stepper is not called.", "With an empty `x`, the integrate step degenerates to advancing `t` to the next boundary, and the stepper is not called.", "new", [], None, "F", None),
("No backend ever faces `N = 0`, and no backend contract has to say what it would do there.", "No backend ever faces `N = 0`, and no backend contract has to say what it would do there.", "new", [], None, "F", None),
("The ownership rule of §10.1 pays off structurally here.", "The loop-ownership rule (§10.1) pays off structurally here.", "new", ["§10.1"], None, "F", None),
("Under a foreign solver loop, an empty state pays a dummy-`[0.0]` tax (D-017).", "Under a foreign solver loop, an empty state pays a dummy-`[0.0]` tax (D-017).", "new", ["D-017"], None, "F", None),
("Here that tax is gone at the root.", "Here that tax is gone at the root.", "new", [], None, "F", None),
("Not only the buffer disappears, but also the step over it.", "Both the buffer (the contiguous vector backing all continuous state) and the step over it disappear.", "new", [], None, "F", None),
("Everything else about such a model is ordinary.", "Everything else about such a model is ordinary.", "new", [], None, "F", None),
("The boundary machinery of sweeps, events and ticks runs unchanged.", "The boundary machinery of sweeps, events and ticks runs unchanged.", "new", [], None, "F", None),
("#### The first-cut backends", "#### The first-cut backends", "new", [], None, "X", None),
("The first cut ships in-house fixed-step RK4 and Heun over the flat state buffer.", "The first cut ships in-house fixed-step RK4 and Heun over the flat state buffer (D-017).", "new", [], ["D-017"], "C", None),
("Together they are about a hundred lines.", "Together they are about a hundred lines.", "new", [], None, "F", None),
("They are trivially zero-allocation, so they can be audited against the CI invariant of §7.5,", "They are trivially zero-allocation, so they can be audited against the CI invariant (§7.5).", "new", ["§7.5"], None, "F", None),
("and they are trivially `T`-generic.", "They are also trivially `T`-generic.", "new", [], None, "F", None),
("Genericity is not even required of the stepper, because linearization and the tracer drive the sweep, never the integrator.",
 "Genericity is not even required of the stepper, because linearization and the feedthrough tracer (the instrument that classifies a rejected cycle as real or artificial, §5.6) drive the sweep, never the integrator.", "new", [], ["§5.6"], "R", "R8 (F13)"),
("Of the two, `RK4` is the default.", "`RK4` is the default of the two (D-227).", "new", [], ["D-227"], "C", None),
("The `algorithm` keyword selects the backend by type on the `Deployment` (the scalar-free artifact the grid parameters fix),",
 "The `algorithm` keyword selects the backend by type on the `Deployment` (the scalar-free artifact the grid parameters fix).", "new", [], None, "F", None),
("and materialization at `Simulation` construction binds the stepper against the state buffer, on the executor (Appendix B, §9.2, D-227).",
 "Materialization at `Simulation` construction binds the stepper against the state buffer, on the executor (Appendix B, §9.2, D-227).", "new", ["Appendix B", "§9.2", "D-227"], None, "F", None),
("The step `h` has no default and is required of the caller.", "The step `h` has no default and is required of the caller.", "new", [], None, "F", None),
("A domain rate is not a framework default.", "A domain rate is not a framework default.", "new", [], None, "F", None),
("An `OrdinaryDiffEq`-backed stepper can exist later as a package extension, if an offline study genuinely demands adaptive or stiff methods.",
 "An `OrdinaryDiffEq`-backed stepper can exist later as a package extension, if an offline study genuinely demands adaptive or stiff methods (D-017).", "new", [], ["D-017"], "C", None),
("Per the guarded-additions rule it is not built until then.", "It is a guarded addition (a capability the design admits but does not build), so it is not built until then.", "new", [], None, "F", None),
("#### Why fixed-step low-order suffices", "#### The case for fixed-step low order", "new", [], None, "X", None),
("The domain argument is recorded here because it is decisive for the whole axis.", "The domain argument is recorded here because it is decisive for the whole axis.", "new", [], None, "F", None),
("1. The closed-loop tick cap.", "1. Closed-loop ticks cap the step.", "new", [], None, "R", "R2"),
("Every application beyond bare propagation runs periodic avionics", "Every application beyond bare propagation runs periodic avionics (onboard flight systems)", "new", [], None, "F", None),
("(50 Hz today)", "The periodic avionics of today's applications run at 50 Hz.", C, [], None, "R", "R2"),
("whose commands are zero-order-held signals.", "whose commands are zero-order-held signals.", "new", [], None, "F", None),
("Integrating past a tick with stale commands is wrong, so the integrator must land on every tick boundary regardless of method.", "Integrating past a tick with stale commands is wrong, so the integrator must land on every tick boundary regardless of method.", "new", [], None, "F", None),
("Adaptive and high-order methods pay off exactly when steps can stretch, and the execution model forbids the stretch by construction.", "Adaptive and high-order methods pay off exactly when steps can stretch, and the execution model forbids the stretch by construction.", "new", [], None, "F", None),
("2. A piecewise-smooth RHS starves high order.", "2. A piecewise-smooth RHS (the continuous derivative function) starves high order.", "new", [], None, "R", "R2"),
("Linearly interpolated lookup tables (C¹-kinked at every knot), clamps, friction blends and mode branches deny high-order error estimators and implicit-solver Newton iterations the smoothness they assume.",
 "Linearly interpolated lookup tables (C¹-kinked at every knot), clamps, friction blends and mode branches deny high-order error estimators and implicit-solver Newton iterations the smoothness they assume.", "new", [], None, "F", None),
("RK4 at 50 Hz already puts integration error orders of magnitude below the model uncertainty of a coefficient-table aircraft model.",
 "RK4 at 50 Hz already puts integration error orders of magnitude below the model uncertainty of a coefficient-table aircraft model.", C, [], None, "R", "R2"),
("3. Stiffness has a remedy ladder.", "3. Stiffness has a remedy ladder.", "new", [], None, "R", "R2"),
("The fastest continuous dynamics in the current codebase sit inside RK4's stability region at `h = 0.02`.", "The fastest continuous dynamics in Flight.jl's codebase sit inside RK4's stability region at `h = 0.02`.", C, [], None, "R", "R2"),
("These are actuator poles near 31 rad/s, gear damper decay and friction compensators.", "These are actuator poles near 31 rad/s, gear damper decay and friction compensators.", C, [], None, "R", "R2"),
("The crosswind-landing demo is the empirical proof.", "The crosswind-landing demo, a Flight.jl demo of a landing in a crosswind, is the empirical proof.", C, [], None, "R", "R2"),
("If a future model exceeds that region, the ladder runs in order.", "If a future model exceeds RK4's stability region at the deployed `h`, the ladder runs in order.", "new", [], None, "F", None),
("First shrink `h`,", "First shrink `h`.", "new", [], None, "F", None),
("since the RHS costs microseconds and 500 Hz real-time is unremarkable.", "Shrinking `h` comes first on the ladder, since the RHS costs microseconds and 500 Hz real-time is unremarkable.", C, [], None, "R", "R2 (coordinator fix 2)"),
("Then subcycle the stepper against the tick grid.", "Then subcycle the stepper against the tick grid.", "new", [], None, "F", None),
("Only then reach for an implicit method through the adapter.", "Only then reach for an implicit method through the `OrdinaryDiffEq` extension above.", "new", [], None, "F", None),
("If that day comes, the eltype genericity of §7.2 supplies exact ForwardDiff Jacobians through the sweep for free.", "If that day comes, eltype genericity (§7.2) supplies exact ForwardDiff Jacobians through the sweep for free.", "new", ["§7.2"], None, "F", None),
("### 10.3 Signal-table consistency is a boundary property", "### 10.3 Signal-table consistency is a boundary property", "new", [], None, "X", None),
("During a step, the RK stages evaluate the interior sweep (§10.5) at internal stage states.", "During a step, the RK stages evaluate the interior sweep (the sweep variant over continuous entries only, §10.5) at internal stage states (D-147).", "new", ["§10.5"], ["§10.5", "D-147"], "C", None),
("While they do, the signal table is transiently integrator scratch.", "While they do, the signal table is transiently integrator scratch.", "new", [], None, "F", None),
("The boundary sweep in the §5.3 sequence restores consistency at each accepted boundary.", "The boundary sweep in the §5.3 sequence restores consistency at each accepted boundary.", "new", ["§5.3"], None, "F", None),
("Rule. External readers (GUI, logging, network output) observe the signal table only at step boundaries.", "External readers (GUI, logging, network output) observe the signal table only at step boundaries (D-023).", "new", [], ["D-023"], "C", None),
("Mid-step contents carry no meaning.", "Mid-step contents carry no meaning.", "new", [], None, "F", None),
("This rule binds the periphery (§11).", "This rule binds the periphery (everything outside the loop that exchanges data with it, §11).", "new", ["§11"], None, "F", None),
("Two terms recur throughout, and they mean different things.", "The two units recur throughout the chapter, and they mean different things.", "new", [], None, "R", "R1"),
("- A frame is one grid step `[tₙ, tₙ₊₁]`.", "- A frame is one grid step `[tₙ, tₙ₊₁]`.", "new", [], None, "R", "R1"),
("It is the unit of scheduling.", "It is the unit of scheduling.", "new", [], None, "R", "R1"),
("Three things are keyed to it: the input drain (the frame-top swap that publishes staged device writes into the root inputs, §11.4), pacer deadlines (§10.7) and tick eligibility (§10.5).",
 "Three things are keyed to it, namely the input drain (the frame-top swap that publishes staged device writes into the root inputs, §11.4), pacer deadlines (§10.7) and tick eligibility (§10.5).", "new", ["§11.4", "§10.7", "§10.5"], None, "R", "R1"),
("- A boundary is a published consistency point.", "- A boundary is a published consistency point.", "new", [], None, "R", "R1"),
("The §10.6 macro-sequence completes there and a snapshot goes out.", "The macro-sequence of §10.6 completes there, and a snapshot (the immutable per-boundary publication) goes out.", "new", ["§10.6"], None, "R", "R1"),
("Every grid point is a boundary, but not every boundary is a grid point.", "Every grid point is a boundary, but not every boundary is a grid point.", "new", [], None, "R", "R1"),
("The localized event time `t` is a boundary,", "The localized event time `t` is a boundary", "new", [], None, "R", "R1"),
("and so is boundary zero (the initialization boundary at `t₀`, §14.5).", "Boundary zero (the initialization boundary at `t₀`, §14.5) is a boundary and not a frame top either.", "new", ["§14.5"], None, "R", "R1"),
("Neither is a frame top.", "but not a frame top (D-081).", "new", [], ["D-081"], "R", "R1"),
("§10.3 extends naturally.", "The rule extends naturally to the boundary sequence (§10.6).", "new", ["§10.3"], ["§10.6"], "C", None),
("External readers observe the table only after the boundary sequence completes.", "External readers observe the table only after the boundary sequence completes.", "new", [], None, "M", None),
]
added = [
 "This chapter owns time.",
 "It takes the execution order (§5.3) and the compiled executor (§9.7) as given, and states how the loop runs them through time.",
 "§10.1 covers loop ownership and the loop's two units, the frame and the boundary, §10.2 the stepper seam, §10.3 signal-table consistency, §10.4 localization mechanics, §10.5 multi-rate tick scheduling, §10.6 event iteration at boundaries, and §10.7 real-time pacing.",
 "This section defines the simulation loop's two units, lists its six activities and states who writes the loop.",
 "`t` is an event's crossing instant inside a step, bracketed by root-finding (§10.4).",
 "D-017 records the rejected foreign-loop alternative.",
 "- The seam carries what a backend needs across a frame top through a checkpoint hook, empty for a single-step method.",
 "A checkpoint is the executor's state at a frame top (§12.6, D-274).",
 "It makes three claims.",
 "The Flight.jl evidence behind these claims lives in section 5 of `companions/flight_case_studies.md`.",
]
claims = []
for i, (o, n, w, c, nc, t, r) in enumerate(rows, 1):
    d = {"id": f"A-{i:03d}", "old": o, "new": n, "where": w, "cites": c}
    if nc is not None: d["newcites"] = nc
    d["tag"] = t
    if r: d["ruling"] = r
    claims.append(d)
json.dump({"claims": claims, "added": added}, open("ch10/units/A/inventory.json", "w"), ensure_ascii=False, indent=1)
print(len(claims), "claims")
