import json
# (old, new, cites, newcites or None, tag, ruling or None)
S = "s_init(::Noise) = (rng = UInt64.((0x9e3779b9, 0x243f6a88, 0xb7e15162, 0x6a09e667)),) ws_init(::Noise, ::Type) = (rng = Xoshiro(0, 0, 0, 0),)"
SO = "s_init(::Noise) = (rng = (0x9e3779b9, 0x243f6a88, 0xb7e15162, 0x6a09e667),) ws_init(::Noise, ::Type) = (rng = Xoshiro(0, 0, 0, 0),)"
FN = "function s_update(c::Noise, b) r = b.ws.rng r.s0, r.s1, r.s2, r.s3 = b.s.rng # load the words at entry z = randn(r) (rng = (r.s0, r.s1, r.s2, r.s3),) # snapshot them back end"
rows = [
("### 7.3 Discrete state, modes, and workspace", "### 7.3 Discrete state, modes, and workspace", [], None, "X", None),
("Two homes sit outside the continuous buffer, and the rules they obey are opposites.", "Two homes sit outside the continuous buffer (the contiguous vector backing all continuous state), and the rules they obey are opposites.", [], None, "F", None),
("Discrete state and modes are state in the full sense.", "Discrete state and modes are state in the full sense.", [], None, "F", None),
("They are isbits values that the framework owns and that a checkpoint copies wholesale.", "They are values whose fields are isbits or `Symbol`s. The framework owns them, and a checkpoint copies them wholesale.", [], None, "R", "R8"),
("A workspace is mutable scratch, deliberately not state at all, governed by contract rather than by checks.", "A workspace is mutable scratch, deliberately not state at all, governed by contract rather than by checks.", [], None, "F", None),
("#### Stores: discrete state and modes", "#### Stores: discrete state and modes", [], None, "R", "R7"),
("Rule. Discrete state, a discrete leaf's `s`, and the modes `m` live in typed stores, apart from the buffer that holds `x` (§7.1).", "Discrete state, a discrete leaf's `s`, and the modes `m` live in typed stores, apart from the buffer that holds `x` (§7.1, D-013, D-302).", ["§7.1"], ["§7.1", "D-013", "D-302"], "C", None),
("The framework overwrites an `s` or `m` store when an update or a handler returns a new value.", "The framework overwrites an `s` or `m` store when an update or a handler returns a new value.", [], None, "F", None),
("An `s` or `m` store keeps the same immutable-value discipline as the table's cells, in a separate home.", "An `s` or `m` store keeps the same immutable-value discipline as the table's cells, in a separate home.", [], None, "F", None),
("The vocabulary of §4.1 never counts a store as a cell.", "The vocabulary of §4.1 never counts a store as a cell (D-302).", ["§4.1"], ["§4.1", "D-302"], "C", None),
("The `s` and `m` stores never touch the integrator buffer, and no arithmetic is ever done on them.", "The `s` and `m` stores never touch the integrator buffer, and no arithmetic is ever done on them.", [], None, "F", None),
("Rule. Every field of an `s` or `m` store value is isbits or a `Symbol`.", "Every field of an `s` or `m` store value is isbits or a `Symbol` (D-231).", [], ["D-231"], "R", "R4"),
("Isbits is an immutable value that holds no references, transitively.", "Isbits is an immutable value that holds no references, transitively.", [], None, "F", None),
("Enums, integers, `Bool`s, `SArray`s and nested isbits structs all qualify.", "Enums, integers, `Bool`s, `SArray`s and nested isbits structs all qualify.", [], None, "F", None),
("A `Symbol` is admitted as the idiomatic label.", "A `Symbol` is admitted as the idiomatic label.", [], None, "F", None),
("It is interned, immutable and never freed, so it copies as a pointer to permanent data and serializes as its name.", "It is interned, immutable and never freed, so it copies as a pointer to permanent data and serializes as its name.", [], None, "F", None),
("The table admits it on the same grounds, as an opaque leaf (§4.3).", "The table admits it on the same grounds, as an opaque leaf (§4.3).", ["§4.3"], None, "F", None),
("A `String`, an array, or a struct holding either does not qualify,", "A `String`, an array, or a struct holding either does not qualify.", [], None, "F", None),
("and neither does a struct nesting a `Symbol`.", "A struct nesting a `Symbol` does not qualify.", [], None, "F", None),
("The structure step checks every `s_init` and `m_init` field and reports a violation as `IllegalStoreField` (§9.1, Appendix C, D-231).", "The structure step checks every `s_init` and `m_init` field and reports a violation as `IllegalStoreField` (§9.1, Appendix C, D-231).", ["§9.1", "Appendix C", "D-231"], None, "F", None),
("Why. State is what changes between ticks.", "State is what changes between ticks (the instants a discrete component runs).", [], None, "F", None),
("Bulk data and labels do not, and their home is the component instance.", "Bulk data and labels do not, and their home is the component instance.", [], None, "F", None),
("The frozen-reference latitude signals enjoy (§4.1)", "The frozen-reference latitude stays with signals (§4.1, D-231).", ["§4.1"], ["§4.1", "D-231"], "R", "R4"),
("exists for field handles (§4.4), and no store needs it.", "It exists for field handles (§4.4), and no store needs it.", ["§4.4"], None, "F", None),
("Isbits is what makes the rest of this section literal.", "Isbits is what makes the rest of this section literal.", [], None, "F", None),
("Copying an `s` or `m` store copies bits, so checkpoint and replay of the entire discrete side is \"copy the store values\", and a stored value has one fixed layout per component.", "Copying an `s` or `m` store copies bits. So checkpoint and replay (the ordinary loop re-driven from the trace) of the entire discrete side is \"copy the store values\", and a stored value has one fixed layout per component.", [], None, "F", None),
("#### Double-buffered mutable state (deferred) Double-buffered mutable state is a possible future extension only, deferred (D-013).", "Double-buffered mutable state is a possible future extension only, deferred (D-013).", ["D-013"], None, "R", "R7"),
("#### Workspace", "#### Workspace", [], None, "R", "R7"),
("A workspace serves heavy algorithms, such as an n≈20 Kalman filter.", "A workspace serves heavy algorithms, such as an n≈20 Kalman filter.", [], None, "X", None),
("Rule. A workspace is component-declared mutable scratch, instantiated by the framework.", "A workspace is component-declared mutable scratch, instantiated by the framework (D-013).", [], ["D-013"], "C", None),
("It arrives as the `ws` field of the bundle (the NamedTuple of zero-copy views a component function receives) in every bundle-receiving function of the declaring component (§5.2).", "It arrives as the `ws` field of the bundle (the NamedTuple of zero-copy views a component function receives) in every bundle-receiving function of the declaring component (§5.2).", ["§5.2"], None, "F", None),
("`x_projection` is positional and receives none.", "`x_projection` is positional and receives none (D-074).", [], ["D-074"], "C", None),
("Rule. A workspace is excluded from state semantics.", "A workspace is excluded from state semantics.", [], None, "F", None),
("It is not snapshotted, not replayed and never a condition target (§14.1).", "It is not snapshotted, not replayed and never a condition target (§14.1).", ["§14.1"], None, "F", None),
("It must carry no information between calls.", "It must carry no information between calls (D-183).", [], ["D-183"], "C", None),
("The framework never inspects or mutates a workspace.", "The framework never inspects or mutates a workspace (D-183).", [], ["D-183"], "C", None),
("The workspace is an opaque, opt-in escape hatch from value semantics, used at the author's own risk,", "The workspace is an opaque, opt-in escape hatch from value semantics, used at the author's own risk.", [], None, "F", None),
("and its rules are contract, not checks.", "Its rules are contract, not checks.", [], None, "F", None),
("At call entry, contents are unspecified beyond the structure the allocator itself established.", "At call entry, contents are unspecified beyond the structure the allocator itself established.", [], None, "F", None),
("A plan or factorization configured at allocation is valid from then on.", "A plan or factorization configured at allocation is valid from then on.", [], None, "F", None),
("Scratch is garbage until written this call, and nothing a previous call left behind may be relied upon.", "Scratch is garbage until written this call, and nothing a previous call left behind may be relied upon.", [], None, "F", None),
("No poisoning of scratch is attempted (D-183).", "No poisoning of scratch is attempted.", ["D-183"], ["D-183"], "F", None),
("Declared by allocation.", "A workspace is declared by allocation (D-077).", [], ["D-077"], "C", None),
("The well-known method is the allocator.", "The well-known method is the allocator.", [], None, "F", None),
("`ws_init(c::KF, ::Type{T}) where {T} = (P = Matrix{T}(undef, c.n, c.n), x̂ = Vector{T}(undef, c.n))`", "`ws_init(c::KF, ::Type{T}) where {T} = (P = Matrix{T}(undef, c.n, c.n), x̂ = Vector{T}(undef, c.n))`", [], None, "F", None),
("Rule. `ws_init(::C, ::Type{T})` takes the activation scalar on both tiers, and it is the one declaration that does.", "`ws_init(::C, ::Type{T})` takes the activation scalar on both tiers, and it is the one declaration that does (D-263).", [], ["D-263"], "C", None),
("A discrete allocator receives `Float64` at every activation, because the discrete tier never runs at another scalar (§9.4).", "A discrete allocator receives `Float64` at every activation, because the discrete tier never runs at another scalar (§9.4).", ["§9.4"], None, "F", None),
("`x_init`, `s_init`, `m_init` and the contracts take the component alone on every tier.", "`x_init`, `s_init`, `m_init` and the contract declarations take the component alone on every tier.", [], None, "F", None),
("Why. State and cells re-scalar through the walk (§7.2), so those declarations never need `T`.", "State and cells re-scalar through the walk (§7.2), so those declarations never need `T`.", ["§7.2"], None, "F", None),
("Scratch is allocated, not retyped.", "Scratch is allocated, not retyped.", [], None, "F", None),
("A factorization, a plan or a buffer sized by the scalar has no rebuild the framework could perform, so the eltypes can come from nowhere but the allocator's own argument (D-077, D-263).", "A factorization, a plan or a buffer sized by the scalar has no rebuild the framework could perform. So the eltypes can come from nowhere but the allocator's own argument (D-077, D-263).", ["D-077", "D-263"], None, "F", None),
("The allocator is called once per activation (the build's typed products at a given scalar type) and once per scratch-store set (§14.8).", "The allocator is called once per activation and once per scratch-store set (§14.8, D-077).", ["§14.8"], ["§14.8", "D-077"], "C", None),
("Sizes come from the instance, and eltypes from the activation.", "Sizes come from the instance, and eltypes from the activation.", [], None, "F", None),
("Nothing downstream derives from a workspace's type, and mistyped scratch detonates loudly at the `Dual` probe.", "Nothing downstream derives from a workspace's type, and mistyped scratch detonates loudly at the `Dual` probe (the build's single evaluation of a user function).", [], None, "F", None),
("The `undef` spelling is the recommended idiom and the sole visible marker that contents are meaningless.", "The `undef` spelling is the recommended idiom and the sole visible marker that contents are meaningless.", [], None, "F", None),
("It puts that fact in the declaration, which is the by-allocation convention this store actually lives in.", "It puts that fact in the declaration. That is the by-allocation convention this declaration actually lives in.", [], None, "R", "R8"),
("Declaration is by allocation, never by initial value (D-077).", "Declaration is by allocation, never by initial value (D-077).", ["D-077"], None, "F", None),
("The `init_` prefix means establish, as the device contract's `init!` does (§11.6), and carries no claim that the allocated contents are a value (D-220).", "The `init` in `ws_init` means establish, as the device contract's `init!` does (§11.6). It carries no claim that the allocated contents are a value (D-220).", ["§11.6", "D-220"], None, "R", "R8"),
("Available on both tiers.", "takes the activation scalar on both tiers", [], [], "R", "R6"),
("Nothing in the workspace contract is tier-specific, and a continuous workspace simply joins the `T`-generic surface.", "Nothing in the workspace contract is tier-specific, and a continuous workspace simply joins the `T`-generic surface.", [], None, "R", "R6"),
("Under a `Dual` activation the allocator is called at `Dual`, and the in-place math runs through Julia's generic fallbacks.", "Under a `Dual` activation the allocator is called at `Dual`, and the in-place math runs through Julia's generic fallbacks.", [], None, "R", "R6"),
("No BLAS is involved.", "No BLAS is involved.", [], None, "R", "R6"),
("Activations probe and linearize, they don't run marathons.", "Activations probe and linearize. They don't run marathons.", [], None, "R", "R6"),
("The continuous side runs many calls per boundary, for RK stages, localization trial evaluations and event re-sweeps.", "The continuous side runs many calls per boundary (a published consistency point), for RK stages, localization trial evaluations and event re-sweeps.", [], None, "F", None),
("That multiplicity makes the no-information-between-calls contract more essential there, not less.", "That multiplicity makes the no-information-between-calls contract more essential there, not less.", [], None, "F", None),
("The blessed idiom for zero-allocation ticks with immutable `s`. Do the in-place math (`mul!`, `cholesky!`, BLAS) on the workspace.", "The blessed (explicitly sanctioned) idiom for zero-allocation ticks with immutable `s` does the in-place math (`mul!`, `cholesky!`, BLAS) on the workspace (D-013).", [], ["D-013"], "C", None),
("At the end, snapshot into an isbits container and return it, as in `s = KFState(SVector{20}(ws.x̂), SMatrix{20,20}(ws.P))`.", "At the end, it snapshots into an isbits container and returns it, as in `s = KFState(SVector{20}(ws.x̂), SMatrix{20,20}(ws.P))`.", [], None, "F", None),
("The blessed idiom for a PRNG in a discrete leaf.", "In the blessed idiom for a PRNG in a discrete leaf,", [], None, "X", None),
("A generator object such as `Xoshiro` is mutable, so it is scratch and lives in the workspace, allocated once.", "a generator object such as `Xoshiro` lives in the workspace, and the values that determine its next draw are state in `s` (D-231). The generator is mutable, so it is scratch and lives in the workspace, allocated once.", [], ["D-231"], "R", "R4"),
("The values that determine its next draw are immutable, so they are state and live in `s`, which is what makes replay deterministic (§2.2).", "The values are immutable, so they are state and live in `s`. Keeping them in `s` is what makes replay deterministic (§2.2).", ["§2.2"], None, "F", None),
("The tick loads them into the generator at entry and snapshots them back at exit, in the same shape as the Kalman idiom above.", "The tick loads them into the generator at entry and snapshots them back at exit, in the same shape as the Kalman idiom above.", [], None, "F", None),
(SO, S, [], None, "R", "R8"),
(FN, FN, [], None, "F", None),
("Rematerializing the generator from its values each tick reads naturally and allocates.", "Rematerializing the generator from its values each tick reads naturally and allocates.", [], None, "F", None),
("A sampler with an out-of-line tail lets the object escape (D-231).", "A sampler with an out-of-line tail lets the object escape (D-231).", ["D-231"], None, "F", None),
("Construction and storage of large `SArray`s are cheap and compile fine.", "Construction and storage of large `SArray`s are cheap and compile fine.", [], None, "F", None),
("The StaticArrays \"codegen catastrophe\" lives in its operations, the unrolled matmuls, which are never called on snapshots.", "The StaticArrays \"codegen catastrophe\" lives in its operations, the unrolled matmuls, which are never called on snapshots.", [], None, "F", None),
("The discipline is that snapshot values are for storage, logging and element access only, never arithmetic.", "The discipline is that snapshot values are for storage, logging and element access only, never arithmetic.", [], None, "F", None),
("It is optionally enforceable by an op-forbidding `ValueSnapshot{N,T}` wrapper, an `NTuple` with only `getindex` and iteration, structurally what `SArray` is minus the methods.", "It is optionally enforceable by an op-forbidding `ValueSnapshot{N,T}` wrapper. That wrapper is an `NTuple` with only `getindex` and iteration, structurally what `SArray` is minus the methods.", [], None, "F", None),
("The practical ceiling is a few KB comfortable and tens of KB defensible.", "The practical ceiling is a few KB comfortable and tens of KB defensible.", [], None, "F", None),
("Beyond that, value semantics stop making sense.", "Beyond that, value semantics stop making sense.", [], None, "F", None),
("(the build's typed products at a given scalar type)", "An activation is the build's typed products at a given scalar type", [], None, "F", None),
]
added = [
"(the contiguous vector backing all continuous state)",
"The section states the rules of the `s` and `m` stores (the framework-owned homes of those letters) first, then the workspace's rules, then the idioms that join the two homes.",
"The rule rests on what state is.",
"(the instants a discrete component runs)",
"(the ordinary loop re-driven from the trace)",
"and a tier is the continuous or the discrete side.",
"(the build's single evaluation of a user function)",
"(a published consistency point)",
"(explicitly sanctioned)",
"#### Idioms",
]
claims = []
for i, (o, n, c, nc, t, r) in enumerate(rows, 1):
    d = {"id": f"C-{i:03d}", "old": o, "new": n, "where": "new", "cites": c}
    if nc is not None: d["newcites"] = nc
    d["tag"] = t
    if r: d["ruling"] = r
    claims.append(d)
json.dump({"claims": claims, "added": added}, open("/Users/miguel/.julia/dev/Cadence.jl/docs/spec_rewrite/ch07/units/C/inventory.json", "w"), ensure_ascii=False, indent=1)
