# Scratch: builds inventory.json for unit E. Each row: old span, new span, cites, newcites, tag[, ruling].
import json, os
H = os.path.dirname(os.path.abspath(__file__))
CODE_OLD = "`remaining = deadline - margin - τ() remaining > 0 && sleep(remaining) # coarse phase: cheap, lower-bound-only (runs at most once) while τ() < deadline # spin phase: µs-precise, CPU cost bounded by margin GC.safepoint() # a safepoint, never a yield: GC and signals get through end`"
R = [
 ("### 10.7 Real-time pacing", "### 10.7 Real-time pacing", [], None, "X"),
 ("Pacing is outside the semantics.", "Pacing is outside the semantics (D-021).", [], ["D-021"], "C"),
 ("That is the section's invariant.", "That is the section's invariant.", [], None, "F"),
 ("The pacer inserts waits between completed frames.", "The pacer inserts waits between completed frames (iterations of the loop).", [], None, "F"),
 ("It never reorders, skips or alters the boundary sequence.", "It never reorders, skips or alters the boundary sequence.", [], None, "F"),
 ("A paced and an unpaced run with identical input traces produce bit-identical trajectories,", "A paced and an unpaced run with identical input traces (the records of each frame's drained inputs) produce bit-identical trajectories.", [], None, "F"),
 ("so deterministic replay (§2.2) extends over pace.", "So deterministic replay (§2.2) extends over pace.", ["§2.2"], None, "F"),
 ("Interactive runs differ only because their inputs differ.", "Interactive runs differ only because their inputs differ.", [], None, "F"),
 ("Detection policy is inside the semantics.", "Detection policy is inside the semantics.", [], None, "F"),
 ("Event localization runs identically paced or unpaced, and its sweep cost is absorbed as debt like any other expensive frame (§10.4).",
  "Event localization runs identically paced or unpaced (§10.4, D-080). Its sweep cost is absorbed as debt (wall time that later frames repay) like any other expensive frame (D-080).", ["§10.4"], ["§10.4", "D-080"], "C"),
 ("Degrading to boundary detection under pacing was rejected (D-080).", "Degrading to boundary detection under pacing was rejected (D-080).", ["D-080"], None, "F"),
 ("The wall-clock map is piecewise affine, re-anchored at every knee.", "The wall-clock map is piecewise affine, re-anchored at every knee (D-021).", [], ["D-021"], "C"),
 ("The map is $\\tau(t) = \\tau_{\\mathrm{anchor}} + (t - t_{\\mathrm{anchor}})/p$, with the anchor pair as its reference point.", "The map is $\\tau(t) = \\tau_{\\mathrm{anchor}} + (t - t_{\\mathrm{anchor}})/p$, with the anchor pair as its reference point.", [], None, "F"),
 ("A live pace change re-establishes the anchor at the current `(t, τ)`, so the new slope applies only forward (D-021).", "A live pace change re-establishes the anchor at the current `(t, τ)`, so the new slope applies only forward (D-021).", ["D-021"], None, "F"),
 ("Un-pause re-anchors for the same reason.", "Un-pause re-anchors for the same reason.", [], None, "F"),
 ("Debt is cleared at re-anchor.", "Debt is cleared at re-anchor.", [], None, "F"),
 ("A deliberate user action is a natural sync point,", "A deliberate user action is a natural sync point.", [], None, "F"),
 ("and the counters record what was forgiven.", "The counters record what was forgiven.", [], None, "F"),
 ("The frame that follows an anchor has no wait, its deadline being the anchor itself.", "The frame that follows an anchor has no wait, because its deadline is the anchor itself.", [], None, "F"),
 ("The run's first anchor is taken when its loop starts, so the first frame runs at once (D-269).", "The run's first anchor is taken when its loop starts, so the first frame runs at once (D-269).", ["D-269"], None, "F"),
 ("Deadline law: an absolute schedule with bounded debt (D-021).", "The deadline law is an absolute schedule with bounded debt (D-021).", ["D-021"], None, "F"),
 ("Frame deadlines come from the map.", "Frame deadlines come from the map.", [], None, "F"),
 ("A frame that exceeds its wall budget `h/p` leaves debt,", "A frame that exceeds its wall budget `h/p` leaves debt.", [], None, "F"),
 ("and subsequent frames repay it by running short or without waiting.", "Subsequent frames repay it by running short or without waiting.", [], None, "F"),
 ("The long-run rate is therefore exact, and ms-scale hiccups from GC or the scheduler are invisible.", "The long-run rate is therefore exact, and ms-scale hiccups from GC or the scheduler are invisible.", [], None, "F"),
 ("Debt beyond a threshold of five frames' worth of budget, `5·h/p`, is forgiven by re-anchor plus a warning,", "Debt beyond a threshold of five frames' worth of budget, `5·h/p`, is forgiven by re-anchor plus a warning (D-133).", [], ["D-133"], "C"),
 ("so long stalls (a debugger, laptop sleep) do not trigger catch-up bursts.", "As a result, long stalls (a debugger, laptop sleep) do not trigger catch-up bursts.", [], None, "F"),
 ("Five frames' worth sits comfortably above the ms-scale hiccups that debt exists to absorb silently, and far below the seconds-to-minutes stalls that forgiveness exists for.", "Five frames' worth sits comfortably above the ms-scale hiccups that debt exists to absorb silently, and far below the seconds-to-minutes stalls that forgiveness exists for.", [], None, "F"),
 ("Neither case lands near the threshold.", "Neither case lands near the threshold.", [], None, "F"),
 ("`p = ∞` is pacer-off, not a limit value (D-021).", "`p = ∞` is pacer-off, not a limit value (D-021).", ["D-021"], None, "F"),
 ("Unpaced mode is the explicit absence of deadlines.", "Unpaced mode is the explicit absence of deadlines.", [], None, "F"),
 ("There are no waits, no debt and no warnings.", "There are no waits, no debt and no warnings.", [], None, "F"),
 ("By the invariant, it is the same execution with the waits deleted.", "By the invariant, it is the same execution with the waits deleted.", [], None, "F"),
 ("The wait mechanism is a hybrid sleep-then-spin with one knob.", "The wait mechanism is a hybrid sleep-then-spin with one knob (D-021).", [], ["D-021"], "C"),
 ("Non-realtime OSes guarantee only a lower bound on sleep.", "Non-realtime OSes guarantee only a lower bound on sleep.", [], None, "F"),
 ("The thread becomes runnable no earlier than requested,", "The thread becomes runnable no earlier than requested.", [], None, "F"),
 ("and the wake-up is best-effort, subject to timer granularity, scheduler load and macOS timer coalescing, with no hard upper bound.", "The wake-up is best-effort, subject to timer granularity, scheduler load and macOS timer coalescing, with no hard upper bound.", [], None, "F"),
 ("Measured on the dev machine, idle, against 2 ms requests (2026-07), Julia `sleep` overshoots by about 1.4 ms median, and `Libc.systemsleep` by about 0.5 ms.", "Measured on the dev machine, idle, against 2 ms requests (2026-07), Julia `sleep` overshoots by about 1.4 ms median, and `Libc.systemsleep` by about 0.5 ms.", [], None, "F"),
 ("Behind the `sleep` figure are libuv's millisecond-granularity timers.", "Behind the `sleep` figure are libuv's millisecond-granularity timers.", [], None, "F"),
 ("Sub-ms requests are accepted and rounded up.", "Sub-ms requests are accepted and rounded up.", [], None, "F"),
 ("Spikes under load are unbounded.", "Spikes under load are unbounded.", [], None, "F"),
 ("The pacer therefore sleeps toward `deadline − margin` and spins the remainder:", "The pacer therefore sleeps toward `deadline − margin` and spins the remainder:", [], None, "F"),
 (CODE_OLD, CODE_OLD, [], None, "F"),
 ("`margin` is a single constant calibrated to cover the primitive's granularity plus typical overshoot.", "`margin` is a single constant calibrated to cover the primitive's granularity plus typical overshoot (D-021).", [], ["D-021"], "C"),
 ("There is no second threshold.", "There is no second threshold.", [], None, "F"),
 ("The resolution floor is absorbed into the calibration,", "The resolution floor is absorbed into the calibration.", [], None, "F"),
 ("and a margin below the primitive's granularity defeats the spin phase's purpose.", "A margin below the primitive's granularity defeats the spin phase's purpose.", [], None, "F"),
 ("Its default is 2 ms, the value the measurements above imply.", "The default `margin` is 2 ms (D-133), the value the measurements above imply.", [], ["D-133"], "C"),
 ("It covers libuv's millisecond timer granularity and `sleep`'s median overshoot of about 1.4 ms,", "It covers libuv's millisecond timer granularity and `sleep`'s median overshoot of about 1.4 ms.", [], None, "F"),
 ("while anything larger merely spends more core in the spin phase.", "Anything larger merely spends more core in the spin phase.", [], None, "F"),
 ("The knob spans the whole design space:", "The knob spans the whole design space (D-021):", [], ["D-021"], "C"),
 ("- `margin = 0`, pure sleep. Cheapest in CPU.", "`margin = 0` is pure sleep, the cheapest in CPU.", [], None, "F"),
 ("Frame spacing is bursty, but the absolute schedule still delivers the exact average rate through debt repayment.", "Frame spacing is bursty, but the absolute schedule still delivers the exact average rate through debt repayment.", [], None, "F"),
 ("The spin phase buys regularity, never rate correctness.", "The spin phase buys regularity, never rate correctness.", [], None, "F"),
 ("- `margin = 2 ms`, the hybrid default.", "`margin = 2 ms` is the hybrid default.", [], None, "F"),
 ("Sleeps about 90% of a 20 ms budget and lands within µs of the deadline at a few percent of one core.", "It sleeps about 90% of a 20 ms budget and lands within µs of the deadline at a few percent of one core.", [], None, "F"),
 ("- `margin = ∞`, pure busy-wait. FlightCore's behavior, with maximum frame regularity at one pinned core.", "`margin = ∞` is pure busy-wait, FlightCore's behavior, with maximum frame regularity at one pinned core.", [], None, "F"),
 ("The \"best attempt at real time\" mode is the knob's endpoint, not a separate mechanism.", "The \"best attempt at real time\" mode is the knob's endpoint, not a separate mechanism.", [], None, "F"),
 ("When the frame budget is at or below the margin (for example `h = 0.01` at `p = 5`, a 2 ms budget), the hybrid degenerates to pure spin per frame by construction.", "When the frame budget is at or below the margin (for example `h = 0.01` at `p = 5`, a 2 ms budget), the hybrid degenerates to pure spin per frame by construction.", [], None, "F"),
 ("Rare wake-ups past the deadline are overruns, absorbed as debt.", "Rare wake-ups past the deadline are overruns, absorbed as debt.", [], None, "F"),
 ("Which primitive the coarse phase uses, task-yielding `sleep` or thread-blocking `Libc.systemsleep`, is settled in §12.2.", "Which primitive the coarse phase uses, task-yielding `sleep` or thread-blocking `Libc.systemsleep`, is settled in §12.2.", ["§12.2"], None, "F"),
 ("The coarse phase uses task-yielding `sleep`, with `margin` absorbing its overshoot.", "The coarse phase uses task-yielding `sleep`, with `margin` absorbing its overshoot (D-027).", [], ["D-027"], "C"),
 ("The wait sits at the frame top, after the control plane is consulted.", "The wait sits at the frame top, after the control plane (the atomic surface carrying pause, pace and stop) is consulted.", [], None, "F"),
 ("A control change issued during a wait is observed at the next frame top, at most one frame budget `h/p` later (§12.1, D-269).", "A control change issued during a wait is observed at the next frame top, at most one frame budget `h/p` later (§12.1, D-269).", ["§12.1", "D-269"], None, "F"),
 ("The wait is an unmask point for the operator interrupt (§12.4),", "The wait is an unmask point (§12.4, D-132) for the operator interrupt (Ctrl-C in an interactive session).", ["§12.4"], ["§12.4", "D-132"], "C"),
 ("which raises out of the coarse phase's `sleep`.", "The interrupt raises out of the coarse phase's `sleep`.", [], None, "F"),
 ("Diagnostics.", "#### Diagnostics", [], None, "X"),
 ("Overrun count, current and peak debt, forgiven-debt events and wait statistics are published as framework status (the frozen diagnostics value each snapshot carries beside the table) for GUI and logs.", "Overrun count, current and peak debt, forgiven-debt events and wait statistics are published as framework status (the frozen diagnostics value each snapshot carries beside the signal table) for GUI and logs.", [], None, "F"),
 ("The record carries `pace`, the pace the loop's frames run under (`Inf` where no frame waits);", "The record carries `pace`, the pace the loop's frames run under (`Inf` where no frame waits).", [], ["D-269"], "F"),
 ("`debt` and `peak_debt`, in seconds; `overruns`, the frames that exceeded their budget;", "It carries `debt` and `peak_debt`, in seconds, and `overruns`, the frames that exceeded their budget.", [], ["D-269"], "F"),
 ("`reanchors`, every re-anchor after the run's first, and `forgiven`, the seconds of debt those re-anchors cleared;", "It carries `reanchors`, every re-anchor after the run's first, and `forgiven`, the seconds of debt those re-anchors cleared.", [], ["D-269"], "F"),
 ("and `waits` and `waited`, the frames that waited and their total wall time (D-269).", "It also carries `waits` and `waited`, the frames that waited and their total wall time (D-269).", ["D-269"], None, "F"),
 ("A deliberate re-anchor, a pace change or an un-pause, is counted and raises no warning.", "A deliberate re-anchor, from a pace change or an un-pause, is counted and raises no warning.", [], None, "F"),
 ("The forgiveness re-anchor is counted and reports `DebtReanchor` (Appendix C).", "The forgiveness re-anchor is counted and reports `DebtReanchor` (Appendix C).", ["Appendix C"], None, "F"),
 ("A live switch to `p = ∞` is a pace change like any other:", "A live switch to `p = ∞` is a pace change like any other.", [], ["D-269"], "F"),
 ("it re-anchors, and the debt it clears is counted as forgiven (D-269).", "It re-anchors, and the debt it clears is counted as forgiven (D-269).", ["D-269"], None, "F"),
 ("Forward pointers.", "#### Where staging and concurrency live", [], None, "X"),
 ("The wait interval is the natural staging slot for externally injected inputs,", "The wait interval is the natural staging slot for externally injected inputs,", [], None, "F"),
 ("applied at the next boundary.", "which are drained at the next frame top.", [], None, "R", "R8-F11"),
 ("The staging rules belong to §11 and §12, as does the concurrency model generally,", "The staging rules belong to §11 and §12, as does the concurrency model generally.", ["§11", "§12"], None, "F"),
 ("which §10.3 constrains but does not decide.", "§10.3 constrains the concurrency model but does not decide it.", ["§10.3"], None, "F"),
 ("---", "---", [], None, "X"),
]
claims = []
for i, r in enumerate(R, 1):
    old, new, cites, newcites, tag = r[:5]
    c = {"id": f"E-{i:03d}", "old": old, "new": new, "where": "new", "cites": cites}
    if newcites is not None: c["newcites"] = newcites
    c["tag"] = tag
    if len(r) > 5: c["ruling"] = r[5]
    claims.append(c)
added = [
    "This section covers pacing (the waits that hold a run to wall-clock time).",
    "Its parts are the invariant with the wall-clock map, the wait, the diagnostics, and where staging and concurrency live.",
    "#### The invariant and the wall-clock map",
    "#### The wait",
    "(iterations of the loop)",
    "(the records of each frame's drained inputs)",
    "(wall time that later frames repay)",
    "(Ctrl-C in an interactive session)",
    "(the atomic surface carrying pause, pace and stop)",
    "Here $p$ is the pace and $\\tau$ is wall-clock time.",
    "The anchor pair $(t_{\\mathrm{anchor}}, \\tau_{\\mathrm{anchor}})$ is the sim time and wall-clock time at the most recent anchor.",
]
json.dump({"claims": claims, "added": added}, open(os.path.join(H, "inventory.json"), "w"), ensure_ascii=False, indent=1)
